### ISSUE TITLE
防止开发者调用__dict__.clear()

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#1010]
调用这个方法后，引擎无法捕获到可能连实体def属性都清空了， 造成一些意外错误。可以考虑动态删除实体这个方法。

**Comment by jay602** [comment]
PyObject* pyEntityDictData = PyObject_GetAttrString(this, "__dict__");
PyObject_DelAttrString(pyEntityDictData , “clear”);
Py_DECREF(pyEntityDictData);

**Comment by kebiao** [comment]
由于clear是只读属性，无法操作
