### ISSUE TITLE
一个实体executeRaw操作不当，引发其他实体exeRaw异常

### ISSUE THREAD

**Issue by blackberry123** [kbengine/kbengine#1030]
`# -*- coding: utf-8 -*-
import KBEngine
from KBEDebug import *
import traceback

class EntityA(KBEngine.Entity):
    """
    """
    def __init__(self):
        KBEngine.Entity.__init__(self)
        self.addTimer(2, 0, 1)

    def onTimer(self, id, userArg):
        self.load_data()

    def load_data(self):
        sql = 'SELECT id FROM db_entity_a;'
        KBEngine.executeRawDatabaseCommand(sql, self.on_query_from_db, -1)

    def on_query_from_db(self, res, lines, insert_id, err):
        ERROR_MSG('...... EntityA on_query_from_db : res = %s ' % (res))
        try:
            for item in res:
                id = int(item[0].decode())
                ERROR_MSG('...... EntityA id: = %i ' % (id))
        except:
            traceback.print_exc()`

`# -*- coding: utf-8 -*-
import KBEngine
from KBEDebug import *
import traceback

class EntityB(KBEngine.Entity):
    def __init__(self):
        KBEngine.Entity.__init__(self)
        self.addTimer(2, 0, 1)

    def onTimer(self, id, userArg):
        self.load_data()

    def load_data(self):
        sql = ('SELECT id FROM db_entity_b WHERE id > %i;', (0))
        KBEngine.executeRawDatabaseCommand(sql, self.on_query_from_db, -1)

    def on_query_from_db(self, res, lines, insert_id, err):
        ERROR_MSG('...... EntityB on_query_from_db : res = %s ' % (res))
        try:
            for item in res:
                id = int(item[0].decode())
                ERROR_MSG('...... EntityB id: = %i ' % (id))
        except:
            traceback.print_exc()`
EntityA.def,EntityB.def相同 没任何定义
`<root>
	<Properties>
	</Properties>

	<BaseMethods>
	</BaseMethods>

</root>`
测试如下:
情况1
`def onBaseAppReady(isBootstrap):
    if isBootstrap:  # 是第一个启动的baseapp
        KBEngine.createEntityLocally("EntityA", {})
        # KBEngine.createEntityLocally("EntityB", {})`
启动后 可以看到日志结果正常，说明EntityA是OK.
...... EntityA id: = 1 
-----------------------------------------------------------
情况2
`def onBaseAppReady(isBootstrap):
    if isBootstrap:  # 是第一个启动的baseapp
        KBEngine.createEntityLocally("EntityA", {})
        KBEngine.createEntityLocally("EntityB", {})`

再次启动 可以看到如下异常
` ERROR root [0x00000e98] [2019-01-28 11:50:00,870] - KBEngine::executeRawDatabaseCommand: execute error!
 S_ERR root [0x00000e98] [2019-01-28 11:50:00,920] - ...... EntityA on_query_from_db : res = [[b'1']] Traceback (most recent call last):
  File "H:/workspace/scripts_test/base\EntityA.py", line 22, in on_query_from_db
    ERROR_MSG('...... EntityA on_query_from_db : res = %s ' % (res))
 S_ERR root [0x00000e98] [2019-01-28 11:50:00,930] -   File "H:/workspace/scripts_test/common\KBEDebug.py", line 28, in ERROR_MSG
    printMsg(args, True)
 S_ERR root [0x00000e98] [2019-01-28 11:50:00,930] -   File "H:/workspace/scripts_test/common\KBEDebug.py", line 6, in printMsg
    for m in args:print (m)
 S_ERR root [0x00000e98] [2019-01-28 11:50:00,930] - TypeError: 'tuple' does not support the buffer interface`

**Comment by blackberry123** [comment]
附上sql
`/*
Navicat MySQL Data Transfer

Target Server Type    : MYSQL
Target Server Version : 50642
File Encoding         : 65001

Date: 2019-01-28 12:00:12
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `db_entity_a`
-- ----------------------------
DROP TABLE IF EXISTS `db_entity_a`;
CREATE TABLE `db_entity_a` (
  `id` bigint(20) NOT NULL DEFAULT '0',
  `name` varchar(15) CHARACTER SET utf8 DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
-- Records of db_entity_a
-- ----------------------------
INSERT INTO `db_entity_a` VALUES ('1', 'test_a');

-- ----------------------------
-- Table structure for `db_entity_b`
-- ----------------------------
DROP TABLE IF EXISTS `db_entity_b`;
CREATE TABLE `db_entity_b` (
  `id` bigint(20) NOT NULL DEFAULT '0',
  `name` varchar(15) CHARACTER SET utf8 DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
-- Records of db_entity_b
-- ----------------------------
INSERT INTO `db_entity_b` VALUES ('1', 'test_b');
`

**Comment by kebiao** [comment]
[bug_test.zip](https://github.com/kbengine/kbengine/files/2801379/bug_test.zip)
![mrr2h y s fmba4q abpvco](https://user-images.githubusercontent.com/2352650/51814150-e6241600-22f4-11e9-9e80-1a13fda3d433.png)
![nc 90 f 5 hf3 ls vtn](https://user-images.githubusercontent.com/2352650/51814152-eae8ca00-22f4-11e9-8554-a2f8fa7b6413.png)
只开其中一个 NoticeComponent是正常的

**Comment by blackberry123** [comment]
[bug_test.zip](https://github.com/kbengine/kbengine/files/2801401/bug_test.zip)
在default db中 加入zip附带的sql 即可测试重新

**Comment by jay602** [comment]
我也测一下，也输出同样的结果：
` S_ERR    baseapp01 32135 70012  [2019-02-01 15:05:35 818] - ...... NoticeComponent 滚动公告 数据: [类型: 0,标题: 标题2, 内容: 跑马灯2] `

但看不明白是什么错

**Comment by blackberry123** [comment]
> 我也测一下，也输出同样的结果：
> `S_ERR baseapp01 32135 70012 [2019-02-01 15:05:35 818] - ...... NoticeComponent 滚动公告 数据: [类型: 0,标题: 标题2, 内容: 跑马灯2]`
> 
> 但看不明白是什么错， 你认为什么样才是正确的？

再打开注释（CreateEntityLocally） 你会发现现在这个正常的变不正常

**Comment by jay602** [comment]
`def load_user_achievement_data(self):
        """
        加载玩家成就数据
        :return:
        """
        # 1.sql不应该是个tuple作为查询语句 只能是这个string, 拼接的话 也是这样拼接的
        # sql = 'select xx ... where 字段1 = %i,字段2 = %i;' % (value1, value2)
        sql = ('SELECT achievement_id, current_progress, flag, claim_reward_flag, claim_reward_timestamp FROM user_achievement_info where id = %i;', (self.id))
        # 执行DB操作 等待异步返回
        # 参数3：指定一个线程来处理本条命令。用户可以通过这个参数控制某一类命令的执行先后顺序
        KBEngine.executeRawDatabaseCommand(sql, self.on_query_from_db_user_achievement, -1)`


![qq 20190213103054](https://user-images.githubusercontent.com/5274872/52682654-21704700-2f7b-11e9-95de-22359707483e.jpg)

`sql = ('SELECT achievement_id, current_progress, flag, claim_reward_flag, claim_reward_timestamp FROM user_achievement_info where id = %i;', (self.id))`

TypeError: a bytes-like object is required, not 'tuple'
你传的sql语句，是tupe类型，不是string类型

更新下引擎，这样就不会崩了
