### ISSUE TITLE
数据库大小写问题

### ISSUE THREAD

**Issue by Jacklibobo** [kbengine/kbengine#1055]
kbengine压测，我这边使用的是华为云数据库mysql，但是默认生成的lower_case_table_names=1。这样sql语句就因大小写问题报错，怎么样才能做到0,1都可以执行呢？

**Comment by kebiao** [comment]
能把报的错贴上来吗

**Comment by kebiao** [comment]
https://bbs.comblockengine.com/forum.php?mod=viewthread&tid=5952&extra=page%3D1

**Comment by Jacklibobo** [comment]
新版本可以解决云数据库大小写的问题吗？具体哪个版本以上呢？

**Comment by kebiao** [comment]
你用1.3.1试试
