### ISSUE TITLE
自定义类型赋值不正确没有提示？

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#1064]
发现好像定义在def中的属性，都是严格检查类型的，比如def中定义了一个属性类型是UINT32，然后在python中如果给这个属性加上一个float，这个赋值是完全无效的，这个倒是能接受没问题，但是没有打印任何警告和错误

**Comment by jay602** [comment]
![qq 20190220151503](https://user-images.githubusercontent.com/5274872/53074410-a46a4200-3525-11e9-9971-769839f8ffa5.png)

HP属性的类型为INT32
测过了，有提示

**Comment by lupurs** [comment]
某些情况下，自定义类型做+=运算会无效，且没有提示
![image](https://user-images.githubusercontent.com/7885407/53078368-04b1b180-352f-11e9-9016-8ef271c14833.png)
有些情况下又有
![image](https://user-images.githubusercontent.com/7885407/53078381-0e3b1980-352f-11e9-80fb-c673a5845ab8.png)


没有提示的结构体定义如下：
![image](https://user-images.githubusercontent.com/7885407/53078395-15fabe00-352f-11e9-98e5-92a82900c123.png)
![image](https://user-images.githubusercontent.com/7885407/53078400-18f5ae80-352f-11e9-8331-9ae3e869b260.png)

**Comment by jay602** [comment]
我测了好多次，都没重现
![qq 20190220192812](https://user-images.githubusercontent.com/5274872/53089011-544fa780-3546-11e9-8251-08fb89cd3bf0.png)
![qq 20190220192836](https://user-images.githubusercontent.com/5274872/53089015-56b20180-3546-11e9-9c6e-2f772137830f.png)
![qq 20190220192913](https://user-images.githubusercontent.com/5274872/53089018-59145b80-3546-11e9-9549-a4d4716ee14e.png)

**Comment by lupurs** [comment]
重现步骤：
1.定义如下数据结构

**Comment by jay602** [comment]
按照你的步骤，也没复现，你用最新的版本来测看看
![qq 20190221172742](https://user-images.githubusercontent.com/5274872/53158567-e3b89180-35fe-11e9-82e5-eeaec6c943f0.png)
![qq 20190221172753](https://user-images.githubusercontent.com/5274872/53158570-e4e9be80-35fe-11e9-8843-d8610b6255a7.png)
![qq 20190221172812](https://user-images.githubusercontent.com/5274872/53158573-e74c1880-35fe-11e9-8b32-365762d151d8.png)
![qq 20190221172831](https://user-images.githubusercontent.com/5274872/53158576-e7e4af00-35fe-11e9-8d78-28679e6f99e6.png)

**Comment by kebiao** [comment]
```
bool FixedDict::checkDataChanged(const char* keyName, PyObject* value, bool isDelete)
{
	FixedDictType::FIXEDDICT_KEYTYPE_MAP& keyTypes = _dataType->getKeyTypes();
	FixedDictType::FIXEDDICT_KEYTYPE_MAP::const_iterator iter = keyTypes.begin();
	
	for(; iter != keyTypes.end(); ++iter)
	{
		if((*iter).first == keyName)
		{
			if(isDelete)
			{
				char err[255];
				kbe_snprintf(err, 255, "can't delete from FIXED_DICT key[%s].\n", keyName);
				PyErr_SetString(PyExc_TypeError, err);
				PyErr_PrintEx(0);
				return false;
			}
			else
			{
				DataType* dataType = (*iter).second->dataType;
				if(!dataType->isSameType(value)){
					return false;
				}
			}

			return true;
		}
	}

	char err[255];
	kbe_snprintf(err, 255, "set FIXED_DICT to a unknown key[%s].\n", keyName);
	PyErr_SetString(PyExc_TypeError, err);
	PyErr_PrintEx(0);
	return false;
}
```

由于老版本中uint32.isSameType中没有输出错误提示，所以没有很好的显示错误
