### ISSUE TITLE
 linux mariadb make错误

### ISSUE THREAD

**Issue by flyarong** [kbengine/kbengine#1089]
entity_table_mysql.cpp: In function ‘bool KBEngine::sync_item_to_db(KBEngine::DBInterface*, const char*, const char*, const char*, KBEngine::uint32, enum_field_types, unsigned int, void*, KBEngine::onSyncItemToDBSuccessPtr)’:
entity_table_mysql.cpp:42:95: error: ‘SYSTEM_CHARSET_MBMAXLEN’ was not declared in this scope
    if ((length == 0) || (sqlitemtype == FIELD_TYPE_VAR_STRING ? (int32)length == tf.length / SYSTEM_CHARSET_MBMAXLEN/*Mysql将length放大了N倍*/ : 
					(int32)length == tf.length))

看不懂啊

**Comment by flyzjr** [comment]
SYSTEM_MB_MAX_CHAR_LENGTH by mariadb

**Comment by woshi91** [comment]
error: ‘SYSTEM_CHARSET_MBMAXLEN’ was not declared in this scope

**Comment by kebiao** [comment]
数据库是什么版本？

**Comment by flyarong** [comment]
mysql  Ver 15.1 Distrib 10.3.2-MariaDB, for Linux (x86_64) using readline 5.1
CentOS Linux release 7.4.1708 (Core) 
引擎版本就是clone的版本。

应该是mariadb没有
SYSTEM_CHARSET_MBMAXLEN，相似的是
SYSTEM_MB_MAX_CHAR_LENGTH。

新问题：
g++ -m64 -fPIC -pipe -Wall -Wno-deprecated -Wno-uninitialized -Wno-char-subscripts -fno-strict-aliasing -Wno-non-virtual-dtor -Wno-invalid-offsetof -Werror -std=c++11 -O3 -g -L/home/zjrvps/kbengine/kbe/src/libs -export-dynamic -Wl,--hash-style=both   -o /home/zjrvps/kbengine/kbe/bin/server/dbmgr Hybrid64/buffered_dbtasks.o Hybrid64/dbmgr.o Hybrid64/dbmgr_interface.o Hybrid64/dbtasks.o Hybrid64/entity_component.o Hybrid64/interfaces_handler.o Hybrid64/main.o Hybrid64/profile.o Hybrid64/sync_app_datas_handler.o Hybrid64/update_dblog_handler.o -lentitydef -lserver -lpyscript -lnetwork -lthread -ldb_interface -ldb_mysql -ldb_redis -lmath -lcommon -lhelper -lresmgr -lcurl -lpython -lpthread -lutil -ldl `/usr/bin/mysql_config --libs_r` -lhiredis -llog4cxx -lapr-1 -laprutil-1 -lexpat -lssl -lcrypto -ldl -lg3dlite -lsigar -ljemalloc -lrt -ltinyxml -lm -lfmt -lz -lpthread 
/usr/bin/ld: cannot find -lmariadb

**Comment by kebiao** [comment]
装mysql吧

**Comment by kebiao** [comment]
mariadb 后面有时间我们看看是怎么回事

**Comment by jay602** [comment]
在centos7中测试过，yum install -y mariadb mariadb-server mariadb-devel，安装好这三个，编译没问题
