### ISSUE TITLE
writeToDB增加了数据变化检查，没变化时没有调用callback

### ISSUE THREAD

**Issue by zhangteng0606** [kbengine/kbengine#1099]
writeToDB的callback参数在数据没变化时未被调用，版本2.3.5

**Comment by kebiao** [comment]
没变化所以不存档， 也就没调用，你这个需求具体是想做些什么？ 可以考虑修改一下变量？

**Comment by zhangteng0606** [comment]
脚本内会在数据库写入成功后有一些额外的逻辑，设计如此的话就无视吧，我已经按我们需求在引擎内加了调用了。。

**Comment by kebiao** [comment]
嗯， 为了降低存档负担， 做了优化， 就是如此设计的。
而此时的确就是没有写入，所以就不调用， 你可以按需自己改
