### ISSUE TITLE
我在onAutoLoadEntityCreate 实现KBEngine.createEntityFromDBID(entityType, dbid)了这个方法，dbmgr报错

### ISSUE THREAD

**Issue by huangjiamin1994** [kbengine/kbengine#1103]
[getstarted_assets.zip](https://github.com/kbengine/kbengine/files/2918895/getstarted_assets.zip)
这个是assert文件

**Comment by huangjiamin1994** [comment]
![0q39 t5 2 e8 nz 8fj 7rg](https://user-images.githubusercontent.com/44112989/53630559-42a78780-3c4b-11e9-8d91-763d8ec03927.png)
重现方法，第一次启动服务器后会生成一条数据
![yjxe _ gsj2 5jcu5 jge0](https://user-images.githubusercontent.com/44112989/53630591-5a7f0b80-3c4b-11e9-99b3-e0d265de348d.png)
关服后重启，就会报错了

**Comment by kebiao** [comment]
原因是其中的start_server.bat太旧了， 可以用引擎 new_assets.bat产生的assets中的bat覆盖。
主要是其中的
if defined uid (echo UID = %uid%) else set uid=%random%%%32760+1
要改为
if defined uid (echo UID = %uid%)
