### ISSUE TITLE
kbe src make 报错要怎么解决？

### ISSUE THREAD

**Issue by Vastxiao** [kbengine/kbengine#1107]
make[2]: 进入目录“/home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/sigar/linux”
cc -m64 -fPIC -DENABLE_WATCHERS -DNO_USE_LOG4CXX -DUSE_SIGAR -DUSE_JEMALLOC -DKBE_SERVER -MMD -DKBE_CONFIG=\"Hybrid64\" -DCODE_INLINE -DKBE_USE_ASSERTS -D_HYBRID -I /home/xiao/kbengine-2.4.3/kbe/src -I /home/xiao/kbengine-2.4.3/kbe/src/lib -I /home/xiao/kbengine-2.4.3/kbe/src/server -I /home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies -I /home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/zlib -I /home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/tinyxml -I /home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/fmt/include -I /home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/curl/include -I /home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/log4cxx/src/main/include -I/home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/openssl/include -I/home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/g3dlite -I/home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/sigar/linux -I/home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/jwsmtp/jwsmtp/jwsmtp -I/home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/tmxparser -I/home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/jemalloc/include  -c linux_sigar.c -o Hybrid64/linux_sigar.o
linux_sigar.c: In function ‘sigar_os_proc_list_get’:
linux_sigar.c:616:5: warning: ‘readdir_r’ is deprecated [-Wdeprecated-declarations]
     while (readdir_r(dirp, &dbuf, &ent) == 0) {
     ^~~~~
In file included from linux_sigar.c:18:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
linux_sigar.c: In function ‘get_iostat_proc_dstat’:
linux_sigar.c:1148:22: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
 #define ST_MAJOR(sb) major((sb).st_rdev)
                      ^~~~~
linux_sigar.c:1224:26: note: in expansion of macro ‘ST_MAJOR’
                          ST_MAJOR(sb), ST_MINOR(sb));
                          ^~~~~~~~
linux_sigar.c:1149:22: warning: implicit declaration of function ‘minor’; did you mean ‘mknod’? [-Wimplicit-function-declaration]
 #define ST_MINOR(sb) minor((sb).st_rdev)
                      ^~~~~
linux_sigar.c:1224:40: note: in expansion of macro ‘ST_MINOR’
                          ST_MAJOR(sb), ST_MINOR(sb));
                                        ^~~~~~~~
linux_sigar.c:1148:22: error: called object ‘major’ is not a function or function pointer
 #define ST_MAJOR(sb) major((sb).st_rdev)
                      ^~~~~
linux_sigar.c:1237:23: note: in expansion of macro ‘ST_MAJOR’
         if ((major == ST_MAJOR(sb)) &&
                       ^~~~~~~~
linux_sigar.c:1232:23: note: declared here
         unsigned long major, minor;
                       ^~~~~
linux_sigar.c:1149:22: error: called object ‘minor’ is not a function or function pointer
 #define ST_MINOR(sb) minor((sb).st_rdev)
                      ^~~~~
linux_sigar.c:1238:24: note: in expansion of macro ‘ST_MINOR’
             ((minor == ST_MINOR(sb)) || (minor == 0)))
                        ^~~~~~~~
linux_sigar.c:1232:30: note: declared here
         unsigned long major, minor;
                              ^~~~~
linux_sigar.c:1149:22: error: called object ‘minor’ is not a function or function pointer
 #define ST_MINOR(sb) minor((sb).st_rdev)
                      ^~~~~
linux_sigar.c:1289:26: note: in expansion of macro ‘ST_MINOR’
             if (minor == ST_MINOR(sb)) {
                          ^~~~~~~~
linux_sigar.c:1232:30: note: declared here
         unsigned long major, minor;
                              ^~~~~
linux_sigar.c: In function ‘get_iostat_procp’:
linux_sigar.c:1148:22: error: called object ‘major’ is not a function or function pointer
 #define ST_MAJOR(sb) major((sb).st_rdev)
                      ^~~~~
linux_sigar.c:1340:23: note: in expansion of macro ‘ST_MAJOR’
         if ((major == ST_MAJOR(sb)) && (minor == ST_MINOR(sb))) {
                       ^~~~~~~~
linux_sigar.c:1335:23: note: declared here
         unsigned long major, minor;
                       ^~~~~
linux_sigar.c:1149:22: error: called object ‘minor’ is not a function or function pointer
 #define ST_MINOR(sb) minor((sb).st_rdev)
                      ^~~~~
linux_sigar.c:1340:50: note: in expansion of macro ‘ST_MINOR’
         if ((major == ST_MAJOR(sb)) && (minor == ST_MINOR(sb))) {
                                                  ^~~~~~~~
linux_sigar.c:1335:30: note: declared here
         unsigned long major, minor;
                              ^~~~~
linux_sigar.c: In function ‘sigar_proc_port_get’:
linux_sigar.c:2260:5: warning: ‘readdir_r’ is deprecated [-Wdeprecated-declarations]
     while (readdir_r(dirp, &dbuf, &ent) == 0) {
     ^~~~~
In file included from linux_sigar.c:18:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
linux_sigar.c:2301:9: warning: ‘readdir_r’ is deprecated [-Wdeprecated-declarations]
         while (readdir_r(fd_dirp, &fd_dbuf, &fd_ent) == 0) {
         ^~~~~
In file included from linux_sigar.c:18:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
make[2]: *** [/home/xiao/kbengine-2.4.3/kbe/src/build/common.mak:512：Hybrid64/linux_sigar.o] 错误 1
make[2]: 离开目录“/home/xiao/kbengine-2.4.3/kbe/src/lib/dependencies/sigar/linux”
make[1]: *** [Makefile:31：all] 错误 2
make[1]: 离开目录“/home/xiao/kbengine-2.4.3/kbe/src/lib”
make: *** [Makefile:7：all] 错误 2

**Comment by kebiao** [comment]
clone一个版本就没问题了
