### ISSUE TITLE
cellapp和baseapp执行 KBEngine.reloadScript() 报异常

### ISSUE THREAD

**Issue by zhanglongfei** [kbengine/kbengine#1123]
cellapp02: [ERROR]: Components::removeComponentByChannel: cellapp : 8001, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

[ERROR]: Components::removeComponentByChannel: cellapp : 8001, Abnormal exit! TCPPacketReceiver::processRecv(): error=10054

**Comment by kebiao** [comment]
修正

**Comment by thao6626** [comment]
@kebiao 意思是现在可以热更新了？？
