### ISSUE TITLE
newPassword function doesn't change password

### ISSUE THREAD

**Issue by darkwere** [kbengine/kbengine#1169]
void KBEngineApp::newPassword (const FString& old_password, const FString& new_password)
{
	INFO_MSG ("KBEngineApp::newPassword(): send newPassword! username=%s", *username_);
	Bundle* pBundle = Bundle::createObject();
	pBundle->newMessage(Messages::messages[TEXT("Baseapp_reqAccountNewPassword"]));
	(*pBundle) << entity_id_;
	(*pBundle) << password_;
	(*pBundle) << old_password;
	(*pBundle) << new_password;
	pBundle->send(pNetworkInterface_);
}

remove (*pBundle) << password_; line in order the function work correctly!

**Comment by kbengine** [comment]
Fixed!
Thanks!
