### ISSUE TITLE
考虑cmake之类的编译配置来满足各种不同编译器的用户。

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#117]

**Comment by fightcto** [comment]
啥时候可以？

**Comment by 2nth0nyj** [comment]
是啊，快点换吧， 苹果机都编译不过了。

**Comment by finchcn** [comment]
为什么关闭Issue呢？不打算支持CMake了吗？跨平台编译，不用维护多套工程配置不是很好吗？

**Comment by kebiao** [comment]
@fightcto 很多大型第三方库不支持cmake， 用cmake还要自己安装和编译第三方库， 不如现在一键编译方便。  也没有什么需要维护的， 几年没改过了
