### ISSUE TITLE
实体必须要有Base部分吗？hasBase = false不起效

### ISSUE THREAD

**Issue by makilyang** [kbengine/kbengine#1186]
<Unit hasCell="true" hasClient="true", hasBase="false"></Unit>
类似这样定义的entity,
在Baseaapp执行KBEngine.reloadScript的时候，如果没有Base部分的实现，Baseapp进程就会崩溃了。

**Comment by kbengine** [comment]
monster不就没base吗

**Comment by kbengine** [comment]
hasBase = false 不要用这个选项。 只要base没有脚本就不会认为有base

**Comment by makilyang** [comment]
base 没脚本reloadScript就崩溃了，版本1.3.1

**Comment by kbengine** [comment]
你先测试一下demo试试， monster就没有脚本

**Comment by makilyang** [comment]
就是demo跑过了，一样的出错才问的。

**Comment by kebiao** [comment]
明天我试试。

**Comment by makilyang** [comment]
在Base里面补齐Gate,Monster,NPC三个实体的空白实现baseapp就不崩溃了，但是在cellapp执行reloadscript 会这里会出错，abstract.c line154 
 assert((item != NULL) ^ (PyErr_Occurred() != NULL));

**Comment by jay602** [comment]
测试最新版本1.3.4，没有出现这个问题
