### ISSUE TITLE
bots， clientappbase增加api， player（）方法获取当前玩家

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#1187]

**Comment by kbengine** [comment]
检查玩家只有base的情况下没有添加到entities的原因

**Comment by jay602** [comment]
![QQ截图20190422142406](https://user-images.githubusercontent.com/5274872/56486695-16054300-650b-11e9-8803-b8fcf36f1c71.png)

KBEngine.bots[3].player()
这里的player方法是新加的
