### ISSUE TITLE
kbengine sdk for C++ client

### ISSUE THREAD

**Issue by MiLoserDie** [kbengine/kbengine#1231]
Hello, have gensdk.bat for C++ client, where not used Engine? 
Example, if i'm want use kbengine for client where used C++ (not used UE4 or Unity and other)
Me need use kbengine sdk in my .dll for call them functions from game client

**Comment by kebiao** [comment]
Look at this, the example is somewhat outdated and may not be compiled successfully, but it is worthy of reference:
https://github.com/kbengine/kbengine_ogre_demo

**Comment by MiLoserDie** [comment]
> Look at this, the example is somewhat outdated and may not be compiled successfully, but it is worthy of reference:
> https://github.com/kbengine/kbengine_ogre_demo

why can't create a command for "kbcmd.exe", for example "--clientsdk = cpp", which would output C ++ code that can be used in C++?

**Comment by kbengine** [comment]
This demo is directly using src/lib/client_lib and cannot generate pure c++ client plugins via kbcmd.

**Comment by MiLoserDie** [comment]
> This demo is directly using src/lib/client_lib and cannot generate pure c++ client plugins via kbcmd.

Could you create examples on kbengine github where the example of a console application shows how to interact with kbengine using C ++ and a console application? Example, for use account auth for Account.def?

**Comment by kbengine** [comment]
An example is https://github.com/kbengine/kbengine_ogre_demo
