### ISSUE TITLE
那些端口应该打开

### ISSUE THREAD

**Issue by xiangxiangjiang** [kbengine/kbengine#1234]
您好，请问默认情况下那些端口应该开启？
当防火墙开启的时候会有以下错误：
loginapp-1: [ERROR]: Components::findComponents: receive error!
cellapp-1: [ERROR]: BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
关闭防火墙时可以正常启动项目
但是服务器防火墙不能总是关着，所以想问一下怎么设置防火墙。

**Comment by kbengine** [comment]
Linux防火墙设置
例子:

server1: 
		machine:
			内部TCP端口 : 20099		// 工具直接访问端口

		loginapp:
			外部TCP端口 : 20013		// 登录端口
			外部TCP端口 : 21103		// Email账号激活、密码重置等等处理的回调接口

		baseapp x N:
			外部TCP端口 : 20015, ...		// 网关端口(externalPorts_min->externalPorts_max)
			内部TCP端口 : 40000		// Telnet服务端口(用于调试等)

server2: 
		machine:
			内部TCP端口 : 20099		// 工具直接访问端口

		cellapp x N
			内部TCP端口 : 50000		// Telnet服务端口(用于调试等)


server3: 
		machine:
			内部TCP端口 : 20099		// 工具直接访问端口

		cellappmgr

		baseappmgr

		dbmgr

		interfaces
			内部TCP端口 : 30040		// 第三方回调接口，用于计费、第三方账号等等

UDP 广播端口: 
	internal : 20086-20088				// 探测和感知其他组件的存在, 组成为一个网络服务组
