### ISSUE TITLE
webconsole不能显示日志

### ISSUE THREAD

**Issue by 2018-10-18** [kbengine/kbengine#1238]
webconsole其他都正常，就是不能显示日志。
使用的是阿里云服务器。
阿里云自带Python2.7和3.6 用Python3启动的，不能显示日志。
Python升级到3.7，还是不行。

本地用deepin，python是3.5，运行正常，可以显示日志。

不能显示日志的情况在论坛上有多人提出。

**Comment by kebiao** [comment]
测试没遇到这个情况， 论坛是老版本出问题
