### ISSUE TITLE
数据库没有任何的报错，主动退出？？求大神出手

### ISSUE THREAD

**Issue by github583442736** [kbengine/kbengine#1263]
执行启动脚本后，启动不了，查看日志，显示dbmgr加入成功后，没有任何报错日志主动退出了，又没人遇到过类似情况？

**Comment by kebiao** [comment]
logs目录打包发上来

**Comment by github583442736** [comment]
好的

**Comment by github583442736** [comment]
你好，作者，日志在这里，有空帮我查看下，链接: https://pan.baidu.com/s/1bbrOFVKfrKsib1ckhsIr6w 提取码: i7dc

**Comment by kebiao** [comment]
好几个程序没有日志文件。 是不是少了什么 没看dbmgr日志。 防火墙关了试试

**Comment by github583442736** [comment]
完整的logs,链接: https://pan.baidu.com/s/1BQjWul4yMJxVdtINwV7R3w 提取码: nx7y

**Comment by kebiao** [comment]
没有dbmgr日志

**Comment by github583442736** [comment]
logger_dbmgr.2019-10-30.log是空，只有dbmgr.2019-10-30.log这个日志记录，没有任何报错就直接退出了dbmgr了

**Comment by kebiao** [comment]
把裁判的任务交给我， 不要给我看局部信息。 也许有其他发现

**Comment by github583442736** [comment]
大佬，我这边提供我测试服务器给你调试看看？

**Comment by kebiao** [comment]
只做简单回复

**Comment by github583442736** [comment]
大佬，我这边还能提供那些有用的信息给你？

**Comment by kebiao** [comment]
所有日志
