### ISSUE TITLE
2D游戏的witness中没有以Y轴作为View范围的问题

### ISSUE THREAD

**Issue by hzzgithub** [kbengine/kbengine#1265]
2D游戏的witness中没有以Y轴作为View范围，3d游戏中Y轴是高度，x，z轴是可见范围，witness设置了		<defaultViewRadius>是正常的，但是2d游戏是以XY轴作为witness可见范围，Z轴则是作为层次分布用的。不知道可不可以加一个配置，使得2d游戏可以使用XY轴作为witness可见范围，而不是XZ轴

**Comment by kebiao** [comment]
z当成y试试

**Comment by hzzgithub** [comment]
能不能修改源码解决？witness.cpp里的lastBasePos_.z改成lastBasePos_.y ？

**Comment by kebiao** [comment]
不能。
