### ISSUE TITLE
继承EntityComponent

### ISSUE THREAD

**Issue by hk520570** [kbengine/kbengine#1269]
请问下继承EntityComponent需要做哪些操作，想要继承EntityComponent来实现第三方AI库，但是好像有问题，之前看了说是官方会提供一个，但是好像并没有

**Comment by kebiao** [comment]
指的是c++还是脚本？

**Comment by hk520570** [comment]
C++总是崩溃，所以不清楚是不是我哪边操作失误了~ 	堆栈位置是显示这个位置，但是原始的是正常的cellapp.exe!KBEngine::EntityComponent::_tp_dealloc(_object * self) 行 82

**Comment by hk520570** [comment]
`AIComponent(ENTITY_ID ownerID, ScriptDefModule* pComponentDescrs, COMPONENT_TYPE assignmentToComponentType);
		~AIComponent();

		PyObject* onScriptGetAttribute(PyObject* attr);
		int onScriptSetAttribute(PyObject* attr, PyObject* value);
		int onScriptDelAttribute(PyObject* attr);
		//
	/*	void addToStream(MemoryStream* mstream, PyObject* pyValue);
		PyObject * createFromStream(MemoryStream* mstream);*/
		//
		void initializeScript();
		static void onInstallScript(PyObject* mod);
		/**
			获得描述
		*/
		INLINE ScriptDefModule* pComponentDescrs(void) const;
		/**
		获得对象的描述
		*/
		PyObject* tp_repr();
		PyObject* tp_str();
		void c_str(char* s, size_t size);
		void reload();
`
只实现了以上方法~不清楚是不是哪边我没考虑到

**Comment by kebiao** [comment]
这个不好判断问题在哪， _tp_dealloc挂了， 你看看是挂在哪里， 是不是指针不对， 有可能python相关的内容没填充， 注意看c++扩展py类使用的一些宏， 把entitycomponent多看看

**Comment by hk520570** [comment]
挂在这个位置了basedealloc(self);
我不是放在def里面的，我是放在cellapp中的，不清楚是不是base没初始化还是怎么回事~

**Comment by hk520570** [comment]
> 这个不好判断问题在哪， _tp_dealloc挂了， 你看看是挂在哪里， 是不是指针不对， 有可能python相关的内容没填充， 注意看c++扩展py类使用的一些宏， 把entitycomponent多看看

谢谢了，我看了一下，确实是python部分哪边初始化的时候有错，我先查找下~

**Comment by kebiao** [comment]
1：你看看entitycomponent类头文件的宏是不是允许继承， 可以对比其他c++的python类 比如proxy有继承。
2：似乎不能有虚函数， 继承就有了虚表， python是c的， 在析构时会有一个指针偏移计算， 可能那块出了问题。

**Comment by hk520570** [comment]
好的，我看了一下proxy的，因为可能不是很完整，不太好分辨，我先看下把宏重新撸一下，谢谢柯大

**Comment by hk520570** [comment]
我大体的已经找到问题了，好像是因为不能使用多重继承，多重继承的时候，BASE_SCRIPT_HREADER崩溃了，我现在区分开来吧，不用多重继承了~关贴了
