### ISSUE TITLE
Plugins compile errors in UnrealEngine 4.24

### ISSUE THREAD

**Issue by korialuo** [kbengine/kbengine#1273]
In UnrealEngine 4.24, there are some compile errors in process of compiling...
Which is, the latest version of UE4 sets the following values by default, which may require code changes:
1.  bLegacyPublicIncludePaths = false  => Omits subfolders from public include paths to reduce compiler command line length. (Previously: true).
2. ShadowVariableWarningLevel = WarningLevel.Error   => Treats shadowed variable warnings as errors. (Previously: WarningLevel.Warning).
3. PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs   => Set in build.cs files to enables IWYU-style PCH model. (Previously: PCHUsageMode.UseSharedPCHs).

So, in ikcp.c, there were so manay WARNINGs (CODE：C4465), and another problem is, so many header files in UE4 module can't be found. Then we need to modify the source of 'kbcmd' project, add the following codes into KBEnginePlugins.Build.cs :

ShadowVariableWarningLevel = WarningLevel.Warning;
bLegacyPublicIncludePaths = true;

It works. : )

**Comment by kebiao** [comment]
vs2017， ue4 4.25.1， windows7
`1>------ Skipped Build: Project: DatasmithRevit2019, Configuration: Development_Program x64 ------
1>Project not selected to build for this solution configuration 
2>------ Skipped Build: Project: DatasmithRevit2020, Configuration: Development_Program x64 ------
2>Project not selected to build for this solution configuration 
3>------ Build started: Project: DatasmithSDK, Configuration: Development_Program x64 ------
4>------ Skipped Build: Project: DatasmithSketchUp2017, Configuration: Development_Program x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Build: Project: DatasmithSketchUp2018, Configuration: Development_Program x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Build: Project: DatasmithSketchUp2019, Configuration: Development_Program x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Build: Project: DatasmithSketchUp2020, Configuration: Development_Program x64 ------
7>Project not selected to build for this solution configuration 
8>------ Build started: Project: HeadlessChaos, Configuration: Development_Program x64 ------
9>------ Skipped Build: Project: UnrealLaunchDaemon, Configuration: Invalid Win32 ------
9>Project not selected to build for this solution configuration 
10>------ Build started: Project: LiveCodingConsole, Configuration: Development_Program x64 ------
11>------ Skipped Build: Project: DsymExporter, Configuration: Invalid Win32 ------
11>Project not selected to build for this solution configuration 
12>------ Skipped Build: Project: UnrealAtoS, Configuration: Invalid Win32 ------
12>Project not selected to build for this solution configuration 
13>------ Build started: Project: ShaderCompileWorker, Configuration: Development_Program x64 ------
14>------ Build started: Project: SlateViewer, Configuration: Development_Program x64 ------
15>------ Build started: Project: TestPAL, Configuration: Development_Program x64 ------
16>------ Build started: Project: UnrealCEFSubProcess, Configuration: Development_Program x64 ------
17>------ Build started: Project: UnrealFileServer, Configuration: Development_Program x64 ------
8>Target is up to date
8>Total execution time: 0.91 seconds
18>------ Build started: Project: UnrealFrontend, Configuration: Development_Program x64 ------
3>Target is up to date
3>Total execution time: 1.43 seconds
19>------ Build started: Project: UnrealHeaderTool, Configuration: Development_Program x64 ------
10>Target is up to date
10>Total execution time: 1.53 seconds
20>------ Build started: Project: UnrealInsights, Configuration: Development_Program x64 ------
13>Target is up to date
13>Total execution time: 1.66 seconds
21>------ Skipped Build: Project: UE4EditorServices, Configuration: Invalid Win32 ------
21>Project not selected to build for this solution configuration 
22>------ Build started: Project: UnrealMultiUserServer, Configuration: Development_Program x64 ------
14>Target is up to date
14>Total execution time: 2.63 seconds
23>------ Build started: Project: UnrealPak, Configuration: Development_Program x64 ------
15>Target is up to date
15>Total execution time: 2.49 seconds
24>------ Build started: Project: UnrealRecoverySvc, Configuration: Development_Program x64 ------
18>Target is up to date
18>Total execution time: 2.92 seconds
25>------ Build started: Project: UnrealVersionSelector, Configuration: Development_Program x64 ------
16>Target is up to date
16>Total execution time: 3.23 seconds
26>------ Build started: Project: UnrealWatchdog, Configuration: Development_Program x64 ------
19>Target is up to date
19>Total execution time: 3.33 seconds
27>------ Build started: Project: BootstrapPackagedGame, Configuration: Development_Program x64 ------
20>Target is up to date
20>Total execution time: 3.43 seconds
28>------ Build started: Project: UE4, Configuration: Development_Editor x64 ------
17>Target is up to date
17>Total execution time: 3.72 seconds
29>------ Build started: Project: UnrealLightmass, Configuration: Development_Program x64 ------
22>Target is up to date
22>Total execution time: 4.29 seconds
30>------ Build started: Project: kbengine_ue4_demo, Configuration: Development_Editor x64 ------
23>Target is up to date
23>Total execution time: 4.01 seconds
31>------ Build started: Project: BenchmarkTool, Configuration: Development_Program x64 ------
24>Target is up to date
24>Total execution time: 4.31 seconds
32>------ Build started: Project: BlankProgram, Configuration: Development_Program x64 ------
25>Target is up to date
25>Total execution time: 4.09 seconds
33>------ Build started: Project: BuildPatchTool, Configuration: Development_Program x64 ------
26>Target is up to date
26>Total execution time: 4.14 seconds
34>------ Build started: Project: CrashReportClient, Configuration: Development_Program x64 ------
27>Target is up to date
27>Total execution time: 4.09 seconds
35>------ Build started: Project: CrashReportClientEditor, Configuration: Development_Program x64 ------
29>Target is up to date
29>Total execution time: 3.75 seconds
36>------ Build started: Project: DatasmithCADWorker, Configuration: Development_Program x64 ------
30>Using 'git status' to determine working set for adaptive non-unity build (D:\kbe\kbengine_ue4_demo).
30>Targets are up to date
30>Total execution time: 5.40 seconds
37>------ Skipped Build: Project: DatasmithFacadeCSharp, Configuration: Development_Program x64 ------
37>Project not selected to build for this solution configuration 
38>------ Skipped Build: Project: DatasmithMax2016, Configuration: Development_Program x64 ------
38>Project not selected to build for this solution configuration 
39>------ Skipped Build: Project: DatasmithMax2017, Configuration: Development_Program x64 ------
39>Project not selected to build for this solution configuration 
40>------ Skipped Build: Project: DatasmithMax2018, Configuration: Development_Program x64 ------
40>Project not selected to build for this solution configuration 
41>------ Skipped Build: Project: DatasmithMax2019, Configuration: Development_Program x64 ------
41>Project not selected to build for this solution configuration 
42>------ Skipped Build: Project: DatasmithMax2020, Configuration: Development_Program x64 ------
42>Project not selected to build for this solution configuration 
43>------ Skipped Build: Project: DatasmithMax2021, Configuration: Development_Program x64 ------
43>Project not selected to build for this solution configuration 
44>------ Skipped Build: Project: DatasmithRevit2018, Configuration: Development_Program x64 ------
44>Project not selected to build for this solution configuration 
31>Target is up to date
31>Total execution time: 5.30 seconds
28>Targets are up to date
28>Total execution time: 6.79 seconds
32>Target is up to date
32>Total execution time: 6.98 seconds
33>Target is up to date
33>Total execution time: 7.10 seconds
34>Target is up to date
34>Total execution time: 7.05 seconds
35>Target is up to date
35>Total execution time: 7.23 seconds
36>Target is up to date
36>Total execution time: 7.19 seconds
========== Build: 26 succeeded, 0 failed, 31 up-to-date, 18 skipped ==========
`
![image](https://user-images.githubusercontent.com/2352650/87239794-aa780000-c445-11ea-9bda-640b6517cc3f.png)
![image](https://user-images.githubusercontent.com/2352650/87239796-b368d180-c445-11ea-98f8-0c861289398f.png)

**Comment by develn** [comment]
已经解决，参考UE4 demo 的代码，修改空白的UE4 工程， 最终编译通过， 主要进行的修改是 删除了一行代码，但是我还不知道是什么原因
Source/KBELearnPro.Target.cs
Source/KBELearnProEditor.Target.cs
这两个文件里面，都删除了

DefaultBuildSettings = BuildSettingsVersion.V2;
这一行代码， 最终编译通过

**Comment by yxjlzr** [comment]
deepin上编译的ue4.25.1打不开demo里带的工程，好像和插件有关系，编译不了插件

**Comment by yxjlzr** [comment]
> 已经解决，参考UE4 demo 的代码，修改空白的UE4 工程， 最终编译通过， 主要进行的修改是 删除了一行代码，但是我还不知道是什么原因
> Source/KBELearnPro.Target.cs
> Source/KBELearnProEditor.Target.cs
> 这两个文件里面，都删除了
> 
> DefaultBuildSettings = BuildSettingsVersion.V2;
> 这一行代码， 最终编译通过

找不到这两个文件在哪？
