### ISSUE TITLE
热更base挂了，windows上没问题，linux上热更多热更几次就挂了

### ISSUE THREAD

**Issue by quexiaobin** [kbengine/kbengine#1274]
Components::removeComponentByChannel: baseapp : 103000003065, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708809709682, lastReceivedTime=1480645018459926, inactivityExceptionPeriod=149524110824)
   cellapp01: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003065, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708818218806, lastReceivedTime=1480645018297888, inactivityExceptionPeriod=149524258160)
baseappmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003065, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708832531410, lastReceivedTime=1480708527302670, inactivityExceptionPeriod=149524323648)
baseappmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003066, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708832857544, lastReceivedTime=1480708631928566, inactivityExceptionPeriod=149524323648)
     dbmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003065, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708833321398, lastReceivedTime=1480708771895122, inactivityExceptionPeriod=149524159936)
     dbmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003066, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708833599768, lastReceivedTime=1480684437762718, inactivityExceptionPeriod=149524159936)
   cellapp01: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003066, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708833778528, lastReceivedTime=1480645027085130, inactivityExceptionPeriod=149524258160)
baseappmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003063, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708856798078, lastReceivedTime=1480708531874548, inactivityExceptionPeriod=149524323648)
baseappmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003064, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708857014950, lastReceivedTime=1480708645770680, inactivityExceptionPeriod=149524323648)
cellappmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003066, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708834332326, lastReceivedTime=1480645027178754, inactivityExceptionPeriod=149524110824)
     dbmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003063, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708857329630, lastReceivedTime=1480684433723740, inactivityExceptionPeriod=149524159936)
     dbmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003064, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708857519118, lastReceivedTime=1480684412327632, inactivityExceptionPeriod=149524159936)
cellappmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003063, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708857488644, lastReceivedTime=1480645027170028, inactivityExceptionPeriod=149524110824)
cellappmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003064, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708857631308, lastReceivedTime=1480645027185382, inactivityExceptionPeriod=149524110824)
   cellapp01: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003063, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708857839372, lastReceivedTime=1480645027076184, inactivityExceptionPeriod=149524258160)
   cellapp01: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003064, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708858000292, lastReceivedTime=1480645027092276, inactivityExceptionPeriod=149524258160)
baseappmgr-1: [ERROR]: Components::removeComponentByChannel: baseapp : 103000003062, Abnormal exit(reason=disconnected)! Channel(timestamp=1480708879546342, lastReceivedTime=1480708538875700, inactivityExceptionPeriod=149524323648)

**Comment by kebiao** [comment]
python热更要注意的东西较多， 你网上查一下。 自己调试一下

**Comment by quexiaobin** [comment]
我只是把服务器启动了，都没有人玩家进去，多执行几次KBEngine.reloadScript(),base就挂了，关键是又没有啥日志可以查看
