### ISSUE TITLE
Cannot start dbmgr

### ISSUE THREAD

**Issue by wycfutures** [kbengine/kbengine#1275]
dbmgr-1: [ERROR]: KBEServerLogTableMysql::isShareDB: The database interface(default) is not shared, uid=45505! Check 'kbe_serverlog' table and 'kbengine[_defs].xml->dbmgr->shareDB'.
     dbmgr-1: [ERROR]: KBEServerLogTableMysql::isShareDB: The database interface(default) is not shared, uid=45505! Check 'kbe_serverlog' table and 'kbengine[_defs].xml->dbmgr->shareDB'.
     dbmgr-1: [ERROR]: app::initialize(): initialization failed!

Could you please tell me how to solve this problem? This problem still exists even if I changed the shareDB from false to true in kbengine_defaults.xml

**Comment by wycfutures** [comment]
Here is the log

INFO root [2020-04-18 15:22:58,202] - 
  INFO root [2020-04-18 15:22:58,202] - -----------------------------------------------------------------------------------------


  INFO root [2020-04-18 15:22:58,202] - Resmgr::initialize: KBE_ROOT=/root/kbengine/
  INFO root [2020-04-18 15:22:58,202] - Resmgr::initialize: KBE_RES_PATH=/root/kbengine/kbe/res/:/root/kbengine/kbengine_demos_assets/:/root/kbengine/kbengine_demos_assets/res/:/root/kbengine/kbengine_demos_assets/scripts/
  INFO root [2020-04-18 15:22:58,202] - Resmgr::initialize: KBE_BIN_PATH=/root/kbengine/kbe/bin/server/
  INFO root [2020-04-18 15:22:58,202] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 172.17.0.2 ( 172.17.0.2:50915 )
  WARN root [2020-04-18 15:22:58,202] - NetworkInterface::initialize(INTERNAL-TCP): Operating with a receive buffer of only 425984 bytes (instead of 16777216)
  WARN root [2020-04-18 15:22:58,203] - NetworkInterface::initialize(INTERNAL-TCP): Operating with a send buffer of only 425984 bytes (instead of 16777216)
  INFO root [2020-04-18 15:22:58,203] - NetworkInterface::initialize(INTERNAL-TCP): address 172.17.0.2:50915, SOMAXCONN=511.
  INFO root [2020-04-18 15:22:58,203] - server-configs:
  INFO root [2020-04-18 15:22:58,203] - 	internalTcpAddr : 172.17.0.2:50915
  INFO root [2020-04-18 15:22:58,203] - 	componentID : 3129652375332859700
  WARN root [2020-04-18 15:22:58,203] - invalid UID(0) <= 0, please check UID for environment! automatically set to 1179.
  INFO root [2020-04-18 15:22:59,707] - ---- dbmgr Version: 2.5.8. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: 11178A1C367680938C8E416B64844ACD. Config: Hybrid64 X64. Built: 14:05:22 Apr 18 2020. AppID: 3129652375332859700. UID: 1179. PID: 764 ----
  INFO root [2020-04-18 15:22:59,707] - Server 39b6ee5c5ac7: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz x8 with 16279864kB RAM
  INFO root [2020-04-18 15:22:59,707] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2020-04-18 15:22:59,707] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2020-04-18 15:22:59,808] - Script::install(): paths=/root/kbengine/kbengine_demos_assets/scripts/common:/root/kbengine/kbengine_demos_assets/scripts/data:/root/kbengine/kbengine_demos_assets/scripts/user_type:/root/kbengine/kbengine_demos_assets/scripts/server_common:/root/kbengine/kbengine_demos_assets/scripts/db:/root/kbengine/kbe/res/scripts:/root/kbengine/kbe/res/scripts/common:/root/kbengine/kbe/res/scripts/common/lib-dynload:/root/kbengine/kbe/res/scripts/common/DLLs:/root/kbengine/kbe/res/scripts/common/Lib:/root/kbengine/kbe/res/scripts/common/Lib/site-packages:/root/kbengine/kbe/res/scripts/common/Lib/dist-packages.
  INFO root [2020-04-18 15:22:59,844] - Script::install(): is successfully, Python=(3.7.3 (default, Apr 18 2020, 13:48:42) 
[GCC 5.4.0 20160609])!
  INFO root [2020-04-18 15:22:59,844] - Script::install(): KBExtra is successfully!
  INFO root [2020-04-18 15:22:59,915] - Dbmgr::initializeEnd: digest(46596D3750651E9F679C7775CD577E35)
S_INFO root [2020-04-18 15:22:59,915] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2020-04-18 15:22:59,915] - TelnetServer server is running on port 32000
  INFO root [2020-04-18 15:22:59,915] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2020-04-18 15:22:59,915] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
9D9D013965C34A43600EF816C4F47BD6D041BEA50EA12DFEADE55E68A23CDF6B5D3960A08811158B974F59CCDA195620C31C6D158106399DE01127D93C6108AAEF49E4778F15E139F2CD9405DFEDE0953F37A1421287C3EC80DEA3FA3C5B1ADDBFAE65C4026209633A532CCF8173CCBAE33DDDEE8439030FB5C4016FC71B0115
 DEBUG root [2020-04-18 15:22:59,916] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2020-04-18 15:22:59,917] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2020-04-18 15:22:59,917] - DBUtil::createInterface[0x7ffee0281948]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2020-04-18 15:22:59,917] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2020-04-18 15:22:59,917] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2020-04-18 15:22:59,917] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2020-04-18 15:22:59,917] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2020-04-18 15:22:59,918] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2020-04-18 15:22:59,918] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2020-04-18 15:22:59,918] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2020-04-18 15:22:59,919] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2020-04-18 15:22:59,919] - DBThread::onStart(): 0x7fa0b4b1b600!
 DEBUG root [2020-04-18 15:22:59,919] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2020-04-18 15:22:59,919] - DBThread::onStart(): 0x7fa0b4b1bc00!
 DEBUG root [2020-04-18 15:22:59,919] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2020-04-18 15:22:59,919] - DBThread::onStart(): 0x7fa0b4b1ba80!
 DEBUG root [2020-04-18 15:22:59,919] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2020-04-18 15:22:59,919] - DBThread::onStart(): 0x7fa0b4b1bcc0!
 DEBUG root [2020-04-18 15:22:59,919] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2020-04-18 15:22:59,919] - DBThread::onStart(): 0x7fa0b4b1bb40!
  INFO root [2020-04-18 15:23:00,018] - DBInterfaceMysql::query: successfully!
  INFO root [2020-04-18 15:23:00,019] - DBInterfaceMysql::query: successfully!
  INFO root [2020-04-18 15:23:00,019] - DBInterfaceMysql::query: successfully!
  INFO root [2020-04-18 15:23:00,019] - DBInterfaceMysql::query: successfully!
 DEBUG root [2020-04-18 15:23:00,019] - syncToDB(): Space->sm_name(varchar(255) not null DEFAULT '').
  INFO root [2020-04-18 15:23:00,019] - DBInterfaceMysql::query: successfully!
 ERROR root [2020-04-18 15:23:00,019] - KBEServerLogTableMysql::isShareDB: The database interface(default) is not shared, uid=45505! Check 'kbe_serverlog' table and 'kbengine[_defs].xml->dbmgr->shareDB'.
  INFO root [2020-04-18 15:23:00,020] - DBInterfaceMysql::query: successfully!
 ERROR root [2020-04-18 15:23:00,020] - KBEServerLogTableMysql::isShareDB: The database interface(default) is not shared, uid=45505! Check 'kbe_serverlog' table and 'kbengine[_defs].xml->dbmgr->shareDB'.
  INFO root [2020-04-18 15:23:00,020] - DBInterfaceMysql::query: successfully!
 DEBUG root [2020-04-18 15:23:00,021] - syncToDB(): SpaceDuplicate->sm_name(varchar(255) not null DEFAULT '').
 DEBUG root [2020-04-18 15:23:00,022] - syncToDB(): Avatar->sm_name(varchar(255) not null DEFAULT '').
 DEBUG root [2020-04-18 15:23:00,022] - syncToDB(): NPC->sm_name(varchar(255) not null DEFAULT '').
 DEBUG root [2020-04-18 15:23:00,023] - syncToDB(): Gate->sm_name(varchar(255) not null DEFAULT '').
 DEBUG root [2020-04-18 15:23:00,028] - syncToDB(): Monster->sm_name(varchar(255) not null DEFAULT '').
 DEBUG root [2020-04-18 15:23:00,028] - syncToDB(): Spaces->sm_name(varchar(255) not null DEFAULT '').
 DEBUG root [2020-04-18 15:23:00,028] - syncToDB(): SpawnPoint->sm_name(varchar(255) not null DEFAULT '').
 DEBUG root [2020-04-18 15:23:00,028] - syncToDB(): Account_characters_values->sm_name(varchar(256) not null DEFAULT '').
  WARN root [2020-04-18 15:23:00,039] - dbmgr.cpp:306: Profile scriptCall took 0.12 seconds
 ERROR root [2020-04-18 15:23:00,039] - app::initialize(): initialization failed!
 DEBUG root [2020-04-18 15:23:00,039] - ThreadPool::destroy(): starting size 5.
  WARN root [2020-04-18 15:23:00,339] - ThreadPool::destroy(): waiting for thread(5)[0x7fa0b4b1b600,0x7fa0b4b1ba80,0x7fa0b4b1bb40,0x7fa0b4b1bc00,0x7fa0b4b1bcc0,], try=1
 DEBUG root [2020-04-18 15:23:00,340] - DBThread::onEnd(): 0x7fa0b4b1bc00!
 DEBUG root [2020-04-18 15:23:00,340] - DBThread::onEnd(): 0x7fa0b4b1bb40!
 DEBUG root [2020-04-18 15:23:00,340] - DBThread::onEnd(): 0x7fa0b4b1b600!
 DEBUG root [2020-04-18 15:23:00,340] - DBThread::onEnd(): 0x7fa0b4b1ba80!
 DEBUG root [2020-04-18 15:23:00,340] - DBThread::onEnd(): 0x7fa0b4b1bcc0!
 DEBUG root [2020-04-18 15:23:00,740] - TPThread::~TPThread(): 0x7fa0b4b1b600
 DEBUG root [2020-04-18 15:23:00,740] - TPThread::~TPThread(): 0x7fa0b4b1ba80
 DEBUG root [2020-04-18 15:23:00,740] - TPThread::~TPThread(): 0x7fa0b4b1bb40
 DEBUG root [2020-04-18 15:23:00,740] - TPThread::~TPThread(): 0x7fa0b4b1bc00
 DEBUG root [2020-04-18 15:23:00,740] - TPThread::~TPThread(): 0x7fa0b4b1bcc0
  WARN root [2020-04-18 15:23:00,741] - ThreadPool::~ThreadPool(): Discarding 4 finished tasks.
 DEBUG root [2020-04-18 15:23:00,741] - ThreadPool::destroy(): successfully!
  INFO root [2020-04-18 15:23:00,753] - Script::uninstall(): is successfully!
 DEBUG root [2020-04-18 15:23:00,754] - ThreadPool::destroy(): starting size 2.
  WARN root [2020-04-18 15:23:01,054] - ThreadPool::destroy(): waiting for thread(2)[0x7fa0b4a61980,0x7fa0b4a240e0,], try=1
 DEBUG root [2020-04-18 15:23:01,455] - TPThread::~TPThread(): 0x7fa0b4a61980
 DEBUG root [2020-04-18 15:23:01,455] - TPThread::~TPThread(): 0x7fa0b4a240e0
 DEBUG root [2020-04-18 15:23:01,455] - ThreadPool::destroy(): successfully!
 DEBUG root [2020-04-18 15:23:01,456] - Bundle::destroyObjPool(): size 1.
 DEBUG root [2020-04-18 15:23:01,456] - Channel::destroyObjPool(): size 15.
 DEBUG root [2020-04-18 15:23:01,456] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2020-04-18 15:23:01,456] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2020-04-18 15:23:01,456] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2020-04-18 15:23:01,456] - Address::destroyObjPool(): size 0.
 DEBUG root [2020-04-18 15:23:01,456] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2020-04-18 15:23:01,456] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2020-04-18 15:23:02,758] - EventDispatcher()::~EventDispatcher: Num timers = 1

**Comment by wycfutures** [comment]
I solved it by using the following command to restart the mysql database.
service mysql restart

**Comment by wycfutures** [comment]
This problem happened again. This time I cannot resolve it by restart the mysql service. Is there any way to solve this issue?

**Comment by a7210232** [comment]
the same question    mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64)

**Comment by kebiao** [comment]
Try deleting the database.
Check if your CID is fixed.

**Comment by yajunjiao** [comment]
I have  the same question too.

**Comment by ve-i-uj** [comment]
I also encountered this problem when running kbengine under a debugger in VSCode (on Ubuntu 20.04). Sometimes you need to wait 5-20 seconds after starting Machine, Logger and Interfaces and only then start DBMgr, otherwise there will be this error. But when running through start_server.sh on CentOs7 this error never happend.
