### ISSUE TITLE
关于参数bitsPerSecondToClient设置  请大佬解答一下

### ISSUE THREAD

**Issue by simpletuo** [kbengine/kbengine#1276]
用的kbe版本是1.3.x   配置文件有 **bitsPerSecondToClient** 这个参数 即每秒发送到客户端的带宽限制(bit)  ，默认值是20000，也就是2.44KB.
  这参数是针对单客服端的限制吗？ 还是针对所有客户端总共的宽带限制？如果是后者，5M的宽带如何设置比较好？如果有两台服务器都启动了kbe服务，那么这个参数是针对单台服务器的宽带显示还是针对所有服务器的宽带限制？

**Comment by kebiao** [comment]
单个客户端
