### ISSUE TITLE
机器人报错

### ISSUE THREAD

**Issue by quexiaobin** [kbengine/kbengine#1280]
0-04-24 12:18:48,695] - flag:0
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,696] - Attempted to get in MemoryStream (pos:1621, size:0, opsize:4)!
  WARN root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,696] - Channel::processPackets(129.204.242.253:20218/0/0/0): packet invalid. currMsg=(Client::onCreatedProxies, id=504, len=-1), currMsgLen=19
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,696] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbcd12800] is condemn.
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,696] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbcd12800] is condemn.
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,696] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbcd12800] is condemn.
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,696] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbcd12800] is condemn.
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,696] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbcd12800] is condemn.
 DEBUG root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,711] - ClientObjectBase::onEntityDestroyed: Account(10493).
 DEBUG root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,711] - Account::~Account(): 10493
  INFO root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,711] - ClientObject::onCreatedProxies(bot_0_1258_31_0): rndUUID=6819127856558178312 eid=10497 entityType=Player!
  INFO root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,711] - ClientObjectBase::createEntity: new Player (10497)
 S_ERR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,712] - flag:0
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,713] - Attempted to get in MemoryStream (pos:1621, size:0, opsize:4)!
  WARN root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,713] - Channel::processPackets(129.204.242.253:20218/0/0/0): packet invalid. currMsg=(Client::onCreatedProxies, id=504, len=-1), currMsgLen=19
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,713] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbd3ec000] is condemn.
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,713] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbd3ec000] is condemn.
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,713] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbd3ec000] is condemn.
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,713] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbd3ec000] is condemn.
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,713] - Channel::processPackets(129.204.242.253:20218/0/16/0): channel[0x7f4fbd3ec000] is condemn.
 DEBUG root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,729] - ClientObjectBase::onEntityDestroyed: Account(10491).
 DEBUG root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,729] - Account::~Account(): 10491
  INFO root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,729] - ClientObject::onCreatedProxies(bot_0_1256_32_0): rndUUID=6819127856558178313 eid=10498 entityType=Player!
  INFO root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,730] - ClientObjectBase::createEntity: new Player (10498)
 S_ERR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,730] - flag:0
 ERROR root [0x7f4fca8bdfc0] [2020-04-24 12:18:48,731] - Attempted to get in MemoryStream (pos:1621, size:0, opsize:4)!

**Comment by kebiao** [comment]
测试方案？

**Comment by quexiaobin** [comment]
有啥测试方案么？

**Comment by kebiao** [comment]
要说清楚你怎么测试的， 什么规模 什么系统等等？

**Comment by quexiaobin** [comment]
两台外网机，linux系统，机器人100个都回报这个错

**Comment by kebiao** [comment]
bot通过外网连接？ 内网试试

**Comment by quexiaobin** [comment]
对的，通过外网连接，内网启动200个机器人没问题

**Comment by kebiao** [comment]
那可能是带宽不够？ 或者哪里限制导致了？

**Comment by quexiaobin** [comment]
应该是运营那边给的机器有啥限制，用自己的外网机测试没问题
