### ISSUE TITLE
sys.modules漏了部分模块

### ISSUE THREAD

**Issue by lanfengnan** [kbengine/kbengine#1281]
做热更新的时候，部分模块有进行import，但是没有放入到sys.modules中。
通过测试，发现在interface目录下import同目录下的模块，就没有放入到sys.modules中。如果是base中的模块import了interface中的模块，就会加入到sys.modules中。

**Comment by kebiao** [comment]
这个你可以查查看。  试试1.x有没有这个问题

**Comment by lanfengnan** [comment]
当前手头上没有1.X版本的，不过2.x只要启动服务器就是这样
