### ISSUE TITLE
streamFileToClient  当客户端断开 服务器仍然发送 不停报红

### ISSUE THREAD

**Issue by qinlinger1** [kbengine/kbengine#1282]
当客户端断开 服务器能否主动停止发送

**Comment by kebiao** [comment]
`bool DataDownload::send(const Network::MessageHandler& msgHandler, Network::Bundle* pBundle)
{
	Proxy* proxy = static_cast<Proxy*>(Baseapp::getSingleton().findEntity(entityID_));
	
	if(proxy && proxy->clientEntityCall())
	{
		proxy->sendToClient(msgHandler, pBundle);
	}
	else
	{
		Network::Bundle::reclaimPoolObject(pBundle);
		return false;
	}

	return true;
}`  这样试试

**Comment by qinlinger1** [comment]
谢谢柯大  完美解决 好用
