### ISSUE TITLE
关于filter的替换的问题

### ISSUE THREAD

**Issue by maaomaao** [kbengine/kbengine#1287]
baseapp和loginapp的onHello方法中,如果使用了加密,则直接用blowfishfilter覆盖之前的filter,那么如果用的是ws协议,之后在哪解析ws包呢?

**Comment by maaomaao** [comment]
是因为ws已经有掩码了不需要额外加密了么？

**Comment by kebiao** [comment]
可以用wss， wss就是https加密的
