### ISSUE TITLE
UE4 DEMO 在MacOS下4.24 编译报错。windows下正常。

### ISSUE THREAD

**Issue by chelyzhou** [kbengine/kbengine#1288]
无法编译该项目。要在Xcode中打开它吗？

Running Mono...

Running bundled mono, version: Mono JIT compiler version 5.16.0.220 (2018-06/bb3ae37d71a Fri Nov 16 17:12:11 EST 2018)
/Users/Shared/Epic Games/UE_4.24/Engine /Users/Shared/Epic Games/UE_4.24/Engine/Binaries/Mac
WARNING: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/KBEnginePlugins.uplugin: warning: The 'Developer' module type has been deprecated in 4.24.
Creating makefile for kbengine_ue4_demoEditor (no existing makefile)
@progress push 5%
Parsing headers for kbengine_ue4_demoEditor
  Running UnrealHeaderTool "/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/kbengine_ue4_demo.uproject" "/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Intermediate/Build/Mac/kbengine_ue4_demoEditor/Development/kbengine_ue4_demoEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for kbengine_ue4_demoEditor in 6.4865878 seconds
@progress pop
Building kbengine_ue4_demoEditor...
[Upgrade]
[Upgrade] Using backward-compatible build settings. The latest version of UE4 sets the following values by default, which may require code changes:
[Upgrade]     bLegacyPublicIncludePaths = false                 => Omits subfolders from public include paths to reduce compiler command line length. (Previously: true).
[Upgrade]     ShadowVariableWarningLevel = WarningLevel.Error   => Treats shadowed variable warnings as errors. (Previously: WarningLevel.Warning).
[Upgrade]     PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs   => Set in build.cs files to enables IWYU-style PCH model. See https://docs.unrealengine.com/en-US/Programming/BuildTools/UnrealBuildTool/IWYU/index.html. (Previously: PCHUsageMode.UseSharedPCHs).
[Upgrade] Suppress this message by setting 'DefaultBuildSettings = BuildSettingsVersion.V2;' in kbengine_ue4_demoEditor.Target.cs, and explicitly overriding settings that differ from the new defaults.
[Upgrade]
Performing 22 actions (12 in parallel)
[1/22] Compile SharedPCH.Engine.h
[2/22] Compile SharedPCH.UnrealEd.NoUndef.h
[3/22] Compile ikcp.c
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/ikcp.c:436:12: warning: declaration shadows a local variable [-Wshadow]
                IKCPSEG *seg = iqueue_entry(kcp->rcv_buf.next, IKCPSEG, node);
                         ^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/ikcp.c:385:11: note: previous declaration is here
        IKCPSEG *seg;
                 ^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/ikcp.c:778:24: warning: declaration shadows a local variable [-Wshadow]
                IUINT32 ts, sn, len, una, conv;
                                     ^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/ikcp.c:767:10: note: previous declaration is here
        IUINT32 una = kcp->snd_una;
                ^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/ikcp.c:1082:8: warning: declaration shadows a local variable [-Wshadow]
                        int size, need;
                            ^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/ikcp.c:939:13: note: previous declaration is here
        int count, size, i;
                   ^
3 warnings generated.
[4/22] Compile Module.KBEnginePlugins.cpp
[5/22] Compile Module.KBEnginePlugins.gen.cpp
[6/22] Compile kbengine_ue4_demo.cpp
[7/22] Compile GameEntity.cpp
[8/22] Compile GameModeDemoBase.cpp
[9/22] Compile GameModeLogin.cpp
[10/22] Compile GameModeSelectAvatar.cpp
[11/22] Compile PlayerCharacter.cpp
[12/22] Compile GameModeWorld.cpp
[13/22] Compile GameModeLogin.gen.cpp
[14/22] Compile GameModeDemoBase.gen.cpp
[15/22] Compile GameModeSelectAvatar.gen.cpp
In file included from /Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Intermediate/Build/Mac/UE4Editor/Development/KBEnginePlugins/Module.KBEnginePlugins.cpp:2:
In file included from /Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/AccountBase.cpp:1:
In file included from /Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/AccountBase.h:11:
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/KBETypes.h:116:1: error: all paths through this function will call itself [-Werror,-Winfinite-recursion]
{
^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/KBETypes.h:131:1: error: all paths through this function will call itself [-Werror,-Winfinite-recursion]
{
^
In file included from /Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Source/kbengine_ue4_demo/PlayerCharacter.cpp:5:
/Users/Shared/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Classes/Kismet/HeadMountedDisplayFunctionLibrary.h:7:1: warning: This file has been moved to HeadMountedDisplay/Public/HeadMountedDisplayFunctionLibrary.h. Some types were moved to HeadMountedDisplay/Public/HeadMountedDisplayTypes.h.  Replace all #include "Kismet\HeadMountedDisplayFunctionLibrary.h" with: #include "HeadMountedDisplayFunctionLibrary.h" or #include "HeadMountedDisplayTypes.h". [-W#pragma-messages]
COMPILE_WARNING("This file has been moved to HeadMountedDisplay/Public/HeadMountedDisplayFunctionLibrary.h. Some types were moved to HeadMountedDisplay/Public/HeadMountedDisplayTypes.h.  Replace all #include \"Kismet\\HeadMountedDisplayFunctionLibrary.h\" with: #include \"HeadMountedDisplayFunctionLibrary.h\" or #include \"HeadMountedDisplayTypes.h\".")
^
/Users/Shared/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/HAL/Platform.h:724:29: note: expanded from macro 'COMPILE_WARNING'
        #define COMPILE_WARNING(x) GCC_DIAGNOSTIC_HELPER(GCC warning x)
                                   ^
/Users/Shared/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/HAL/Platform.h:723:35: note: expanded from macro 'GCC_DIAGNOSTIC_HELPER'
        #define GCC_DIAGNOSTIC_HELPER(x) _Pragma(#x)
                                         ^
<scratch space>:101:6: note: expanded from here
 GCC warning "This file has been moved to HeadMountedDisplay/Public/HeadMountedDisplayFunctionLibrary.h. Some types were moved to HeadMountedDisplay/Public/HeadMountedDisplayTypes.h.  Replace all #include \"Kismet\\HeadMountedDisplayFunctionLibrary.h\" with: #include \"HeadMountedDisplayFunctionLibrary.h\" or #include \"HeadMountedDisplayTypes.h\"."
     ^
[16/22] Compile GameModeWorld.gen.cpp
[17/22] Compile PlayerCharacter.gen.cpp
[18/22] Compile kbengine_ue4_demo.init.gen.cpp
[19/22] Compile GameEntity.gen.cpp
1 warning generated.
In file included from /Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Intermediate/Build/Mac/UE4Editor/Development/KBEnginePlugins/Module.KBEnginePlugins.cpp:5:
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/ClientSDKUpdater.cpp:103:48: warning: declaration shadows a local variable [-Wshadow]
                        UKBEventData_onImportClientSDKSuccessfully* pEventData = NewObject<UKBEventData_onImportClientSDKSuccessfully>();
                                                                    ^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/ClientSDKUpdater.cpp:42:40: note: previous declaration is here
        const UKBEventData_onImportClientSDK* pEventData = dynamic_cast<const UKBEventData_onImportClientSDK*>(eventData);
                                              ^
In file included from /Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Intermediate/Build/Mac/UE4Editor/Development/KBEnginePlugins/Module.KBEnginePlugins.cpp:42:
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Engine/NetworkInterfaceKCP.cpp:109:59: warning: 'CreateInternetAddr' is deprecated: To support different address sizes, use CreateInternetAddr with no arguments and call SetIp/SetRawIp and SetPort on the returned object Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
        addr_ = ISocketSubsystem::Get(PLATFORM_SOCKETSUBSYSTEM)->CreateInternetAddr(ip, addr.GetPort());
                                                                 ^
/Users/Shared/Epic Games/UE_4.24/Engine/Source/Runtime/Sockets/Public/SocketSubsystem.h:278:2: note: 'CreateInternetAddr' has been explicitly marked deprecated here
        UE_DEPRECATED(4.23, "To support different address sizes, use CreateInternetAddr with no arguments and call SetIp/SetRawIp and SetPort on the returned object")
        ^
/Users/Shared/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:227:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
                                          ^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Source/kbengine_ue4_demo/GameEntity.cpp:107:34: warning: declaration shadows a field of 'AGameEntity' [-Wshadow]
void AGameEntity::setModelID(int modelID)
                                 ^
/Users/chely/kbengine_ue4_demo-2.5.8 4.24 - 2/Source/kbengine_ue4_demo/GameEntity.h:76:6: note: previous declaration is here
        int modelID;
            ^
2 warnings and 2 errors generated.
1 warning generated.

**Comment by kebiao** [comment]
没有为Mac编译器适配。你可以用最新版本生成一下客户端sdk，如果还有错可以看看错在哪

**Comment by chelyzhou** [comment]
> 没有为Mac编译器适应。您可以使用最新版本生成一下客户端sdk，如果还有错可以看看错在哪

当前的错误信息是使用了新生成的ue4插件放入了ue4DEMO之中。

**Comment by kebiao** [comment]
排查一下
