### ISSUE TITLE
問新手問題

### ISSUE THREAD

**Issue by samsin1981** [kbengine/kbengine#1290]
最近回鍋 
寫到  reqcreateavatar  , ue4 按創建角色  , guiconsole傳回  index error : sequence index out of range
ue4 C++  , debug  EventData RoleType Name 有傳值 , this  AvatarList = Null ??? 
感覺是server 空值? , database  avatarList的 Info 也沒創 , code  報錯地方 , 看過原版 , 沒寫錯 . 
KBEngine 2.5.8

INFO root [0x00004ba4] [2020-05-05 02:34:33,847] - Resmgr::initialize: KBE_ROOT=C:/kbengine-2.5.8/
  INFO root [0x00004ba4] [2020-05-05 02:34:33,847] - Resmgr::initialize: KBE_RES_PATH=C:/kbengine-2.5.8/kbe/res/;C:/kbengine-2.5.8/course_assets/;C:/kbengine-2.5.8/course_assets/scripts/;C:/kbengine-2.5.8/course_assets/res/
  INFO root [0x00004ba4] [2020-05-05 02:34:33,847] - Resmgr::initialize: KBE_BIN_PATH=C:/kbengine-2.5.8/kbe/bin/server/
  INFO root [0x00004ba4] [2020-05-05 02:34:33,862] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.1.3 ( 192.168.1.3:20015 )
  INFO root [0x00004ba4] [2020-05-05 02:34:33,863] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.1.3:20015, SOMAXCONN=511.
  INFO root [0x00004ba4] [2020-05-05 02:34:33,865] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.1.3 ( 192.168.1.3:20005 )
  INFO root [0x00004ba4] [2020-05-05 02:34:33,866] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.1.3:20005, SOMAXCONN=511.
  INFO root [0x00004ba4] [2020-05-05 02:34:33,868] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.1.3 ( 192.168.1.3:60029 )
  INFO root [0x00004ba4] [2020-05-05 02:34:33,869] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.1.3:60029, SOMAXCONN=511.
  INFO root [0x00004ba4] [2020-05-05 02:34:33,869] - server-configs:
  INFO root [0x00004ba4] [2020-05-05 02:34:33,869] - 	gameUpdateHertz : 10
  INFO root [0x00004ba4] [2020-05-05 02:34:33,869] - 	entryScriptFile : kbemain
  INFO root [0x00004ba4] [2020-05-05 02:34:33,869] - 	internalTcpAddr : 192.168.1.3:60029
  INFO root [0x00004ba4] [2020-05-05 02:34:33,869] - 	externalTcpAddr : 192.168.1.3:20015
  INFO root [0x00004ba4] [2020-05-05 02:34:33,869] - 	externalUdpAddr : 192.168.1.3:20005
  INFO root [0x00004ba4] [2020-05-05 02:34:33,870] - 	componentID : 7001
  INFO root [0x00004ba4] [2020-05-05 02:34:34,069] - Components::findLogger: found logger, addr:192.168.1.3:60015
  INFO root [0x00004ba4] [2020-05-05 02:34:34,069] - Components::addComponent: reset orderLog, uid=28866!
  INFO root [0x00004ba4] [2020-05-05 02:34:34,070] - Components::addComponent[logger], uid=28866, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004ba4] [2020-05-05 02:34:34,077] - ---- baseapp Version: 2.5.8. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 15:40:41 Apr 13 2020. AppID: 7001. UID: 28866. PID: 18244 ----
  INFO root [0x00004ba4] [2020-05-05 02:34:34,077] - Server Sam: AMD Ryzen 7 1700 Eight-Core Processor           with 2097151kB RAM
  INFO root [0x00004ba4] [2020-05-05 02:34:34,077] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004ba4] [2020-05-05 02:34:34,078] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00004ba4] [2020-05-05 02:34:34,299] - Script::install(): is successfully, Python=(3.7.3 (default, Apr 13 2020, 15:39:05) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00004ba4] [2020-05-05 02:34:34,300] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00004ba4] [2020-05-05 02:34:34,420] - loaded entity-script:ExAccount(1).
 DEBUG root [0x00004ba4] [2020-05-05 02:34:34,420] - loaded entity-script:ExRole(2).
  INFO root [0x00004ba4] [2020-05-05 02:34:34,420] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00004ba4] [2020-05-05 02:34:34,421] - TelnetServer server is running on port 40000
  INFO root [0x00004ba4] [2020-05-05 02:34:34,956] - ---- baseapp is running ----
 DEBUG root [0x00004ba4] [2020-05-05 02:34:34,956] - Components::process(): Request for the process of identity...
  WARN root [0x00004ba4] [2020-05-05 02:34:41,137] - Forwarding logs to logger[192.168.1.3:60015/0/0/0]...
 ERROR root [0x00004ba4] [2020-05-05 02:51:10,538] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467494137282, lastReceivedTime=467414870923, inactivityExceptionPeriod=599492902)
   OFF root [0x00004ba4] [2020-05-05 02:51:10,541] - The following logs sent to logger failed:
  WARN root [0x00004ba4] [2020-05-05 02:51:10,542] - ==> [2020-05-05 02:51:10 538] TCPPacketReceiver::processPendingEvents(192.168.1.3:60015): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004ba4] [2020-05-05 02:51:10,542] - ==> [2020-05-05 02:51:10 539] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467494137282, lastReceivedTime=467414870923, inactivityExceptionPeriod=599492902)
  WARN root [0x00004ba4] [2020-05-05 02:51:10,673] - TCPPacketReceiver::processPendingEvents(192.168.1.3:60016): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004ba4] [2020-05-05 02:51:10,674] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467495493352, lastReceivedTime=467419640999, inactivityExceptionPeriod=599492902)
  INFO root [0x00004ba4] [2020-05-05 02:51:10,680] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00004ba4] [2020-05-05 02:51:10,687] - onBaseAppShutDown: state=0
  INFO root [0x00004ba4] [2020-05-05 02:51:10,687] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00004ba4] [2020-05-05 02:51:10,688] - onBaseAppShutDown: state=1
  INFO root [0x00004ba4] [2020-05-05 02:51:10,688] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00004ba4] [2020-05-05 02:51:10,688] - onBaseAppShutDown: state=2
 ERROR root [0x00004ba4] [2020-05-05 02:51:10,700] - ExAccount::onCellWriteToDBCompleted(1): not found dbmgr!
 ERROR root [0x00004ba4] [2020-05-05 02:51:10,701] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00004ba4] [2020-05-05 02:51:10,702] - ExAccount::~ExAccount(): 1
  INFO root [0x00004ba4] [2020-05-05 02:51:10,714] - Script::uninstall(): is successfully!
 DEBUG root [0x00004ba4] [2020-05-05 02:51:10,715] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00004ba4] [2020-05-05 02:51:11,015] - ThreadPool::destroy(): waiting for thread(2)[0x1afa2d8,0x1afa340,], try=1

**Comment by kebiao** [comment]
原版有错？

**Comment by samsin1981** [comment]
找到原因 , 下載不完全 .  原版沒錯 .
