### ISSUE TITLE
遇到个很难的问题self.streamFileToClient 下载 服务器正常 客户端报错

### ISSUE THREAD

**Issue by qinlinger1** [kbengine/kbengine#1291]
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <437ba245d8404784b9fbab9b439ac908>:0)
KBEngine.MessageReaderTCP.process (System.Byte[] datas, System.UInt32 offset, System.UInt32 length) (at Assets/Plugins/kbengine/kbengine_unity3d_plugins/MessageReaderTCP.cs:59)
KBEngine.PacketReceiverKCP.process () (at Assets/Plugins/kbengine/kbengine_unity3d_plugins/PacketReceiverKCP.cs:85)
KBEngine.NetworkInterfaceKCP.process () (at Assets/Plugins/kbengine/kbengine_unity3d_plugins/NetworkInterfaceKCP.cs:136)
KBEngine.KBEngineApp.process () (at Assets/Plugins/kbengine/kbengine_unity3d_plugins/KBEngine.cs:291)
KBEMain.KBEUpdate () (at Assets/Plugins/kbengine/kbengine_unity3d_plugins/KBEMain.cs:124)
KBEMain.FixedUpdate () (at Assets/Plugins/kbengine/kbengine_unity3d_plugins/KBEMain.cs:117)

报红 崩溃于次行代码Message msg = Messages.clientMessages[msgid];

**Comment by qinlinger1** [comment]
uint32 datasize = (GAME_PACKET_MAX_SIZE_TCP - sizeof(int16) - sizeof(uint32));  问题已经定位 我把上代码改成 	uint32 datasize = 10*(GAME_PACKET_MAX_SIZE_TCP - sizeof(int16) - sizeof(uint32));客户端报错  我想提升 下载速度 怎么办  客户端如何对应修改

**Comment by kebiao** [comment]
用tcp模式试试，可能是网络缓冲区爆了
