### ISSUE TITLE
关于导航的问题

### ISSUE THREAD

**Issue by snnui85** [kbengine/kbengine#1292]
版本：1.3.12
客户端：cocos creator
导航网格是用的tiledmap生成的tmx格式，在使用cocos js的官方demo时   导航就报错  提示：NavTileHandle::findStraightPath: Search terminated. Did not find goal state
大概研究了一下，如果坐标大于tilewidth或者tileheight  就报这个错，如果小于这个，不报错，但是不移动

**Comment by kebiao** [comment]
一般是目标位置不可到达
