### ISSUE TITLE
1.3.12版本配置externalInterface和externalAddress没有效果

### ISSUE THREAD

**Issue by dogagithub** [kbengine/kbengine#1296]
环境是腾讯云上的Ubuntu

![image](https://user-images.githubusercontent.com/1228178/81564100-cde0e900-93c9-11ea-90f7-36532aa98bd8.png)

运行之后日志里显示 internalAddr 与 externalAddr 都是内网地址

**Comment by dogagithub** [comment]
后续去 引擎目录下面改了 kbengine_defaults.xml 里的 externalAddress。生效了。

所以问题是项目目录下的 kbengine.xml 这几个配置不会生效？

**Comment by kebiao** [comment]
应该都能生效
