### ISSUE TITLE
PacketReader::processMessages收包BUG

### ISSUE THREAD

**Issue by zhengjianhua91** [kbengine/kbengine#1304]
当消息使用了扩展长度且第一个长度信息被截断接收不全时，将不会再处理第二个长度信息且将只包含包头的信息直接发送到业务逻辑接口，导致业务逻辑读取信息错误而崩溃

**Comment by kebiao** [comment]
更新试试

**Comment by zhengjianhua91** [comment]
当包体长度正好是65535的时候，且第二个长度信息被截断后，获取到完整的扩展长度应该还是65535，这时候消息长度-1是否有问题？

**Comment by kebiao** [comment]
> 当包体长度正好是65535的时候，且第二个长度信息被截断后，获取到完整的扩展长度应该还是65535，这时候消息长度-1是否有问题？

还有一个调整没有提交。 你晚点看看 @zhengjianhua91
