### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by jgwinner** [kbengine/kbengine#1306]
In the readme.md on the front page, it says documentation is at:

http://kbengine.org/docs/ 

However, when I visit this site, I get a 404 - webpage not found.

Please update the front page, OR (please) add an English translation. Since I visted KBEngine.org, I now seem to get documentation in English, so this is a huge help, thank you!

I'm sorry I couldn't put this in your native language.

        == John ==

**Comment by nordbit** [comment]
For old docs look in the archive.org
The app is now commercial - branch 2.x
Bugs, commits, forks - all in native language, do not expect too much.
Branch with friendly license - 1.x is outdated, You can build only on ancient linux, on modern almost all depedencies are broken - openssl, rpc, etc.
IMO if You are seriously interested - fork 1.x, gather new  team (english speaking), start updating project

**Comment by kebiao** [comment]
https://kbengine.github.io//docs/

Revised.

**Comment by jgwinner** [comment]
Who said anything about old docs?

I don't want to fork an old version, I'm interested in a modern engine with support that we can purchase. In other words, I'm looking for something like Photon Industries, but that works with Unreal (UE4), although we're still evaluating costs and servers.  

Maybe I stumbled on an earlier engine version, but it's the 2.x version that we are interested in.

You said "if you are seriously interested". Yes, we have funding from Monaco Foundry.

Thanks for fixing the link.

        == John ==
