### ISSUE TITLE
Build failing on CentOS 7

### ISSUE THREAD

**Issue by whitejasond** [kbengine/kbengine#1308]
make[3]: Entering directory `/home/kbe/kbengine/kbe/src/lib/resmgr'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/kbe/kbengine/kbe/src/lib/resmgr'
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libssl.a', needed by `/home/kbe/kbengine/kbe/bin/server/baseapp'.  Stop.
make[2]: Leaving directory `/home/kbe/kbengine/kbe/src/server/baseapp'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/kbe/kbengine/kbe/src/server'
make: *** [all] Error 2

ldconfig -p|grep ssl
        libxmlsec1-openssl.so.1 (libc6,x86-64) => /lib64/libxmlsec1-openssl.so.1
        libxmlsec1-openssl.so (libc6,x86-64) => /lib64/libxmlsec1-openssl.so
        libssl3.so (libc6,x86-64) => /lib64/libssl3.so
        libssl.so.10 (libc6,x86-64) => /lib64/libssl.so.10
        libssl.so (libc6,x86-64) => /lib64/libssl.so
        libevent_openssl-2.0.so.5 (libc6,x86-64) => /lib64/libevent_openssl-2.0.so.5

**Comment by kebiao** [comment]
Revised.
