### ISSUE TITLE
[版本不匹配]demo在unity2019登录后报错

### ISSUE THREAD

**Issue by Cherrymelon** [kbengine/kbengine#1314]
kbengine版本1.3.1
登录后提示红字version does not match the server.click to update kbengineplugin
点击更新脚本之后还是一堆错误,之前也有类似的issue,似乎走进死胡同了,求解

**Comment by kebiao** [comment]
更新完编译没有？

**Comment by Cherrymelon** [comment]
在哪里编译?我看`D:\project\kbengine-1.3.1\Assets\Plugins\kbengine_unity3d_plugins`里面也是cs文件呀

**Comment by develn** [comment]
你在服务器assets里面运行gensdk然后拷贝插件到unity项目里是一样的

**Comment by Cherrymelon** [comment]
拷贝插件之后运行会报错,net2.0是这样的
![image](https://user-images.githubusercontent.com/24840278/89516703-5b867600-d80b-11ea-9a26-c813e727c56e.png)
net4.0是这样的
![image](https://user-images.githubusercontent.com/24840278/89516810-7bb63500-d80b-11ea-8cde-5733079b7367.png)

**Comment by develn** [comment]
应该是unity版本兼容的问题，  你把那几个错误修复一下不就可以了？  修复完推送一份到kbe master？

**Comment by Cherrymelon** [comment]
没用过c#,如何修复?

**Comment by shijiaxing-web** [comment]
楼主解决了吗，我也遇到这个问题了，版本不匹配

**Comment by Cherrymelon** [comment]
> 楼主解决了吗，我也遇到这个问题了，版本不匹配

没有

**Comment by shijiaxing-web** [comment]
> > 楼主解决了吗，我也遇到这个问题了，版本不匹配
> 
> 没有

我解决了，解决办法是：服务器生成的UnityKbe插件有个脚本叫做KBEngine里面有个字段serverEntitydefMD5，把这个字段的值替换demo里面的KBEngine脚本里面的字段serverEntitydefMD5的值就行了

**Comment by shijiaxing-web** [comment]
什么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kbengine/kbengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 上午9:44
收件人:&nbsp;"kbengine/kbengine"<kbengine@noreply.github.com&gt;;
抄送:&nbsp;"石佳兴"<895510752@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [kbengine/kbengine] [版本不匹配]demo在unity2019登录后报错 (#1314)





 
Closed #1314.
