### ISSUE TITLE
Help to understand more about KBE's license!

### ISSUE THREAD

**Issue by duong2179** [kbengine/kbengine#1317]
Hi there,

I have a question regarding KBE's license: I want to develop a game using KBE and Unity 3D. Can I use KBE for free?

I couldn't understand KBE's license comprehensively as it is written in Chinese. I also found the below-quoted text:

>当产品为您创造收入或您因向最终用户传播产品而获得收入时，您必须尽可能早地在www.comblockengine.com上事先通知YOLO，包括通知YOLO产品名称、分发格式、唯一产品ID（如适用）和分发渠道。

Using Google translate:

>When the product creates revenue for you or you gain revenue from disseminating the product to end-users, you must notify YOLO in advance on www.comblockengine.com as early as possible, including notifying YOLO of the product name, distribution format, and unique product ID (such as Applicable) and distribution channels.

Does this imply that I will have to pay some money to YOLO if the game makes some revenue?

**Comment by kebiao** [comment]
Hi，

Currently, only need to inform.
