### ISSUE TITLE
数据库连接数一般设置成多少

### ISSUE THREAD

**Issue by hk520570** [kbengine/kbengine#1326]
当default库数据库连接数超过100左右，也就是参数numConnections设置超过100，数据库进程就会起不来了【阿里云局域网】
但是在本地服务器设置成200也没问题【不过此处用的localhost】
mysql的连接数都是配置成5000
阿里云用的服务器是游戏服务器4核8GB，数据库使用的是8核16GB  系统->centos7.8
本地用的是4核8GB 系统->centos7.8

**Comment by Wandar** [comment]
请问设置成多少比较合理呢,请教下
