### ISSUE TITLE
DB出现死锁

### ISSUE THREAD

**Issue by hk520570** [kbengine/kbengine#1327]
当数据库mysql出现死锁的时候，dbmgr整个进程都会崩溃，不知道大家有没有做容错方案之类的，可以分享下么？

**Comment by kbengine** [comment]
给重现方法

**Comment by hk520570** [comment]
我看日志上是出现死锁，对系统表生成表进行查询后，刚好此时writetodb调用该表，有可能就会产生死锁了，死锁后，整个dbmgr进程就挂掉了，导致所有的进程也退出了

**Comment by hk520570** [comment]
> 给重现方法

查询对应的系统表【kbe创建的实体表】，然后writetodb的时候调用该表，就会产生死锁了，死锁后dbmgr就崩溃了，导致所有进程退出

**Comment by kbengine** [comment]
能demo中实现一下重现问题打包发上来？
