### ISSUE TITLE
2D中AOI 同步移动时， X向右移动同步和Z向上移动同步时，会出现当前角色中AOI范围内的entity未触发leave事件。

### ISSUE THREAD

**Issue by oxversion** [kbengine/kbengine#1329]
角色“我的天”，向下移动时，在超出AOI范围之后：“我的天”游戏屏幕中正确接收到“神战”的leave事件；“神战”的游戏屏幕中正确接收到“我的天”的leave事件，视频如下：
https://user-images.githubusercontent.com/43436984/102852307-eaadc680-4458-11eb-825e-12ca133ed372.mp4

【bug1】角色“我的天”，向上移动时，在超出AOI范围之后：“我的天”游戏屏幕中**没有接收到“神战”的leave事件**；“神战”的游戏屏幕中正确接收到“我的天”的leave事件，视频如下：
https://user-images.githubusercontent.com/43436984/102852612-9c4cf780-4459-11eb-9066-a23f0c1ccccb.mp4

【bug2】角色“我的天”，向右移动时，在超出AOI范围之后：“我的天”游戏屏幕中**没有接收到“神战”的leave事件**；“神战”的游戏屏幕中正确接收到“我的天”的leave事件，视频如下：
https://user-images.githubusercontent.com/43436984/102852809-ff3e8e80-4459-11eb-9f29-bc8521659526.mp4

**Comment by kbengine** [comment]
你可以写个demo能机器人登陆自动重现这个问题，将demo打包发上来看看？

**Comment by oxversion** [comment]
一、这个是游戏资产库，重github上下载之后没有改过，就改了个数据库连接。 这个数据库连接是专门建立的测试连接，可以直接使用这个ip地址和帐号，你那边现在不需要修改，可以直接连接即可。
[kbengine_demos_assets - 2020-12-23 105105.zip](https://github.com/kbengine/kbengine/files/5733006/kbengine_demos_assets.-.2020-12-23.105105.zip)

二、下面这个用CocosCreator 2.4.3版本即可打开。
[【COCOS creator 2.4.3版本】 -MyHelloWord - 2020-12-23 105210.zip](https://github.com/kbengine/kbengine/files/5733032/COCOS.creator.2.4.3.-MyHelloWord.-.2020-12-23.105210.zip)

三、引擎源码就不传了，我用的就是在kbengine项目首页直接点击下载的zip包编译的。

四、登录测试帐号：
【角色：b1】 帐号：b1     密码：123
【角色：b2】 帐号：b2     密码：b2

五、重现流程：
1、用cocos creator 2.4.3 加载源码运行，直接打开浏览器，登录b1、b2后，直接点击进入游戏；
2、在b2的屏幕点击【上】按钮移动b2（需要多移动几次） ，直到b1的屏幕中没有玩家b2，此时会发现b2的屏幕中还能显示b1；此时就是【异常】状态。
3、把b2的位置重置，即在b2的屏幕点击【下】（需要多点击几次），直到b1屏幕中显示b2；
4、此时在b1屏幕中，点击【下】（需要多点击几次），直到b1屏幕中没有显示b2；此时会发现b2的屏幕中也没有显示b1，此时就是【正常】状态。
5、【右】的异常状态和【左】的正常 同理。

**Comment by oxversion** [comment]
> 你可以写个demo能机器人登陆自动重现这个问题，将demo打包发上来看看？

详细重现步骤和代码都已经发在issues 上了，你帮忙看一下。

**Comment by oxversion** [comment]
不仅新版本kbengine有这个情况，连老版本1.3.13测试也是同样的情况。

**Comment by FozuBlessNoBug** [comment]
AOI视野增加0.5，这个问题应该可以解决
看过源码，是那个十字链表排序引起的

**Comment by oxversion** [comment]
谢谢你，我试试。
&nbsp;



武汉牛凸科技有限公司&nbsp; &nbsp;&nbsp;
公司网址：www.oxtoo.cn
联系电话：152 7189 7168
QQ：4006676&nbsp;


新颖的设计方案，大胆的革新思想，灵活的运用最新技术是牛凸科技的特点，我们用心做好每一个项目。


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gameGear"<notifications@github.com&gt;; 
发送时间: 2020年12月23日(星期三) 下午3:17
收件人: "kbengine/kbengine"<kbengine@noreply.github.com&gt;; 
抄送: "张雨晴🐮"<4006676@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kbengine/kbengine] 2D中AOI 同步移动时， X向右移动同步和Z向上移动同步时，会出现当前角色中AOI范围内的entity未触发leave事件。 (#1329)





 
AOI视野增加0.5，这个问题应该可以解决
 看过源码，是那个十字链表排序引起的

**Comment by oxversion** [comment]
AOI视野增加0.5，这个问题应该可以解决
看过源码，是那个十字链表排序引起的

**Comment by oxversion** [comment]
> 你可以写个demo能机器人登陆自动重现这个问题，将demo打包发上来看看？

有人回复我说：
“AOI视野增加0.5，这个问题应该可以解决，看过源码，是那个十字链表排序引起的”， 

测试结果：
确实可以配置中增加0.5即可，可能是有问题，期待得到修复。
<defaultViewRadius>			
	<radius> 40.5 </radius>
	<hysteresisArea> 2.0 </hysteresisArea>
</defaultViewRadius>
