### ISSUE TITLE
机器人onLeaveWorld的问题

### ISSUE THREAD

**Issue by github-yxb** [kbengine/kbengine#1330]
我们发现机器人服务在某一个机器人的onLeaveWorld被回调后，就会出现有其它机器人析构,日志表现如下:  
S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,167] - Avatar::onLeaveWorld:  eid-20  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,167] - Avatar::onLeaveWorld:  eid-22  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,167] - Avatar::onLeaveWorld: eid-69  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,167] - Avatar::onLeaveWorld: eid-16  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,167] - Avatar::onLeaveWorld: eid-8  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,167] - Avatar::onLeaveWorld: eid-21  
DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 22    
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 69  
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 16   
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 8  
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 21  
S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::onLeaveWorld: 21  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::onLeaveWorld: 22  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::onLeaveWorld: 69  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::onLeaveWorld: 16  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::onLeaveWorld: 8  
 S_DBG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::onLeaveWorld: 20  
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 22  
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 69  
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 16  
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 8  
 DEBUG root [0x7fe26e7cffc0] [2020-12-24 10:53:36,169] - Avatar::~Avatar(): 20  

类似这6个机器人在互相Destory,导致机器人一局游戏后全掉.  
查看引擎的bots实现时发现是引擎在做的:  
![image](https://user-images.githubusercontent.com/7059300/103056771-d1cc1f00-45d8-11eb-9ea3-fd251e89f61c.png)
请问这样做的目的是什么?

**Comment by kebiao** [comment]
A离开B的视野了， bots中B的客户端需要清除A。
