### ISSUE TITLE
希望将dbmgr的报错或者警告在guiconsole里面显示出来。

### ISSUE THREAD

**Issue by shangdibaozi** [kbengine/kbengine#1332]
实际开发的时候没看见guiconsole里面有报错，线上运行的时候发现有的玩家数据回档。后来查了好久才发现是某个字段字符串长度低于配置里面的字符串长度，导致数据无法入库。在logger_dbmgr.log里面发现了很多Exception: Data too long for column这样的警告。如果在开发阶段能显示出来就好了。

**Comment by kebiao** [comment]
guiconsole只能平时开发调试用， 线上看日志还是应该直接搜log文件或者其他工具
