### ISSUE TITLE
创建实体，无法自动更新

### ISSUE THREAD

**Issue by zhangyq73** [kbengine/kbengine#1340]
定义了一个KBEngine.Entity，有def文件，entities.xml也加入了，相应的脚本也创建了，数据库表也有了，但是就是无法同步数据库，就是脚本的表字段改了改了，但是数据库却没有同步更新；而且创建表里会自动产生sm_autoLoad,请问这字段是做什么用的？为什么写不进去数据库？

**Comment by kebiao** [comment]
没有writeToDB？

**Comment by zhangyq73** [comment]
字段的属性<Persistent>true</Persistent>，这个也要调用writeToDB吗？

**Comment by kbengine** [comment]
当然
