### ISSUE TITLE
求助！teleport后的报错问题！

### ISSUE THREAD

**Issue by kop098** [kbengine/kbengine#1387]
请问，我的cell在自己的空间使用 self.teleport(None,坐标1，角度1)后
日志输出ERROR
Entity 6 is already a controller, don't repeat settings
但是cell实体进了onTeleportSusess了 正常瞬移
不知道什么原因？请大佬帮助！

**Comment by 186139** [comment]
`
bool Entity::setControlledBy(EntityCall* controllerBaseEntityCall)
{
	EntityCall *oldEntityCall = controlledBy();

	//  如果新旧的entityCall是同一个人，则不做任何更改
	if (oldEntityCall != NULL && controllerBaseEntityCall != NULL &&
		oldEntityCall->id() == controllerBaseEntityCall->id())
	{
		ERROR_MSG(fmt::format("Entity {0} is already a controller, don't repeat settings\n", oldEntityCall->id()));
		return false;
	}

`

你这是调用了setControlledBy吧

**Comment by kebiao** [comment]
调用了 setcontrollBy？ 不一定是teleport造成的
