### ISSUE TITLE
KBE ubuntu20.04编译

### ISSUE THREAD

**Issue by warm-dawn** [kbengine/kbengine#1398]
基本按项目docs上面所述进行操作

编译时遇到的问题是GCC版本太高 >=7.0就会报错:
entity_table_mysql.cpp:387:32: error: ‘%s’ directive output may be truncated writing up to 65534 bytes into a region of size 65427 [-Werror=format-truncation=]
解决方式:
编辑kbengine/kbe/src/build/common.mak
131行添加这句:CPPFLAGS += -Wno-format-truncation

**Comment by warm-dawn** [comment]
加了群问 2000人群里没什么人搭理 氛围低迷.

**Comment by tkuipers** [comment]
I realize you closed this, but for anyone else googling this issue, I made it work by including `CPPFLAGS += -Wno-format-truncation` on line 130 of `kbe/src/build/common.mak`.
