### ISSUE TITLE
如何开启多个baseapp

### ISSUE THREAD

**Issue by Leovany** [kbengine/kbengine#1417]
尝试步骤如下
1. 打开 start_server.bat ， 在里面增加一个baseapp
  如： `start "" "%KBE_BIN_PATH%/baseapp.exe" --cid=7002 --gus=8 --hide=1`
2. 启动之后，客户端连接报错，提示 
` KBEngine::Client_onLoginFailed: failedcode(20:SERVER_ERR_SRV_STARTING[服务器正在启动中。]), datas(17)!`

请问下，是否还有其他配置没改？

附图如下：

![666666](https://user-images.githubusercontent.com/2864116/116390661-e2bfc200-a850-11eb-9728-53f06ba4136f.png)

![6666666](https://user-images.githubusercontent.com/2864116/116390780-f8cd8280-a850-11eb-9b24-1322e104e5d0.png)

**Comment by huhubis** [comment]
cid唯一， uid要一致。 启动多个就行了。

**Comment by Leovany** [comment]
> cid唯一， uid要一致。 启动多个就行了。

我现在的配置就是这样，但客户端就是连接不上，改成一个baseapp之后就正常，不知道哪里有问题了...

十分感谢你的回答！

**Comment by Leovany** [comment]
webconsole 方式开启baseapp，也出现一样的情况
其次，kill 多的baseApp, 一直关不掉

![webconsole](https://user-images.githubusercontent.com/2864116/116784317-3a1a9800-aac6-11eb-9126-c7782f1804e2.png)
![webconsole_1](https://user-images.githubusercontent.com/2864116/116784320-3be45b80-aac6-11eb-8cb8-820a0c80d5d7.png)

**Comment by Leovany** [comment]
问题已解决，检查下 base/kbemain.py 文件中，onReadyForLogin(isBootstrap) 方法，刚开始写的时候，加了个判断 加载完成策划数据 才 `return 1.0` ， 注意这个`isBootstrap`的判断（第一个baseapp启动才为 true）

`
def onReadyForLogin(isBootstrap):
	"""
	KBEngine method.
	如果返回值大于等于1.0则初始化全部完成, 否则返回准备的进度值0.0~1.0。
	在此可以确保脚本层全部初始化完成之后才开放登录。
	@param isBootstrap: 是否为第一个启动的baseapp
	@type isBootstrap: BOOL
	"""
	# 延迟处理,服务器会一直监测执行，知道开放登录
	# 基础数据是否加载完成，加载完成开放登录
	# <1.0 = 不开放, >=1.0 开放

	My_WARNING_MSG("============= onReadyForLogin ,isOpenLogin = %s " %(GlobalConst.isOpenLogin));
	#return 1.0	

	if GlobalConst.isOpenLogin :
	   return 1.0;
	else:
		return 0.5;
`
