### ISSUE TITLE
loginapp01: [ERROR]: PacketReader::processMessages报错

### ISSUE THREAD

**Issue by Leovany** [kbengine/kbengine#1418]
环境：
   1. 版本 kbe V1.1.13 & unity 2019.4.23
   1. window 和  centos7 都会
   2. 已执行过`gensdk.bat`
   查资料说，插件不统一，执行了，也还会报错
‘https://blog.csdn.net/weixin_33895695/article/details/92148019’

unity客户端登录，就会报一条这样的错误
`loginapp01: [ERROR]: PacketReader::processMessages: not found msgID=25960, msglen=3, from 10.0.0.200:2674/0/0/0.`

请问下，这是什么问题？
十分感谢

![Login](https://user-images.githubusercontent.com/2864116/116775073-5224f400-aa93-11eb-9ddb-4c69c47dc59f.png)

**Comment by kebiao** [comment]
客户端发的包有问题。自己调试一下跟一下协议解析

**Comment by Leovany** [comment]
已解决

kbe生成插件是没问题，问题在于，因为之前断线重连的问题，客户端手动多次调用了`Ready`方法，去掉客户端手动增加的方法（demo形式）就没出现这个报错log ,  具体原因不清楚（多次刷新导致协议ID 变了吗？）

```
clientApp.cs

 public void Ready()
    {
        installEvents();
        initKBEngine();
        ready = true;
    }

```

**Comment by Leovany** [comment]
后面又进行了一次仔细排查，最终确定了问题
原因是，客户端后面增加了个判断，判断服务器是否开启的方法，方法里包含了 发送个hello协议测试，移除就没事了
```
public static async void WebSocket(string url,Action successCall,Action<Exception> failCall)
    {
        try
        {
            ClientWebSocket ws = new ClientWebSocket();
            CancellationToken ct = new CancellationToken();
            //添加header
            //ws.Options.SetRequestHeader("X-Token", "eyJhbGciOiJIUzI1N");
            Uri uri = new Uri(url);
            await ws.ConnectAsync(uri, ct);
            //  =========== 就是下面这一行 ====================
            // await ws.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes("hello")), WebSocketMessageType.Binary, true, ct);
            successCall?.Invoke();
        }
        catch (Exception ex)
        {
            failCall?.Invoke(ex);
        }
    }
}
```
