### ISSUE TITLE
cellappmagr, webconsole进程CPU内存暴涨

### ISSUE THREAD

**Issue by Leovany** [kbengine/kbengine#1421]
一）环境
1. kbe V1.1.13 
2. Unity2019.4.23
3. centos7 4核16G
4. docker 封装

二）描述：
今天早上起来，查看监控，发现云后台CPU和内存暴涨，通过`top`命令，发现是python 和 cellappmgr两个进程，当时在线玩家人数不多，重启webconsole进程之后

1.  python --> webconsole 
    昨天晚上22点左右刚部署上去
2. cellappmgr
   未使用cell模块，cellapp实体数为0
3. kill webconsole 进程 , 正常，重启 webconsole  之后，也正常了

请问下，这是什么原因？

十分感谢 ！！

附图：
![catHotel_docker_top](https://user-images.githubusercontent.com/2864116/116800827-13e11080-ab37-11eb-99f8-b7eef2a50658.png)

![11111111111](https://user-images.githubusercontent.com/2864116/116800833-1c394b80-ab37-11eb-9412-8774c04d2e9d.png)

![QQ截图20210502111040](https://user-images.githubusercontent.com/2864116/116800834-1f343c00-ab37-11eb-8e43-c53bdee63320.png)

![222222222222222](https://user-images.githubusercontent.com/2864116/116800852-3ffc9180-ab37-11eb-96a2-a0a1b54e3af9.png)

**Comment by kebiao** [comment]
guiconsole 工具可以看对象池大小， 可以看看cellappmgr的情况。
python进程这个需要用python的方法调试看看

**Comment by Leovany** [comment]
> python

CPU暴涨问题，不是必现，但baseapp 奔溃的时候，目前看到的log 显示CPU100% ，
 等他出现的时候，我在看看 ，一天baseapp挂两三次，头疼....

谢谢柯大的回复 ！

**Comment by Leovany** [comment]
已解决

这个问题出现，是因为baseapp异常奔溃之后，执行`safe_kill.sh`, 关闭服务器，baseappmgr进程一直关闭不成功（跟baseapp失联，卡主了？），导致baseappmgr CPU 满负荷在跑，因此不执行`safe_kill.sh`，改成直接执行`kill_server.sh`（毕竟baseapp奔溃了，玩家数据已丢失.....）, 后面就没出现这个现象了

PS : 说到底，问题还是出在 baseapp 因为什么原因导致奔溃，继续排查 ing.........哎..........

**Comment by kbengine** [comment]
> 已解决
> 
> 这个问题出现，是因为baseapp异常奔溃之后，执行`safe_kill.sh`, 关闭服务器，baseappmgr进程一直关闭不成功（跟baseapp失联，卡主了？），导致baseappmgr CPU 满负荷在跑，因此不执行`safe_kill.sh`，改成直接执行`kill_server.sh`（毕竟baseapp奔溃了，玩家数据已丢失.....）, 后面就没出现这个现象了
> 
> PS : 说到底，问题还是出在 baseapp 因为什么原因导致奔溃，继续排查 ing.........哎..........

调试看看 消耗在哪
