### ISSUE TITLE
baseapp奔溃后生成的core文件，如何调试定位问题

### ISSUE THREAD

**Issue by Leovany** [kbengine/kbengine#1422]
一、环境
1. kbe V1.1.13
2. Unity2019.4.23
3. centos7 4核16G
4. docker 封装

二、问题描述
线上问题，baseapp不知为何突然奔溃，奔溃之后，生成了`core`文件（docker环境），因为没有明确的信息（代码无处下手），所以想从这个`core`文件入手, 定位出问题，按照网上的教程，gdb调试 遇到了些问题

![5555555555555](https://user-images.githubusercontent.com/2864116/117109884-ed7dd800-adb7-11eb-861a-0a8a0ec4f6ae.png)

三、 gdb 调试步骤
参考资料： [gdb调试core文件快速定位core dump位置](https://blog.csdn.net/github_36186488/article/details/77976408)

1. 安装gdb
`yum -y install gdb`
2. gdb 加载core 查看
`
gdb '/kbe_server/kbengine/kbe/bin/server/baseapp --cid=710000 --gus=7&' core.5437
`

![image](https://user-images.githubusercontent.com/2864116/117106647-cffa3f80-adb2-11eb-8de9-008c9fce9263.png)

然后`bt ` 查看堆栈，但这`??`没看出什么东西 , 网上说缺少`gcc -g`编译源码

3. 编译该源代码
`
gcc -g /kbe_server/kbengine/kbe/bin/server/baseapp
`
![image](https://user-images.githubusercontent.com/2864116/117109957-05555c00-adb8-11eb-9387-ba7df2ca6b7a.png)

然后，就卡在这个位置 ，不知道怎么进行下一步操作了.....
请问下大家，这个问题怎么解决，还是说有其他方式可以调试 core文件，来定位问题

期待大家的回复，谢谢

PS:  如果学会了这一步，就再也不怕找奔溃的问题了

参考资料
1. gdb调试coredump(使用篇)
https://blog.csdn.net/sunxiaopengsun/article/details/72974548
2. gdb调试core文件快速定位core dump位置
https://blog.csdn.net/github_36186488/article/details/77976408

**Comment by huhubis** [comment]
-g不是这样加的   common.mak试试

**Comment by Leovany** [comment]
> 一、环境
> 
> 1. kbe V1.1.13
> 2. Unity2019.4.23
> 3. centos7 4核16G
> 4. docker 封装
> 
> 二、问题描述
> 线上问题，baseapp不知为何突然奔溃，奔溃之后，生成了`core`文件（docker环境），因为没有明确的信息（代码无处下手），所以想从这个`core`文件入手, 定位出问题，按照网上的教程，gdb调试 遇到了些问题
> 
> ![5555555555555](https://user-images.githubusercontent.com/2864116/117109884-ed7dd800-adb7-11eb-861a-0a8a0ec4f6ae.png)
> 
> 三、 gdb 调试步骤
> 参考资料： [gdb调试core文件快速定位core dump位置](https://blog.csdn.net/github_36186488/article/details/77976408)
> 
> 1. 安装gdb
>    `yum -y install gdb`
> 2. gdb 加载core 查看
>    `gdb '/kbe_server/kbengine/kbe/bin/server/baseapp --cid=710000 --gus=7&' core.5437`
> 
> ![image](https://user-images.githubusercontent.com/2864116/117106647-cffa3f80-adb2-11eb-8de9-008c9fce9263.png)
> 
> 然后`bt ` 查看堆栈，但这`??`没看出什么东西 , 网上说缺少`gcc -g`编译源码
> 
> 1. 编译该源代码
>    `gcc -g /kbe_server/kbengine/kbe/bin/server/baseapp`
>    ![image](https://user-images.githubusercontent.com/2864116/117109957-05555c00-adb8-11eb-9387-ba7df2ca6b7a.png)
> 
> 然后，就卡在这个位置 ，不知道怎么进行下一步操作了.....
> 请问下大家，这个问题怎么解决，还是说有其他方式可以调试 core文件，来定位问题
> 
> 期待大家的回复，谢谢
> 
> PS: 如果学会了这一步，就再也不怕找奔溃的问题了
> 
> 参考资料
> 
> 1. gdb调试coredump(使用篇)
>    https://blog.csdn.net/sunxiaopengsun/article/details/72974548
> 2. gdb调试core文件快速定位core dump位置
>    https://blog.csdn.net/github_36186488/article/details/77976408

附个官方文档：http://server.muguayun.top:10090/file/KBEngineDoc/www.comblockengine.com/docs/1.0/advance/debug/index.html

文档太简略了，关于第二步断点调试，不知道要做什么.....

**Comment by Leovany** [comment]
附个官方文档：http://server.muguayun.top:10090/file/KBEngineDoc/www.comblockengine.com/docs/1.0/advance/debug/index.html

文档太简略了，关于第二步断点调试，没看懂要怎么弄....

**Comment by Leovany** [comment]
已解决 

注意格式写法，`gdb 对应的进程目录 core.xxx`
比如 ` gdb ' /kbe_server/kbengine/kbe/bin/server/baseapp' core.5845`
然后，用`bt` 或者 `where` 查看堆栈

如出现 `??` 像我之前这种，要么gdb格式不对，要么奔溃的进程不对
比如：

![7200000000000](https://user-images.githubusercontent.com/2864116/117538001-bcf7a180-b036-11eb-9968-7e72f8227a27.png)

![730000000](https://user-images.githubusercontent.com/2864116/117538009-bff29200-b036-11eb-80b4-559ae1c4450f.png)

**Comment by huhubis** [comment]
> 已解决
> 
> 注意格式写法，`gdb 对应的进程目录 core.xxx`
> 比如 ` gdb '/kbe_server/kbengine/kbe/bin/server/baseapp' core.5845`
> 然后，用`bt` 或者 `where` 查看堆栈
> 
> 如出现 `??` 像我之前这种，要么gdb格式不对，要么奔溃的进程不对
> 比如：
> 
> ![7200000000000](https://user-images.githubusercontent.com/2864116/117538001-bcf7a180-b036-11eb-9968-7e72f8227a27.png)
> 
> ![730000000](https://user-images.githubusercontent.com/2864116/117538009-bff29200-b036-11eb-80b4-559ae1c4450f.png)

应该有log吧   你这个看起来是从数据库load的东西太大了， 撑爆了
    template <typename T> T read(size_t pos) const
    {
        if(sizeof(T) > length())
            throw MemoryStreamException(false, pos, sizeof(T), length());

**Comment by Leovany** [comment]
生成的core文件，出现次数最多的是下面两个，dbmgr（上图）目前就看到一次

麻烦大佬帮忙看一眼下面两张，十分感谢

![74000000000](https://user-images.githubusercontent.com/2864116/117539092-92f4ae00-b03b-11eb-8751-c40fef1fcdc7.png)

![750000000000](https://user-images.githubusercontent.com/2864116/117539094-96883500-b03b-11eb-900e-3fdc789310e9.png)

**Comment by kbengine** [comment]
> 生成的core文件，出现次数最多的是下面两个，dbmgr（上图）目前就看到一次
> 
> 麻烦大佬帮忙看一眼下面两张，十分感谢
> 
> ![74000000000](https://user-images.githubusercontent.com/2864116/117539092-92f4ae00-b03b-11eb-8751-c40fef1fcdc7.png)
> 
> ![750000000000](https://user-images.githubusercontent.com/2864116/117539094-96883500-b03b-11eb-900e-3fdc789310e9.png)

你没更新代码吧，这是个日志格式化错误
