### ISSUE TITLE
如何查看.pyprofile文件

### ISSUE THREAD

**Issue by Leovany** [kbengine/kbengine#1423]
最近在找baseapp奔溃问题，通过论坛，看到可以通过打开`kbengine.xml` 中 profiles 开关来帮助定位问题。
等baseapp奔溃之后，目录下生成了 `baseapp1.pyprofile`和`cellapp1.pyprofile` 两个文件，
直接打开，发现是二进制，然后通过`.pyprofile`关键字搜索，找到的内容，要么是说环境配置，要么是`python -m cProfile -o result.out  ccc.py` 这种形式，跟xxx.pyprofile似乎关系不大....

想问一下 ：
1. .pyprofile文件是kbe自定义的后缀格式吗

2. 如何打开.pyprofile文件，定位奔溃问题

期待大佬们的回复，谢谢！

附 kbengine.xml 修改内容
```
<profiles>
		<!-- 如果设置为true，引擎启动时就会开始记录相关profile信息， 进程退出后将导出一份报告 
				(if is true, Engine start is completed, start to record profile information, 
				Process exit will export a report.)
			-->
			<cprofile> true</cprofile>
			<pyprofile> true</pyprofile>
			<eventprofile> true</eventprofile>
			<networkprofile> true</networkprofile>
		</profiles>
```

**Comment by huhubis** [comment]
guiconsole上的profile页面比这个好用

**Comment by huhubis** [comment]
pyprofile就是python的profile ， 你自己查手册吧

**Comment by Leovany** [comment]
已解决，我还是附一下步骤吧，防止像我一样的小白，要重新踩坑.........

读取profile文件步骤：
```
import pstats
Profile_Path = r"C:\Users\Administrator\Desktop\catHotel_Log\2021-05-08\baseapp1.pyprofile"

print("Profile_Path = " + Profile_Path)

# 加载文件，生成 Stats对象
p = pstats.Stats(Profile_Path)
# ===== 前N个耗时最长 =======
p.sort_stats("cumulative").print_stats(30)
# ===== 显示函数被哪些函数调用======
p.print_callers() 
# ===== 显示哪个函数调用了哪些函数 ======
p.print_callees()
```

![76000000000000](https://user-images.githubusercontent.com/2864116/117569595-fe508580-b0f8-11eb-80c7-389e7cabf76b.png)

附带参考资料：
* profile 手册
   https://docs.python.org/zh-cn/3/library/profile.html
* pstats.Stats
   https://docs.python.org/zh-cn/3/library/profile.html#pstats.Stats
