### ISSUE TITLE
Baseapp奔溃问题

### ISSUE THREAD

**Issue by Leovany** [kbengine/kbengine#1425]
经过这几天的信息收集，把baseapp奔溃相关日志整理一下，希望有大佬能帮忙看看问题出现在哪，
自己也是第一次对kbe这样仔细的排查问题（头发没了....），
也希望对之后的人有些帮助吧

# 环境
1. kbe V1.3.13
2. mysql 5.7
3. Unity 2019.4.23
4. docker封装kbe和mysql

# 问题
在内测阶段，baseapp不知为什么异常奔溃

# 日志信息
## core 文件
1.  下面这个出现最多（基本上是这个问题导致）
![8000000000000](https://user-images.githubusercontent.com/2864116/117569893-6489d800-b0fa-11eb-8653-2bb1c97ecf2d.png)

2. 偶尔看到
![830000000000](https://user-images.githubusercontent.com/2864116/117569910-7a979880-b0fa-11eb-905e-44537949deed.png)

3.  目前只看到一次
![840000000000](https://user-images.githubusercontent.com/2864116/117569981-d3ffc780-b0fa-11eb-85cd-f3412e8c7da1.png)

## .pyprofile 文件
baseapp 上
1. reqCommonEvent :  客户端请求服务器的通信协议，全部走这个方法，耗时高也是正常
2.  Hotxxxx : 是使用论坛上的别人写的热更新，功能能用，但性能方面没有测试

![860000000000000](https://user-images.githubusercontent.com/2864116/117570052-3f499980-b0fb-11eb-9a27-85d1415e0dcb.png)

![870000000000](https://user-images.githubusercontent.com/2864116/117570053-41abf380-b0fb-11eb-9d12-543233b39105.png)

![880000000000](https://user-images.githubusercontent.com/2864116/117570181-b54e0080-b0fb-11eb-971b-2ea4f352d287.png)

## 引擎log文件
1. logger_baseappmgr.log
![image](https://user-images.githubusercontent.com/2864116/117570886-d19f6c80-b0fe-11eb-8bec-a757ee8dd3d7.png)
2. logger_baseapp.log
![image](https://user-images.githubusercontent.com/2864116/117571002-42468900-b0ff-11eb-8373-8ef0f0b52dfb.png)
3. logger_dbmgr.log
![image](https://user-images.githubusercontent.com/2864116/117571031-66a26580-b0ff-11eb-99c8-0649568efd97.png)
4. logger_loginapp.log
![image](https://user-images.githubusercontent.com/2864116/117571109-ad905b00-b0ff-11eb-919a-e7913b3f4c29.png)
5. logger_cellapp.log
![image](https://user-images.githubusercontent.com/2864116/117571188-02cc6c80-b100-11eb-90a2-c55decc8ff9a.png)

**Comment by kbengine** [comment]
前2个你代码应该不够新。
第三个就是从数据库一次性加载了太大的内容，自己做一下切割读取。

pyprofile不能看c++问题

**Comment by Leovany** [comment]
1. 代码应该不够新
    V1.3.13 , 已经是最新的了，这个我要怎么更新？

2. 图上 Account 、 hotfix 这个耗时正常吗，
     如果不正常，会导致 baseapp奔溃吗
   
麻烦柯大了

PS: 目前人数不多情况下，一天都能奔溃个2-3次，好绝望.....

**Comment by Leovany** [comment]
根据柯大给的提示，按着V1.3.13 以上对比最新的代码，根据 core 提示，找到下面这个，然后去掉多余的 `}` ，重新编译了kbe,
编译之后的两天终于没奔溃了！！！

PS : 但我们这次的内测时间也结束了，没法继续观察，但这个肯定是导致奔溃原因之一，不确定是否还有其他原因，继续观察吧

！！！ 用了V1.3.13 版本的朋友们，记得要改啊  ！！！

![image](https://user-images.githubusercontent.com/2864116/118581391-28bed480-b7c4-11eb-88fd-3bfc8e25c507.png)

**Comment by Leovany** [comment]
很久没出现了，确定这是个问题，使用 V1.3.13 版本记得更新啊！！！
-- 血与泪的教训
