### ISSUE TITLE
kbe启动，dbmgr进程卡住

### ISSUE THREAD

**Issue by zhangchao2021** [kbengine/kbengine#1427]
![image](https://user-images.githubusercontent.com/83998922/117756027-f7885680-b24f-11eb-8a2d-5fb1fc9db7e8.png)
dbmgr 的log如上：

![image](https://user-images.githubusercontent.com/83998922/117756222-5d74de00-b250-11eb-80c8-766c8caa9961.png)
生成core文件，gdb如上。
大侠们帮看看是什么问题的

**Comment by huhubis** [comment]
用老一点的系统   openssl和系统的版本冲突了

**Comment by zhangchao2021** [comment]
> 用老一点的系统 openssl和系统的版本冲突了

谢谢
