### ISSUE TITLE
EntityComponent的属性变化时，同步给客户端utype有问题

### ISSUE THREAD

**Issue by ypcyyy1** [kbengine/kbengine#1443]
https://github.com/kbengine/kbengine/blob/f5e55b4789fc8ad5df778eac53d76897448c38e2/kbe/src/server/baseapp/entity.cpp#L140

pScriptModule_->usePropertyDescrAlias()判断第一个值没问题，但第二个值应该用pEntityComponent->pComponentScriptDefModuleDescrs()->usePropertyDescrAlias()来判断，要不然Entity的属性小于255Component属性大于255就出问题了，客户端解析部分也有这个问题

**Comment by ypcyyy1** [comment]
https://github.com/kbengine/kbengine/blob/f5e55b4789fc8ad5df778eac53d76897448c38e2/kbe/src/lib/entitydef/entity_component_call.cpp#L172

这里好像也有类似问题，应该用pEntityCall_->pScriptModule()->usePropertyDescrAlias()来判断

**Comment by huhubis** [comment]
🈶️鞋测试案例吗？用demo能重现错误？
