### ISSUE TITLE
dbmgr初始化线程失败，mysql_thread_safe返回false

### ISSUE THREAD

**Issue by Amither113** [kbengine/kbengine#1518]
log如下：
` INFO root [2021-11-17 06:22:33,719] - Resmgr::initialize: KBE_ROOT=/kbengine/
  INFO root [2021-11-17 06:22:33,719] - Resmgr::initialize: KBE_RES_PATH=/kbengine/kbe/res/:/kbengine/kbengine_demos_assets/:/kbengine/kbengine_demos_assets/res/:/kbengine/kbengine_demos_assets/scripts/
  INFO root [2021-11-17 06:22:33,719] - Resmgr::initialize: KBE_BIN_PATH=/kbengine/kbe/bin/server/
  INFO root [2021-11-17 06:22:33,719] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 172.17.0.2 ( 172.17.0.2:56621 )
  WARN root [2021-11-17 06:22:33,719] - NetworkInterface::initialize(INTERNAL-TCP): Operating with a receive buffer of only 425984 bytes (instead of 16777216)
  WARN root [2021-11-17 06:22:33,719] - NetworkInterface::initialize(INTERNAL-TCP): Operating with a send buffer of only 425984 bytes (instead of 16777216)
  INFO root [2021-11-17 06:22:33,719] - NetworkInterface::initialize(INTERNAL-TCP): address 172.17.0.2:56621, SOMAXCONN=511.
  INFO root [2021-11-17 06:22:33,719] - server-configs:
  INFO root [2021-11-17 06:22:33,719] -         internalTcpAddr : 172.17.0.2:56621
  INFO root [2021-11-17 06:22:33,719] -         componentID : 3129652375332859700
  WARN root [2021-11-17 06:22:33,719] - invalid UID(0) <= 0, please check UID for environment! automatically set to 57054.
  WARN root [2021-11-17 06:22:34,034] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20917, Address already in use
  INFO root [2021-11-17 06:22:34,037] - ---- dbmgr Version: 2.5.10. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CEEA1830B25FC811C6B0172173A5FCD0. Config: Hybrid64 X64. Built: 05:29:16 Nov 17 2021. AppID: 3129652375332859700. UID: 57054. PID: 64283 ----
  INFO root [2021-11-17 06:22:34,037] - Server 51f0a5d0a624: Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz x40 with 131657836kB RAM
  INFO root [2021-11-17 06:22:34,037] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2021-11-17 06:22:34,038] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2021-11-17 06:22:34,138] - Script::install(): paths=/kbengine/kbengine_demos_assets/scripts/common:/kbengine/kbengine_demos_assets/scripts/data:/kbengine/kbengine_demos_assets/scripts/user_type:/kbengine/kbengine_demos_assets/scripts/server_common:/kbengine/kbengine_demos_assets/scripts/db:/kbengine/kbe/res/scripts:/kbengine/kbe/res/scripts/common:/kbengine/kbe/res/scripts/common/lib-dynload:/kbengine/kbe/res/scripts/common/DLLs:/kbengine/kbe/res/scripts/common/Lib:/kbengine/kbe/res/scripts/common/Lib/site-packages:/kbengine/kbe/res/scripts/common/Lib/dist-packages.
  INFO root [2021-11-17 06:22:34,173] - Script::install(): is successfully, Python=(3.7.3 (default, Nov  7 2021, 04:44:39)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)])!
  INFO root [2021-11-17 06:22:34,173] - Script::install(): KBExtra is successfully!
  INFO root [2021-11-17 06:22:34,233] - Dbmgr::initializeEnd: digest(46596D3750651E9F679C7775CD577E35)
S_INFO root [2021-11-17 06:22:34,233] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2021-11-17 06:22:34,233] - TelnetServer server is running on port 32000
  INFO root [2021-11-17 06:22:34,233] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2021-11-17 06:22:34,233] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
3B6445530EBDF6B39A0DC9AABDB0A3985DEA9B38E3E0D67C01A0092A0B91A127B0AA2F04C484A62EE6AEB5FAE9E36AB97F32A0A1226424FFA663BDBC65DE25909A655E81600504619F106547F77F6F7839CBF45477E440899531E4D4F0598F55CE3D9EE017AF328158393775AF85023D2969ABDC7058C198FFB58F1B816B80A9
 DEBUG root [2021-11-17 06:22:34,233] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2021-11-17 06:22:34,235] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2021-11-17 06:22:34,235] - DBUtil::createInterface[0x7ffde4e4adb0]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2021-11-17 06:22:34,235] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2021-11-17 06:22:34,235] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
  INFO root [2021-11-17 06:22:34,240] - Stack: #0 KBEngine::DebugHelper::backtrace_msg()
  INFO root [2021-11-17 06:22:34,240] - Stack: #1 KBEngine::myassert(char const*, char const*, char const*, unsigned int)
  INFO root [2021-11-17 06:22:34,240] - Stack: #2 KBEngine::DBUtil::initThread(std::string const&)
  INFO root [2021-11-17 06:22:34,240] - Stack: #3 KBEngine::DBThread::onStart()
  INFO root [2021-11-17 06:22:34,240] - Stack: #4 KBEngine::thread::TPThread::threadFunc(void*)
  INFO root [2021-11-17 06:22:34,240] - Stack: #5
  INFO root [2021-11-17 06:22:34,240] - Stack: #6 clone
   OFF root [2021-11-17 06:22:34,240] - assertion failed: false, file db_interface.cpp, line 50, at: initThread
`
环境：
centos7.8
mysql5.1.73-log

**Comment by huhubis** [comment]
用老一点的系统看看

**Comment by Amither113** [comment]
没找到解决办法
最后改用Centos7.5+mariadb服务器，dbmgr启动成功

**Comment by Amither113** [comment]
没找到解决方案
改用Centos7.5+mariadb才启动成功

**Comment by shadowzhougit** [comment]
安装mariadb后，要使用kbengine，编译和安装流程和mysql一样吗？ 谢谢!
