### ISSUE TITLE
2.5.10 dbmgr启动报错

### ISSUE THREAD

**Issue by a492486** [kbengine/kbengine#1527]
WARN root [2021-12-20 11:22:19,718] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
E3AD6C1EA7EAAC343827041D1FEAFBCEDEAC4AC71916AA69E898FDC77969545D0D32821CCA4D53C6DA07A366B2199A13B481FE42BFE9F1C722C503E387C4572736C63FAC2FD838E8B025754AB2B626C9E2E9292EC5884E1363E90911EAC427B83179F6B5A06E606A177AC1C43481BDBD5EBEB9D78692DBA78E8A8DBBA90EA34C
我把encrypt设置成true，然后把密码设置成他提示的这个，再起他又提示了一个新的。
我把encrypt设置成false，进程也没起起来，日志里也没有报错

**Comment by a492486** [comment]
生成了core文件。。我用gdb看好像是log4j报错，我拉下最新的代码试试

**Comment by a492486** [comment]
。。最新的代码make不通过，懒得弄了。。也不知道是又make了几次，还是重启了服务器。。现在没log4j这个错误了。。正常起起来了

**Comment by huhubis** [comment]
：）
