### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by YimenLeong** [kbengine/kbengine#1529]
entity_table_mysql.cpp:59:95: error: ‘SYSTEM_CHARSET_MBMAXLEN’ was not declared in this scope
     if ((length == 0) || (sqlitemtype == FIELD_TYPE_VAR_STRING ? (int32)length == tf.length / SYSTEM_CHARSET_MBMAXLEN/*Mysql½«length·Ŵ⊎±¶*/ :

**Comment by YimenLeong** [comment]
处理好了

**Comment by 14488474** [comment]
请问怎么处理的
