### ISSUE TITLE
登录不进游戏，该如何排查问题

### ISSUE THREAD

**Issue by Leovany** [kbengine/kbengine#1547]
情况：
   玩家反馈，今天凌晨3点，登录不进游戏，（类似登录不进也有少部分玩家在反馈）

   根据玩家的账号，先去logs目录下，`logger_loginapp.2022-02-10.log` 找到这个登录连接信息，但最早的是10点记录，没有玩家说的3点左右记录
![bug](https://user-images.githubusercontent.com/2864116/153333851-804b4bec-4459-474f-9e70-4d537905680e.png)

因此，请教一下各位大佬
1. `logger_loginapp.XXX.log` 这个文件，是否是客户端最开始连接的日志文件
2. 该如何排查这个登录不进的问题？
   （网络波动？客户端问题？日志排查流程）
3. 目前loginapp只有一个20013，是否可以通过多个loginapp来解决这个问题
   （单个loginapp客户端连接上限数量是多少？）

期待大佬的回复，感谢！

**Comment by huhubis** [comment]
1：是的
2：都有可能
3：可以多开， 但不一定能解决问题吧   网络波动和客户端问题你怎么办？

你把他号要来测试一下就知道了？

**Comment by Leovany** [comment]
收到，谢谢~
