### ISSUE TITLE
loginap多开，端口号相同，是否正常？

### ISSUE THREAD

**Issue by Leovany** [kbengine/kbengine#1550]
版本：kbe V1.3.13 

在start_server.bat文件中，多开xxapp，来实现负载
1. 多开baseapp ，端口号依次往下累加
2. 多开loginapp, 端口号竟然是相同，这个是正常的吗？

  我预期是跟多开xxxapp逻辑是一样，端口号也是依次往下累加，这是正常的吗，还是loginapp这个比较特殊？

![loginapp](https://user-images.githubusercontent.com/2864116/153987157-c3b0cd18-2ef0-4bb6-81ec-0fe95798ea2a.png)

**Comment by Leovany** [comment]
放到centos7环境中，看loginapp 日志，只有第一个日志正常， 其他loginapp提示端口占用，应该是有问题的 ，怎么解决呢？

1. 第一个loginapp, 绑定端口成功
![image](https://user-images.githubusercontent.com/2864116/154184629-c01fd334-6168-416d-bc65-1c5dbb0d7440.png)
1. 其他loginapp, 绑定端口失败（提示占用）
![image](https://user-images.githubusercontent.com/2864116/154184549-bbec176c-71e7-4aa7-ad91-5200d847e3bb.png)

**Comment by huhubis** [comment]
启动参数有端口参数 ？

**Comment by Leovany** [comment]
> 启动参数有端口参数 ？

恩？没有吧，我这边没改其他的了

**Comment by Leovany** [comment]
已解决：
`start_server.bat`和`kbengine.xml` 开放端口保持一致
PS: 配置是0，并不是端口号自动递增的意思.....

![image](https://user-images.githubusercontent.com/2864116/177271671-2f60f735-9ddd-4aab-832e-07a8315cf6b5.png)

**Comment by Leovany** [comment]
收到，谢谢~
