### ISSUE TITLE
把实体 writeToDB了为啥他的databaseID还是0

### ISSUE THREAD

**Issue by a492486** [kbengine/kbengine#1558]
globalgroup =KBEngine.createEntityLocally("Group", params)
			if globalgroup:
				globalgroup.writeToDB()
				#globalgroup.groupID=globalgroup.databaseID
				DEBUG_MSG('onBaseAppReady: globalgroup=%i' % globalgroup.databaseID)
直接用createEntityLocally创建的实体

**Comment by a492486** [comment]
后来发现写在writeToDB的回调里就保存了

**Comment by RaymondKing123** [comment]
说明writeToDb内部是一个异步过程
