### ISSUE TITLE
教学指南

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#158]

**Comment by qykings** [comment]
说有指南,为何没有,现在出了错,我都不知怎么搞

**Comment by kbengine** [comment]
还在制作中，这是一个未完成的issue。

**Comment by kbengine** [comment]
目前可以加群学习16535321

**Comment by liudaafang** [comment]
感谢作者无私奉献，我正在为KBEngine制作教学课程， 希望能够出一份微薄之力！

**Comment by basstal** [comment]
群满了怎么办呀？

**Comment by kbengine** [comment]
加这个461368412
@basstal

**Comment by Thomas-JZQ** [comment]
@liudaafang 大侠  我follow你了   啥时候出教学课程啊   我这种新手急需学习资料来着
