### ISSUE TITLE
建议 KBEngine 开发几个用于校验角色名是否被使用的功能

### ISSUE THREAD

**Issue by cyecp** [kbengine/kbengine#204]
建议 KBEngine 开发一个 bool LockAvatarName(Int Table,string AvatarName) 用于检测角色名是否可用（Table是一个单独的角色名到DBID的映射表，AvatarName做数据库的key键），如存在AvatarName就返回false,如不存在写入数据库，DBID项先写入0，然后返回True,另对应 void UnlockAvatarName(Int Table,string AvatarName) 用于释放某个角色名。 和 void UpdateAvatarName(Table,AvatarName,AvatarDBID) 用于更新角色名对应的DBID，还有DBID GetDBIDByAvatarName(Table,AvatarName).

**Comment by 516057094** [comment]
最新版本的源码好像有两个新增文件没有提交！导致编译通不过，不过只要删除调用代码即可，很好修复。

**Comment by kbengine** [comment]
什么文件没提交？ 每次提交这里会自动编译， https://travis-ci.org/kbengine/kbengine， 可以看到最新版本编译状态为pass

**Comment by kbengine** [comment]
角色名称校验属于逻辑层功能，并不是所有游戏都需要唯一名称，而且部分游戏角色名称甚至由第三方运营平台获得和创建， 要开发也是在脚本层实现一个有针对性的功能模块， 不过目前并没有在计划中。
