### ISSUE TITLE
关于linux下查看进程是否启动状态

### ISSUE THREAD

**Issue by genghaolove** [kbengine/kbengine#218]
linux 下 没有guiconsole哦
ps axu | grep -E 'kbmachine|loginapp|baseapp|cellapp|messagelog|baseappmgr|cellappmgr|dbmgr|billingsystem'

**Comment by kbengine** [comment]
进程有可能分布在几台机器上，如上命令只能查看本机进程

linux有cluster_controller.py可以使用
http://kbengine.org/cn/docs/tools/pycluster.html
