### ISSUE TITLE
跨服或者多服务集群使用一个数据库

### ISSUE THREAD

**Issue by thoreaw** [kbengine/kbengine#221]
假设我想使用kbe实现多服务器用一个数据库或者跨服获取数据如何实现

**Comment by kbengine** [comment]
不支持多服务器用痛一个数据库，这样会冲突。
获取其他服的数据可以通过pysocket来完成，这里有一个例子
kbengine.org/assets/other/py/Poller.py

其他参考：
http://bbs.kbengine.org/forum.php?mod=viewthread&tid=8&extra=page%3D4

**Comment by thoreaw** [comment]
非常感谢！
