### ISSUE TITLE
make mysql include路径问题 #269

### ISSUE THREAD

**Issue by Renyunhuang** [kbengine/kbengine#269]
在初次编译0.6.21 时，/kbe/src/lib/db_mysql/* 对于 include 'mysql/mysql.h' 找不到依赖头文件
修改：src/build/common.mak
line 142 新增：KBE_INCLUDES += -I $(KBE_ROOT)/kbe/src/lib/dependencies/mysql 解决

**Comment by kbengine** [comment]
yum install mysql-devel
yum install mysql-server
