### ISSUE TITLE
ERROR级别建议控制台提示

### ISSUE THREAD

**Issue by phypor** [kbengine/kbengine#280]

**Comment by kbengine** [comment]
windows控制台已经显示， linux一般在后台跑， 关了securecrt下次即使有输出也看不到

**Comment by phypor** [comment]
是这样的，日志肯定是必须log进去，但是也建议提供下显示控制台，因为方便调试，方便排查问题，例如nginx的启动，如果错误也会提供error级别的控制台显示。如果启动完成了，一般中途出错问题肯定都是找日志的了。主要还是方便排查启动错误。

**Comment by kbengine** [comment]
值得考虑

**Comment by kbengine** [comment]
已改善
