### ISSUE TITLE
网络IO轮询逻辑在主线程中，感觉对性能影响颇大

### ISSUE THREAD

**Issue by mjssw** [kbengine/kbengine#288]
kbengine的网络IO轮询逻辑在主线程中，感觉对性能影响颇大，建议使用asio异步网络库，将主逻辑循环与IO循环分开。asio不带boost的版本的独立版本，全头文件构成，这样也可以确保kbengine不加入boost这样庞大的第三方库。

**Comment by kbengine** [comment]
主线程不是问题，本身就是采用单线程多进程架构，一个进程承受不住应该增加进程分担。
网络这块也是异步IO， linux epoll。

windows使用select，开发期使用无所谓，游戏上线应该在linux下。
