### ISSUE TITLE
There may be a error in the document

### ISSUE THREAD

**Issue by woshichuanqilz** [kbengine/kbengine#290]
There is a different to set the **lower_case_table_names** between windows and linux.

> Use lower_case_table_names=0 on Unix and lower_case_table_names=2 on Windows.

*quote link* : [mysql_link](http://dev.mysql.com/doc/refman/5.0/en/identifier-case-sensitivity.html)
---
But in the document it says that you should set ower_case_table_names=0. (If you use `0` , the mysql server will not start).

**Comment by kbengine** [comment]
SHA-1: 6ff7e50f78a1e89e820ace1c980a6d1d2020c47a

**Comment by kbengine** [comment]
https://github.com/kbengine/kbengine.github.com
SHA-1: 1fbc4b71517baad942224d323947490d9801122c

**Comment by kbengine** [comment]
Thank you for your reports!

**Comment by woshichuanqilz** [comment]
python 安装脚本也需要修改一下, 我暂时修改了那个判断值, 安装成功了
```python
				if lower_case_table_names != '2':  # 原本是0
					ERROR_MSG('mysql lower_case_table_names is not 2 in windows')
					config, cnf = getMysqlConfig()
					INFO_MSG('Attempt to modify the [%s]...' % cnf)
					config.set('mysqld', 'lower_case_table_names', '0')
					config.write(open(cnf, "w"))
					restartMsql()
					continue

```

**Comment by kbengine** [comment]
ok
