### ISSUE TITLE
how to set KBEngine use the mysql in vmware?

### ISSUE THREAD

**Issue by woshichuanqilz** [kbengine/kbengine#291]

**Comment by kbengine** [comment]
这个问题很难回答你，你的mysql可以在vmware中安装在windows或者linux上。
遇到mysql安装的问题可以咨询mysql社区或者google，KBE报出的问题你可以在http://bbs.kbengine.org/forum.php上搜索问题， 如果没有搜索到你可以将信息详细列出来咨询
