### ISSUE TITLE
guiconsole.exe缺失

### ISSUE THREAD

**Issue by snoworld888** [kbengine/kbengine#319]
kbe/tools/server/guiconsole/guiconsole.exe v0.8.1版本找不到

**Comment by W12S12E12** [comment]
for python s://mail.scipy.org/pipermail/ipython-user/2011-December/date.html#8844
check out the possible file .exe -run
//sourceforge.net/projects/py2exe/files/py2exe/0.6.9/

**Comment by kbengine** [comment]
编译了就有了。
