### ISSUE TITLE
OGREdemo需要检查

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#349]

**Comment by changxy2** [comment]
open_ssl 使用不能通过

**Comment by changxy2** [comment]
无法执行下去

**Comment by kbengine** [comment]
服务器引擎和服务器kbengine_demos_assets以及ogre项目全部都更新到最新提交再测试。
我已经测试通过。

注意删除你的系统环境变量， 不要设置系统环境变量， 服务器的启动脚本和客户端启动脚本都会自动设置， 只要你的文件夹目录结构按照ogre readme提示要求放置即可正常启动测试。
