### ISSUE TITLE
关于GUIConsole的调试功能

### ISSUE THREAD

**Issue by guihouchang** [kbengine/kbengine#362]
能否将调试功能直接添加的到对应的控制台上呢？
比如我想在cellapp中获取对象调试，直接就在cellapp控制台里进行debug，就像GUIConsole那样

**Comment by kbengine** [comment]
这个功能我已经考虑过， 不过后来放弃了， 放弃的原因是真正使用起来还是挺不方便，因为你需要从一堆窗口中找到cellapp窗口然后才能调试， 一下切换了焦点下次又需要找出窗口来。

新的版本增加了“Windows下支持启动参数以后台方式启动服务器”
https://github.com/kbengine/kbengine/issues/359

以后可以将所有的窗口都隐藏起来， 这样在win下会干净很多，此时使用用具会更高效。

**Comment by guihouchang** [comment]
目前0.8.10是不支持参数的对吧？请问0.9.0什么时候有release版本呢

**Comment by kbengine** [comment]
可能一个月左右

**Comment by guihouchang** [comment]
好的！
