### ISSUE TITLE
使用pyhon后写逻辑后，想复用原来c的一部分带，就在python调用import ctypes，就直接报错

### ISSUE THREAD

**Issue by situnan** [kbengine/kbengine#385]
INFO root [0x00000fe0] [2016-08-06 15:38:21,093] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 30 2016, 20:03:45) [MSC v.1900 64 bit (AMD64)])!
  INFO root [0x00000fe0] [2016-08-06 15:38:21,093] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000fe0] [2016-08-06 15:38:21,126] - loaded script:Player(1).
 ERROR root [0x00000fe0] [2016-08-06 15:38:21,145] - EntityDef::initialize: Could not load module[Hall]
 S_ERR root [0x00000fe0] [2016-08-06 15:38:21,149] - Traceback (most recent call last):
  File "E:/SourceCode/kbengine-0.8.10/assets/scripts/base\Hall.py", line 3, in <module>
    import ctypes
 S_ERR root [0x00000fe0] [2016-08-06 15:38:21,151] -   File "E:/SourceCode/kbengine-0.8.10/kbe/res/scripts/common/Lib\ctypes\__init__.py", line 435, in <module>
    pythonapi = PyDLL("python dll", None, _sys.dllhandle)
 S_ERR root [0x00000fe0] [2016-08-06 15:38:21,156] - AttributeError: 'module' object has no attribute 'dllhandle'
 ERROR root [0x00000fe0] [2016-08-06 15:38:21,157] - app::initialize(): initialization failed!

**Comment by kbengine** [comment]
KBE集成的python是静态编译，dll都不允许使用。
要么你把KBE的python改为动态库集成，或者把你的代码集成到KBE的c++层。

**Comment by kbengine** [comment]
linux下ctypes是可以使用的。
运营环境是在linux上的
