### ISSUE TITLE
降低向客户端send次数

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#389]
在极端的情况， 例如300人同屏互相pk，大部分原因是由于cellapp中位置更新的频率+属性广播和方法广播的频率加载一起造成send次数增多。

witness位置同步频率是恒定的， 而属性广播和方法广播的次数是有变数的， 只需要提供一种机制， 每次witness都产生一个待发送的bundle， 不管是位置同步还是属性广播和方法广播都向这个bundle中塞， 这样就可以减少转发次数，常规情况下应该能将send次数恒定在witness每帧同步次数。

**Comment by kbengine** [comment]
另一种方案是在baseapp中， 每个tick中产生的包并不马上send，而是累加到一个bundle中， 等一个tick结束后统一发送。

**Comment by Kiddinglife** [comment]
工作太忙 好久欣赏大神的代码了， 以下建议若不准确，望包涵。
1. bit packing 不知道你现在实现里用上了吗？
2. 位置更新时是否使用了delta value？
参考 http://fabiensanglard.net/doom3_documentation/DOOM-3-BFG-Technical-Note.pdf

**Comment by Kiddinglife** [comment]
另外，大神有时间可以思考下 actor 模式， 利用单机多核优势，
毕竟 production模式下 一台物理机只运行一个实例是最安全的做法，

**Comment by kbengine** [comment]
感谢你的建议， 建议我有空研究一下。

上面解决的不是流量问题， 是cpu消耗问题。
send调用次数越多消耗越大。

**Comment by kbengine** [comment]
仔细看了一下你的建议， 还是挺不错的。
不过KBE已经具备。

“另外，大神有时间可以思考下 actor 模式， 利用单机多核优势，
 毕竟 production模式下 一台物理机只运行一个实例是最安全的做法”

对与这个看法觉得只是一个可选的，多进程多线程都可以利用多核优势，2中模型都在较出名的产品上有应用，当然了解总是不吃亏的， 不过我已经了解过了：）。

**Comment by Kiddinglife** [comment]
“ 等一个tick结束后统一发送。”　ｔｉｃｋ时间不稳定，　若机器负载过重，ｒｅａｄ和ｗｒｉｔｅ比例严重失调，客户延迟会很高。
可能的优化：
每次发送时，检测距离上一次ｓｅｎｄ过了多长时间，　如果超过例如２０ｍｓ，就强制ｓｅｎｄ一次，

**Comment by kbengine** [comment]
单线程多进程自动负载均衡分布式模型不考虑机器负载过重情况，出现这种问题表示硬件和逻辑进程资源不足，应该开启更多进程共同负载。
负载过重无论如何客户都会感觉卡，计算量摆在那。

在kbe中一个逻辑tick时间超出有明确的警告性提示。

**Comment by kbengine** [comment]
准确说这种模型不考虑一帧耗完带来的延迟后果

**Comment by kbengine** [comment]
不过你的建议在服务器没有负荷的情况下对于极度要求实时性是有帮助的。

unreal4对于同步就分为了2种，一种是立即同步，一种是一帧同步。
或许可以提供这样一个配置。
