### ISSUE TITLE
关于kbengine 对比 bigworld 完整度

### ISSUE THREAD

**Issue by Mattosx** [kbengine/kbengine#394]
你好, 看了kbengine 觉得挺赞的, 想请问下 kbengine 是仿造 bigworld 架构来写的, 在对比bigworld 完整度上如何, 是否很多重要的模块和细节都已经没有遗漏了?

**Comment by kbengine** [comment]
是的，提炼bigworld思想来实现。
除了自动拆分space部分， 其他都已经完善并经过项目验证了。
而当前的游戏市场对于space拆分需求已经越来越小了，所以没有选择实现。

**Comment by Mattosx** [comment]
你说的space 自动拆分, 是无缝地图的对吧? 一个区域人太多, 然后自动拆分到多个 cellapp 上的?

**Comment by kbengine** [comment]
是的

**Comment by Mattosx** [comment]
是否可以用 cmake 组织工程哈？ 这样就cmake 可以跨平台，这样可以根据不同平台ide 生成不同的工程，目前在mac linux 下看代码不容易。

**Comment by kbengine** [comment]
https://github.com/kbengine/kbengine/issues/117

**Comment by heijing-iw7** [comment]
> 你说的space 自动拆分, 是无缝地图的对吧? 一个区域人太多, 然后自动拆分到多个 cellapp 上的?
> 而当前的游戏市场对于space拆分需求已经越来越小了，所以没有选择实现。
我是请问一下kbengine的，这个cellapp拆分不是挺有必要的么。。为啥说需求越来越小了

**Comment by hsz8250** [comment]
没有做动态拆分，但是针对无缝地图的边缘复制和同步是否有实现呢？
