### ISSUE TITLE
Cryengine Support 

### ISSUE THREAD

**Issue by dregen** [kbengine/kbengine#417]
Would be great if this worked for Cryengine also.

**Comment by HeadClot** [comment]
The next version of cry engine should have some form of plugin support which will allow people write plugins Cryengine V. That is if it does not get delayed.

**Comment by kbengine** [comment]
Is currently developing ue4 plug-in, Cryengine is also relatively good engine, but there is no plan to support it.

If time is enough, it could be supported.
