### ISSUE TITLE
KBE支持直接用C++编写服务端游戏逻辑吗？

### ISSUE THREAD

**Issue by duuyia** [kbengine/kbengine#418]
问题：
支持使用c++编写服务端逻辑不？
直接使用c++我想性能会更好一点，而且不想再去搞python！
如果不支持，那是否有考虑做成支持c++编写游戏逻辑层呢？

**Comment by kbengine** [comment]
性能肯定会更高，但开发效率会大大降低，普通团队用c++开发复杂项目稳定性也会大大降低。
kbe已经将复杂计算封装到c++了，python主要是组织逻辑，效率比纯python项目高很多。

如果一定要在c++开发游戏，你在引擎源码扩展就好了。

**Comment by duuyia** [comment]
确实有这个想法，但框架太大，没有教程切入有点费时和困难
