### ISSUE TITLE
方便出一个客户端lua版吗？

### ISSUE THREAD

**Issue by isghost** [kbengine/kbengine#423]
U3D由于有热更的需求，开发基本也是用的lua。
cocos2d-x 虽然官方大力支持js发展(已经好几年，内部**)，但一点起色没有，AppStore排行榜上用cocos2dx的，用的几乎清一色的Lua。js都是一些棋牌类游戏开发。

**Comment by kbengine** [comment]
你可以参考https://github.com/liuxq/StriveGame

**Comment by jyunfan2015** [comment]
我是这样看待lua嵌入unity项目的，因为ios和android安全性的原因，限制unity的热更新项目。所以unity官方本身不做热更新这款，理论上unity官方可以实现热更新，但是需要苹果和谷歌的配合，即修改操作系统的代码，但是这样做几乎不可能。所以unity项目的热更新都是第三方程序员在做的框架比如ulua。但是用了这些东西之后，因为想要热更新，马上增加了客户端unity项目的代码复杂度，代码的复杂度增加，可读性变得非常差，维护上就更困难一些。国内的大游戏公司似乎对unity客户端手游项目热更新并不太看重，似乎重要版本的升级几乎要求玩家下载合适的版本，因为这样做了之后给游戏玩家一定的补偿，比如送金币道具之类，而且手机上往往有应用商店，可以应用更新，其实更新的过程还很便捷，点击应用商店里某个游戏的更新就升级了，也没有麻烦玩家下载和安装，对游戏开发者来说这样的选择也没有增加项目的代码复杂度。这似乎是一个双赢的选择。

**Comment by isghost** [comment]
@jyunfan2015  现在排行榜上的游戏基本都有热更新，我目前玩到的只有一款炉石传说（暴雪）没有。整包更新，对于用户的流失，实在是巨大。你能举几个排行榜上没有热更新的游戏吗？我去下载参考参考
