### ISSUE TITLE
Compiling issues, char narrowing

### ISSUE THREAD

**Issue by jedStevens** [kbengine/kbengine#425]
locationinfo.cpp: In member function 'void log4cxx::spi::LocationInfo::write(log4cxx::helpers::ObjectOutputStream&, log4cxx::helpers::Pool&) const':
    locationinfo.cpp:163:21: error: narrowing conversion of '237' from 'int' to 'char' inside { } [-Wnarrowing]
              0x78, 0x70 };
                         ^
    locationinfo.cpp:163:21: error: narrowing conversion of '153' from 'int' to 'char' inside { } [-Wnarrowing]
    locationinfo.cpp:163:21: error: narrowing conversion of '187' from 'int' to 'char' inside { } [-Wnarrowing]
    locationinfo.cpp:163:21: error: narrowing conversion of '225' from 'int' to 'char' inside { } [-Wnarrowing]
    locationinfo.cpp:163:21: error: narrowing conversion of '145' from 'int' to 'char' inside { } [-Wnarrowing]
    locationinfo.cpp:163:21: error: narrowing conversion of '165' from 'int' to 'char' inside { } [-Wnarrowing]

using the compiling commands from [here](http://kbengine.org/docs/build.html) gives me this error.

64 Bit Manjaro Linux, GCC 6.2.1, any ideas on how to get around this or is this a bug?

**Comment by kbengine** [comment]
This may be a high version of the GCC will report the error.
	
Error occurred in the log4cxx source code (locationinfo.cpp:163:21)
`        char prolog[] = {
         0x72, 0x00, 0x21, 0x6F, 0x72, 0x67, 0x2E, 
         0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2E, 0x6C, 
         0x6F, 0x67, 0x34, 0x6A, 0x2E, 0x73, 0x70, 0x69, 
         0x2E, 0x4C, 0x6F, 0x63, 0x61, 0x74, 0x69, 0x6F, 
         0x6E, 0x49, 0x6E, 0x66, 0x6F, 0xED, 0x99, 0xBB, 
         0xE1, 0x4A, 0x91, 0xA5, 0x7C, 0x02, 0x00, 0x01, 
         0x4C, 0x00, 0x08, 0x66, 0x75, 0x6C, 0x6C, 0x49, 
         0x6E, 0x66, 0x6F, 
            0x74, 0x00, 0x12, 0x4C, 0x6A, 
                0x61, 0x76, 0x61, 0x2F, 0x6C, 0x61, 0x6E, 0x67, 
                0x2F, 0x53, 0x74, 0x72, 0x69, 0x6E, 0x67, 0x3B,
         0x78, 0x70 };`

	
Some numbers overflow the char, but this should not be a coding error.
Can modify the value of the overflow：

`	char prolog[] = {
		(char)0x72, (char)0x00, (char)0x21, (char)0x6F, (char)0x72, (char)0x67, (char)0x2E,
		(char)0x61, (char)0x70, (char)0x61, (char)0x63, (char)0x68, (char)0x65, (char)0x2E, (char)0x6C,
		(char)0x6F, (char)0x67, (char)0x34, (char)0x6A, (char)0x2E, (char)0x73, (char)0x70, (char)0x69,
		(char)0x2E, (char)0x4C, (char)0x6F, (char)0x63, (char)0x61, (char)0x74, (char)0x69, (char)0x6F,
		(char)0x6E, (char)0x49, (char)0x6E, (char)0x66, (char)0x6F, (char)0xED, (char)0x99, (char)0xBB,
		(char)0xE1, (char)0x4A, (char)0x91, (char)0xA5, (char)0x7C, (char)0x02, (char)0x00, (char)0x01,
		(char)0x4C, (char)0x00, (char)0x08, (char)0x66, (char)0x75, (char)0x6C, (char)0x6C, (char)0x49,
		(char)0x6E, (char)0x66, (char)0x6F,
		(char)0x74, (char)0x00, (char)0x12, (char)0x4C, (char)0x6A,
		(char)0x61, (char)0x76, (char)0x61, (char)0x2F, (char)0x6C, (char)0x61, (char)0x6E, (char)0x67,
		(char)0x2F, (char)0x53, (char)0x74, (char)0x72, (char)0x69, (char)0x6E, (char)0x67, (char)0x3B,
		(char)0x78, (char)0x70 };`

**Comment by jedStevens** [comment]
Is there no way to just use the recommended compiler version?

And I believe that this fix will also fail in other places for similar reasons but I am recompiling now to find out.

**Comment by jedStevens** [comment]
loggingevent.cpp: In static member function 'static void log4cxx::spi::LoggingEvent::writeProlog(log4cxx::helpers::ObjectOutputStream&, log4cxx::helpers::Pool&)':
    loggingevent.cpp:292:26: error: narrowing conversion of '243' from 'int' to 'char' inside { } [-Wnarrowing]
             0x3B, 0x78, 0x70 };
                          ^
    loggingevent.cpp:292:26: error: narrowing conversion of '242' from 'int' to 'char' inside { } [-Wnarrowing]
    loggingevent.cpp:292:26: error: narrowing conversion of '185' from 'int' to 'char' inside { } [-Wnarrowing]
    loggingevent.cpp:292:26: error: narrowing conversion of '181' from 'int' to 'char' inside { } [-Wnarrowing]

I am getting more narrowing errors.

I think this should be solvable with `-Wno-narrowing` but I am unsure how to add this flag in the large structure of make files.

**Comment by kbengine** [comment]
I will use a high version of GCC test.
The current you can use a GCC4.4 ~ 4.5

**Comment by jedStevens** [comment]
What is the best way to run the compilation with GCC4.4~4.5?

**Comment by kbengine** [comment]
The recommended way is:
centos5.5~6.0 and GCC4.4~4.5

**Comment by kbengine** [comment]
Add -Wno-narrowing, you can look at 
\kbengine\kbe\src\lib\dependencies\log4cxx\(Makefile、configure)
CXXFLAGS

**Comment by pluton05** [comment]
i have the same problem,i use ubuntu 16.04.

**Comment by kbengine** [comment]
GCC 6.2 test passed.
You can update the kbengine development version.

Ubuntu can also.
