### ISSUE TITLE
baseapp::loginBaseapp 时 ptinfos->deadline检查问题

### ISSUE THREAD

**Issue by vvfly** [kbengine/kbengine#439]
RT
if (ptinfos->deadline > 0 && ::time(NULL) - ptinfos->deadline <= 0)
{
	loginBaseappFailed(pChannel, accountName, SERVER_ERR_ACCOUNT_DEADLINE);
	return;
}
ptinfos->deadline 是uint64
time_t 是int64

**Comment by kbengine** [comment]
deadline 存储的实际就是time(NULL)， time_t在不同平台上是不一样的，为了统一进程间无缝通讯，使用了统一的存储类型。

这里并没有问题

**Comment by kbengine** [comment]
那个运算会隐式转换
