### ISSUE TITLE
mac os make error

### ISSUE THREAD

**Issue by liuxm6** [kbengine/kbengine#441]
`sigar.c:1123:12: warning: 'utmp' is deprecated [-Wdeprecated-declarations]
    struct utmp ut;
           ^
/usr/include/utmp.h:92:8: note: 'utmp' has been explicitly marked deprecated here
struct utmp {
       ^
sigar.c:1149:30: error: no member named 'ut_user' in 'struct utmp'
        WHOCPY(who->user, ut.ut_user);
                          ~~ ^
sigar.c:1071:25: note: expanded from macro 'WHOCPY'
    SIGAR_SSTRCPY(dest, src); \
                        ^~~
/Users/liuxm/Documents/work/git/kbengine/kbe/src/lib/dependencies/sigar/linux/sigar_private.h:101:25: note: expanded from macro 'SIGAR_SSTRCPY'
    SIGAR_STRNCPY(dest, src, sizeof(dest))
                        ^~~
/Users/liuxm/Documents/work/git/kbengine/kbe/src/lib/dependencies/sigar/linux/sigar_private.h:95:19: note: expanded from macro 'SIGAR_STRNCPY'
    strncpy(dest, src, len); \
                  ^~~
/usr/include/secure/_string.h:119:34: note: expanded from macro 'strncpy'
  __builtin___strncpy_chk (dest, src, len, __darwin_obsz (dest))
                                 ^~~
sigar.c:1149:30: error: no member named 'ut_user' in 'struct utmp'
        WHOCPY(who->user, ut.ut_user);
                          ~~ ^
sigar.c:1072:16: note: expanded from macro 'WHOCPY'
    if (sizeof(src) < sizeof(dest)) \
               ^~~
sigar.c:1149:30: error: no member named 'ut_user' in 'struct utmp'
        WHOCPY(who->user, ut.ut_user);
                          ~~ ^
sigar.c:1073:21: note: expanded from macro 'WHOCPY'
        dest[sizeof(src)] = '\0'
                    ^~~
sigar.c:1474:21: error: use of undeclared identifier 'SIOCGARP'
    if (ioctl(sock, SIOCGARP, &areq) < 0) {
                    ^
1 warning and 4 errors generated.
make[2]: *** [Hybrid64/sigar.o] Error 1
make[1]: *** [all] Error 2`

**Comment by kbengine** [comment]
当前不支持mac os编译。
