### ISSUE TITLE
坐标系统，同位置下节点级别排序

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#464]

**Comment by ljporljp** [comment]
能解释下这个功能么，看起来可能会加快一下索引速度？

**Comment by kbengine** [comment]
只是解决一个重叠时优先级的问题。 不会加快速度

**Comment by kebiao** [comment]
https://bbs.comblockengine.com/forum.php?mod=viewthread&tid=6453#lastpost

**Comment by kebiao** [comment]
修正
