### ISSUE TITLE
*(CLOSE)[WebConsole]Healp me please!

### ISSUE THREAD

**Issue by cshard447** [kbengine/kbengine#468]
Hello, I have this problem
When writing KBE paths, why is there nothing in the management clusters
User Settings
![screenshot_2](https://cloud.githubusercontent.com/assets/7473900/25398071/4d055b4c-29f3-11e7-9ac0-72378f5853b1.png)
Kbe paths
![screenshot_3](https://cloud.githubusercontent.com/assets/7473900/25398099/6b1f5254-29f3-11e7-8599-f1aa67fcbdbf.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/7473900/25398100/6b1fd0a8-29f3-11e7-85a0-1cee129e0088.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/7473900/25398101/6b21016c-29f3-11e7-8bb2-10177cf26788.png)
Cluster
![screenshot_4](https://cloud.githubusercontent.com/assets/7473900/25398118/7ae99b04-29f3-11e7-8a75-6d2ab23631b2.png)

Thanks for the help! 👍

**Comment by acatadog** [comment]
KBE_ROOT、KBE_RES_PATH、KBE_BIN_PATH是否设置与是否能发现服务器无关，它们只会影web console是否能正确的启动KBEngine的服务器组件（baseapp、cellapp等）。
从截图来看，要么是服务器的machine进程未启动（web console几乎所有的操作都依赖machine进程），如果确实未启动，请手动启动machine进程。如果已经确认启动了machine进程，请检查防火墙等，是否禁止了udp 20086的访问。

**Comment by cshard447** [comment]
thanks!
WebConsole Work!
![image](https://cloud.githubusercontent.com/assets/7473900/25417408/8b302bbe-2a4c-11e7-9af9-fbf85b84158a.png)
