### ISSUE TITLE
[WebConsole](SpaceViewer)

### ISSUE THREAD

**Issue by cshard447** [kbengine/kbengine#469]
Hi, help me please!
The web console does not work Space Weaver
![image](https://cloud.githubusercontent.com/assets/7473900/25417497/356fa230-2a4d-11e7-9894-d06c968a68b0.png)

![image](https://cloud.githubusercontent.com/assets/7473900/25417472/0690b09e-2a4d-11e7-9fbb-e2d0d8c6af87.png)

And the components do not start
![image](https://cloud.githubusercontent.com/assets/7473900/25417529/5dfec21c-2a4d-11e7-8ccb-fb6c5ffd9a1e.png)
![image](https://cloud.githubusercontent.com/assets/7473900/25417536/6a2eeb34-2a4d-11e7-894d-d89d1f17b9d1.png)

```
Environment:


Request Method: POST
Request URL: http://5.39.14.148:8000/wc/components/run

Django Version: 1.4.22
Python Version: 2.7.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'WebConsole')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/root/kbengine/kbe/tools/server/webconsole/WebConsole/auth.py" in wrapper
  25. 		return func( request, *args, **kws )
File "/root/kbengine/kbe/tools/server/webconsole/WebConsole/views.py" in components_run
  265. 				components.startServer( componentType, cid, gus, targetMachine, kbe_root, kbe_res_path, kbe_bin_path )
File "/root/kbengine/kbe/tools/server/pycommon/Machines.py" in startServer
  243. 		msg.writeString(kbe_root)
File "/root/kbengine/kbe/tools/server/pycommon/MessageStream.py" in writeString
  212. 		assert isinstance(val, (bytes, str, unicode)), "value type not match! current val type = %s" % type(val)

Exception Type: AssertionError at /wc/components/run
Exception Value: value type not match! current val type = <type 'unicode'>
```

**Comment by acatadog** [comment]
Django Version: 1.4.22……
建议你们在Django-1.8.9上测试，我没有在1.4.22这个如此低的版本下运行过，所以我不能保证在这个版本下web console的功能可以正确执行。

**Comment by cshard447** [comment]
How do I update django?

**Comment by acatadog** [comment]
https://github.com/kbengine/kbengine/tree/master/kbe/tools/server/django_packages
这下面有相关的django包，1.6或1.8，随便选一个把包解压缩，进入解开的目录，执行python setup.py install——在这之前，请自己想办法把原来的django 1.4.22从现在的python上删除，我不知道你们实际的运行环境，所以删除旧包只能靠你自己

**Comment by cshard447** [comment]
django updated...
Environment:


Request Method: POST
Request URL: http://5.39.14.148:8000/wc/components/run

Django Version: 1.8.9
Python Version: 2.7.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'WebConsole')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/Django-1.8.9-py2.7.egg/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/root/kbengine/kbe/tools/server/webconsole/WebConsole/auth.py" in wrapper
  25. 		return func( request, *args, **kws )
File "/root/kbengine/kbe/tools/server/webconsole/WebConsole/views.py" in components_run
  265. 				components.startServer( componentType, cid, gus, targetMachine, kbe_root, kbe_res_path, kbe_bin_path )
File "/root/kbengine/kbe/tools/server/pycommon/Machines.py" in startServer
  243. 		msg.writeString(kbe_root)
File "/root/kbengine/kbe/tools/server/pycommon/MessageStream.py" in writeString
  212. 		assert isinstance(val, (bytes, str, unicode)), "value type not match! current val type = %s" % type(val)

Exception Type: AssertionError at /wc/components/run
Exception Value: value type not match! current val type = <type 'unicode'>

**Comment by cshard447** [comment]
my system
OC: Debian 7
python version: 2.7

**Comment by acatadog** [comment]
修正：/root/kbengine/kbe/tools/server/pycommon/MessageStream.py
删除第13行：unicode = str
试试

**Comment by cshard447** [comment]
![image](https://cloud.githubusercontent.com/assets/7473900/25419728/fefcb3b8-2a5c-11e7-9323-85253191f45d.png)
![image](https://cloud.githubusercontent.com/assets/7473900/25419733/0abc399e-2a5d-11e7-9b7e-7ebbf3f05d05.png)

**Comment by acatadog** [comment]
可以考虑多“refresh”几次，如果不行，说明很可能是KBEngine服务器出问题了，考虑检查一下服务器的日志，看是否有错误，检查一下machine进程是否存在，如果确定machine进程存在，可以点击第二项“All status daemons”看里面是否能显示出相关的machine进程

**Comment by acatadog** [comment]
另外，前面MessageStream.py异常的错误已修正，可以考虑更新

**Comment by cshard447** [comment]
![image](https://cloud.githubusercontent.com/assets/7473900/25420077/01598b02-2a5f-11e7-97a9-3b251626dcd3.png)
machine log
```
root/kbengine/kbe/, KBE_RES_PATH=/root/kbengine/kbe/res/, KBE_BIN_PATH=/root/kbengine/kbe/bin/
  INFO root [2017-04-26 08:04:05,483] - Machine::startLinuxProcess: UID 0 execing '/root/kbengine/kbe/bin/cellapp', cid = 501577751570002, gus = 502
 DEBUG root [2017-04-26 08:04:05,487] - SignalHandlers: receive sigNum SIGCHLD.
 DEBUG root [2017-04-26 08:04:05,487] - SignalHandlers::process: sigNum SIGCHLD handle.
  INFO root [2017-04-26 08:04:06,689] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:35088/0/0/0 timed out.
  INFO root [2017-04-26 08:04:06,790] - Machine::onQueryAllInterfaceInfos[127.0.0.1:55261/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
  INFO root [2017-04-26 08:04:08,694] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:47452/0/0/0 timed out.
  INFO root [2017-04-26 08:04:08,794] - Machine::onQueryAllInterfaceInfos[127.0.0.1:46544/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
  INFO root [2017-04-26 08:04:10,698] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:51660/0/0/0 timed out.
  INFO root [2017-04-26 08:04:10,799] - Machine::onQueryAllInterfaceInfos[127.0.0.1:53197/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
  INFO root [2017-04-26 08:04:12,703] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:42603/0/0/0 timed out.
  INFO root [2017-04-26 08:04:12,803] - Machine::onQueryAllInterfaceInfos[127.0.0.1:60250/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
  INFO root [2017-04-26 08:04:14,707] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:54477/0/0/0 timed out.
  INFO root [2017-04-26 08:04:14,807] - Machine::onQueryAllInterfaceInfos[127.0.0.1:48981/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
  INFO root [2017-04-26 08:04:16,711] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:51171/0/0/0 timed out.
  INFO root [2017-04-26 08:04:16,812] - Machine::onQueryAllInterfaceInfos[127.0.0.1:59466/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
  INFO root [2017-04-26 08:04:18,716] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:41845/0/0/0 timed out.
  INFO root [2017-04-26 08:04:18,816] - Machine::onQueryAllInterfaceInfos[127.0.0.1:50257/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
  INFO root [2017-04-26 08:04:20,720] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:54215/0/0/0 timed out.
  INFO root [2017-04-26 08:04:20,821] - Machine::onQueryAllInterfaceInfos[127.0.0.1:54973/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
  INFO root [2017-04-26 08:04:22,724] - ServerApp::onChannelTimeOut: Channel 127.0.0.1:59471/0/0/0 timed out.
  INFO root [2017-04-26 08:04:22,825] - Machine::onQueryAllInterfaceInfos[127.0.0.1:48456/0/0/0]: uid:0, username:WebConsole, finderRecvPort:45992.
```

**Comment by kbengine** [comment]
Logs file can be attached?

**Comment by cshard447** [comment]
[machine.txt](https://github.com/kbengine/kbengine/files/957416/machine.txt)

**Comment by acatadog** [comment]
![image](https://cloud.githubusercontent.com/assets/4627767/25420937/1cd1be62-2a8d-11e7-9dfd-2db011349c36.png)
点击红框处的地址，看在下面是否能列出其它的组件

**Comment by cshard447** [comment]
I clicked, but the list is empty
![image](https://cloud.githubusercontent.com/assets/7473900/25421011/7716c784-2a63-11e7-8a57-9c536a3b385e.png)

**Comment by acatadog** [comment]
这说明web console从machine中没有得到有用的数据，你确定服务器中除了machine以外，还有其它的KBEngine组件吗？如cellapp、cellapmpr、dbmgr等等

**Comment by cshard447** [comment]
no
Through the Linux console, I can start the server
And through WebConsole there is no

**Comment by acatadog** [comment]
我现在也没有什么想法，也许你可以看看web console是否有输出什么错误日志到linux console，又或修改KBESettings/settings.py，把USE_MACHINES_BUFFER参数设置为False以后重新运行web console试试，看看是否有更多的提示出现在web上或出现在linux console上面。

**Comment by cshard447** [comment]
When I click on SpaseViewer
The Linux console displays errors
![image](https://cloud.githubusercontent.com/assets/7473900/25421939/ba6f9cb4-2a67-11e7-983c-8df59d4f2bf6.png)

**Comment by acatadog** [comment]
这是已知的错误，它并不影响使用

**Comment by acatadog** [comment]
![image](https://cloud.githubusercontent.com/assets/4627767/25422741/70e68ed6-2a94-11e7-834f-b68687d5be84.png)
反而是这个错误，你可以查一下日志，看看它是否来自cellappmgr，如果是来自cellappmgr，那说明cellappmgr并不认识这个消息如果是这样，那说明你的服务器似乎少了点什么

**Comment by acatadog** [comment]
另外，只有ServerControl正常的情况下，SpaceView才有可能正常运行，你现在的ServerControl正常了吗？

**Comment by cshard447** [comment]
Can the problem in this?
![image](https://cloud.githubusercontent.com/assets/7473900/25423443/5f94ea50-2a6d-11e7-8039-80134ede4b02.png)

**Comment by kbengine** [comment]
error：50003
update kbengine!

**Comment by kbengine** [comment]
1: update kbengine
2: You can delete all the logs in the current logs folder, and then run the server again.
Logs files can be attached?

**Comment by cshard447** [comment]
i update kbe and run webconsole
Environment:


Request Method: POST
Request URL: http://5.39.14.148:8000/wc/components/run

Django Version: 1.8.9
Python Version: 2.7.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'WebConsole')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/Django-1.8.9-py2.7.egg/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/root/kbengine/kbe/tools/server/webconsole/WebConsole/auth.py" in wrapper
  25. 		return func( request, *args, **kws )
File "/root/kbengine/kbe/tools/server/webconsole/WebConsole/views.py" in components_run
  265. 				components.startServer( componentType, cid, gus, targetMachine, kbe_root, kbe_res_path, kbe_bin_path )
File "/root/kbengine/kbe/tools/server/pycommon/Machines.py" in startServer
  243. 		msg.writeString(kbe_root)
File "/root/kbengine/kbe/tools/server/pycommon/MessageStream.py" in writeString
  212. 		assert isinstance(val, (bytes, str, unicode)), "value type not match! current val type = %s" % type(val)

Exception Type: AssertionError at /wc/components/run
Exception Value: value type not match! current val type = <type 'unicode'>

**Comment by cshard447** [comment]
kbe_pathes
![image](https://cloud.githubusercontent.com/assets/7473900/25425398/86c0e262-2a74-11e7-93c2-8bc0c7450a2e.png)

**Comment by cshard447** [comment]
I managed to fix the server startup via WebConsole
But SpaseViever does not work as before ..

**Comment by cshard447** [comment]
![image](https://cloud.githubusercontent.com/assets/7473900/25427533/8bef0bae-2a7b-11e7-84ec-d6da850a73cd.png)

**Comment by cshard447** [comment]
[cellappmgr.2017-04-26.txt](https://github.com/kbengine/kbengine/files/957931/cellappmgr.2017-04-26.txt)

**Comment by cshard447** [comment]
If I understand correctly, it can not get a list of spaces

**Comment by acatadog** [comment]
我修正了一个版本，如果你有需要的话可以试一下。
但这个得等KBE合并到其主分支上以后你才能更新。

**Comment by kbengine** [comment]
Already merged!

**Comment by cshard447** [comment]
Guys, should I recompile the engine?

**Comment by kbengine** [comment]
No

**Comment by cshard447** [comment]
![image](https://cloud.githubusercontent.com/assets/7473900/25469763/000234ca-2b27-11e7-8599-90b54a3d2aaa.png)

**Comment by kbengine** [comment]
这个问题可能需要一些时间修复了，请等待修正。

**Comment by cshard447** [comment]
Ok, I'll wait for the update

**Comment by darkwere** [comment]
cshard447 - It was you to translate webconsole to English language?

**Comment by cshard447** [comment]
Yes

**Comment by darkwere** [comment]
Can you share it with me?
I would be very grateful!

**Comment by cshard447** [comment]
https://drive.google.com/file/d/0ByXpHqLu60YNS3lkdG9ESW11ZWs/view?usp=sharing
Extract to folder "kbengine/kbe/tools/server/webconsole/templates" with the replacement of files
;)

**Comment by darkwere** [comment]
Thanks a lot, man!
You really great!

**Comment by darkwere** [comment]
Hey, man, can I have you contact? Wanna ask you pair of questions!

**Comment by cshard447** [comment]
Yes, my skype:  andfox447

**Comment by acatadog** [comment]
![image](https://cloud.githubusercontent.com/assets/4627767/26233018/e70adc98-3c8c-11e7-9b34-46603795a9f0.png)
请等待开发者合并更新
需要重新编译服务器端

**Comment by kbengine** [comment]
Already merged!

**Comment by cshard447** [comment]
dont work spaceview
last update
![image](https://cloud.githubusercontent.com/assets/7473900/26285142/6e6f7628-3e52-11e7-8786-4c35077c016b.png)
![image](https://cloud.githubusercontent.com/assets/7473900/26285147/827ce06a-3e52-11e7-8739-486fbe9ff4c9.png)

**Comment by acatadog** [comment]
从日志来看，应该是你的服务器不匹配，你的服务器并不认得msgID=50003的消息

**Comment by kbengine** [comment]
Update kbengine to latest(Development version)

**Comment by kbengine** [comment]
Can be closed?

**Comment by cshard447** [comment]
Yes)
