### ISSUE TITLE
[Help]Avatar.model

### ISSUE THREAD

**Issue by cshard447** [kbengine/kbengine#470]
I tried to add a field for the character model
Help please solve the problem
Mysql Table
![image](https://cloud.githubusercontent.com/assets/7473900/25453343/3574d1f4-2ad1-11e7-8022-4e770523fec5.png)

scripts/base/Account.py
![image](https://cloud.githubusercontent.com/assets/7473900/25452851/b11523e2-2acf-11e7-9a2b-e84c48a7ee6c.png)
![image](https://cloud.githubusercontent.com/assets/7473900/25453129/95a7b362-2ad0-11e7-89ed-edad470f35f0.png)
scripts/entity_defs/Account.def
![image](https://cloud.githubusercontent.com/assets/7473900/25452904/e228521a-2acf-11e7-8af7-3c3b985c7aaa.png)
scripts/entity_defs/alias.xml
![image](https://cloud.githubusercontent.com/assets/7473900/25452952/06207f30-2ad0-11e7-9728-d33b7dba31bd.png)
scripts/entity_defs/Avatar.def
![image](https://cloud.githubusercontent.com/assets/7473900/25452998/2b367220-2ad0-11e7-9a3a-3f510d976200.png)
scripts/user_type/AVATAR_INFOS.py
![image](https://cloud.githubusercontent.com/assets/7473900/25453037/4c45d834-2ad0-11e7-97b7-86a71f7113e6.png)

SERVER_LOGS
baseapp
![image](https://cloud.githubusercontent.com/assets/7473900/25453164/b44685b4-2ad0-11e7-8581-27a64f3df8c4.png)
![image](https://cloud.githubusercontent.com/assets/7473900/25453205/c9d1dc3a-2ad0-11e7-896f-7cb5245212b6.png)

Tell me, please, what I'm wrong about ...
Thanks!!

**Comment by kbengine** [comment]
Model is the property of cell.
Account.model is accessing the base property.

**Comment by cshard447** [comment]
Can you tell me how to do it better?

**Comment by cshard447** [comment]
When creating a character, I specify the model and click the button to create
But in the database it does not fill this field (sm_model)

**Comment by kbengine** [comment]
First you need to know your needs.
Model is used in cellapp on the entity or baseapp base.
The base attribute is defined as <Flags> BASE </ Flags>, just like roleType.
The Flags of the cell attribute contains CELL_PUBLIC, CELL_PRIVATE, ALL_CLIENTS, etc.

You need to know what they mean,
And then decide how to do it.

**Comment by kbengine** [comment]
You can define an attribute as <Flags> BASE </ Flags>

**Comment by cshard447** [comment]
I still can not write data to the database table...
Can you give an example?

**Comment by cshard447** [comment]
![image](https://cloud.githubusercontent.com/assets/7473900/25476027/72fb0bcc-2b41-11e7-8e17-cf64874a7f94.png)
![image](https://cloud.githubusercontent.com/assets/7473900/25476033/7c4f6286-2b41-11e7-8ddc-66ee60477835.png)

**Comment by kbengine** [comment]
![1](https://cloud.githubusercontent.com/assets/2336717/25476170/e86744f0-2b6b-11e7-83c7-ff09ddeb4dec.png)

![2](https://cloud.githubusercontent.com/assets/2336717/25476157/deee18fe-2b6b-11e7-847c-bd9c339f9acf.png)
![3](https://cloud.githubusercontent.com/assets/2336717/25476158/e0434d8c-2b6b-11e7-8c1d-f852b62ff853.png)

[kbengine_demos_assets.zip](https://github.com/kbengine/kbengine/files/961043/kbengine_demos_assets.zip)

**Comment by kbengine** [comment]
In the base want to visit this property:
Avatar.cellData ["model"]

**Comment by cshard447** [comment]
##SERVER LOGS
![image](https://cloud.githubusercontent.com/assets/7473900/25477393/0c022fa4-2b46-11e7-8539-620e5b2cf590.png)
![image](https://cloud.githubusercontent.com/assets/7473900/25477402/144c24f8-2b46-11e7-94ab-18836e0841aa.png)
![image](https://cloud.githubusercontent.com/assets/7473900/25477421/20c761ac-2b46-11e7-90fc-aaff5fa62bbc.png)

##Game Client modify code
![image](https://cloud.githubusercontent.com/assets/7473900/25477526/7e7bd058-2b46-11e7-9995-2b315cd843b1.png)
![image](https://cloud.githubusercontent.com/assets/7473900/25477594/bf0d5fb0-2b46-11e7-9f04-bb7503c33cab.png)

![image](https://cloud.githubusercontent.com/assets/7473900/25477685/0b2878f8-2b47-11e7-9666-4fb31d161b0e.png)
##After clicking the CreateAvatar button
![image](https://cloud.githubusercontent.com/assets/7473900/25477700/192d7818-2b47-11e7-9a19-09e78864f76c.png)

##Server code
Account.py
![image](https://cloud.githubusercontent.com/assets/7473900/25477783/657a8580-2b47-11e7-8545-7349e4f9f2cb.png)

Avatar.def
![image](https://cloud.githubusercontent.com/assets/7473900/25477841/882a5d76-2b47-11e7-9514-bd2e983863dc.png)

**Comment by cshard447** [comment]
Thanks!
Work
The truth is now I do not know how to synchronize the model between the players and get it from the database

**Comment by kbengine** [comment]
1: model should be defined as ALL_CLIENTS.
So that you can automatically synchronize to each client.
You can in any and the player related to the client to find the player entity, get model.
Refer to modelID in Demo

2: attributes can be automatically archived,
After the entity is loaded from the database, the data is automatically set to avatar.model

**Comment by cshard447** [comment]
Many thanks for your help!
