### ISSUE TITLE
[Spaces]Help!

### ISSUE THREAD

**Issue by cshard447** [kbengine/kbengine#476]
Help, I can not understand where is the standard ID space when you create a character.

**Comment by kbengine** [comment]
Reference demo:
1: https://github.com/kbengine/kbengine_demos_assets/blob/master/scripts/base/Account.py
def reqCreateAvatar(self, roleType, name):
Select the birth scene (spaceUType)

2:https://github.com/kbengine/kbengine_demos_assets/blob/master/scripts/base/interfaces/Teleport.py
KBEngine.globalData["Spaces"].loginToSpace(self, self.spaceUTypeB, {})
Avatar to create a scene after landing.

**Comment by cshard447** [comment]
Thanks!
