### ISSUE TITLE
[NAVMESH]Help!

### ISSUE THREAD

**Issue by cshard447** [kbengine/kbengine#477]
Hello
When I created it navmesh and placed it on the server
Such monsters do not see the landscape
 #Video
> (https://youtu.be/3MbS8mR8w-I)

Help me please!

**Comment by cshard447** [comment]
cellapp LOGS
![image](https://cloud.githubusercontent.com/assets/7473900/25587162/77240eca-2eab-11e7-9665-8ce3b31dbe9b.png)

**Comment by kbengine** [comment]
1:Whether the server has addSpaceGeometryMapping?
https://github.com/kbengine/kbengine_demos_assets/blob/master/scripts/cell/Space.py#L20

2: Does the client handle this event?
https://github.com/kbengine/kbengine_unity3d_warring/blob/master/Assets/scripts/world/KBEEventProc.cs#L42

**Comment by kbengine** [comment]
After the server executes addSpaceGeometryMapping, space loads navmesh and the navigate API will depend on navmesh.

**Comment by cshard447** [comment]
![image](https://cloud.githubusercontent.com/assets/7473900/25609902/cfa93cb8-2f29-11e7-808e-f9fe68de4cae.png)

**Comment by kbengine** [comment]
Why 2 times "addspacegeometrymapping"?

**Comment by cshard447** [comment]
This is my mistake, until it changes
Maybe I'm doing something wrong in the client?
![image](https://cloud.githubusercontent.com/assets/7473900/25610140/c36d7f9e-2f2a-11e7-8377-f94c6ac7baab.png)

![image](https://cloud.githubusercontent.com/assets/7473900/25609990/1e771c98-2f2a-11e7-829c-4e3226f37e50.png)

**Comment by kbengine** [comment]
Can I see the server load the navmesh log?

**Comment by kbengine** [comment]
cellapp*.log

**Comment by cshard447** [comment]
yes
cellapp.log
[cellapp.7129652375332859700.2017-05-02.txt](https://github.com/kbengine/kbengine/files/970058/cellapp.7129652375332859700.2017-05-02.txt)

**Comment by kbengine** [comment]
Navmesh normally loaded!

`  INFO root [0x7f8908ca7780] [2017-05-02 10:29:05,819] - EntityApp::createEntity: new Space 22
  INFO root [0x7f8908ca7780] [2017-05-02 10:29:05,819] - KBEngine::addSpaceGeometryMapping: spaceID=3, respath=spaces/test_space, shouldLoadOnServer=1!
 S_DBG root [0x7f8908ca7780] [2017-05-02 10:29:05,819] - onSpaceData: spaceID=3, key=_mapping, value=spaces/test_space.
 DEBUG root [0x7f89067c8700] [2017-05-02 10:29:05,819] - NavMeshHandle::create: (/root/kbengine/assets/res/spaces/test_space/srv_test_space.navmesh), layer=0
 DEBUG root [0x7f89067c8700] [2017-05-02 10:29:05,821] - 	==> tiles loaded: 1
 DEBUG root [0x7f89067c8700] [2017-05-02 10:29:05,821] - 	==> BVTree nodes: 4636
 DEBUG root [0x7f89067c8700] [2017-05-02 10:29:05,821] - 	==> 2318 polygons (3824 vertices)
 DEBUG root [0x7f89067c8700] [2017-05-02 10:29:05,821] - 	==> 8578 triangles (3675 vertices)
 DEBUG root [0x7f89067c8700] [2017-05-02 10:29:05,821] - 	==> 0.39 MB of data (not including pointers)
 S_DBG root [0x7f8908ca7780] [2017-05-02 10:29:05,821] - created space[3] entityID = 22, res = spaces/test_space.
  INFO root [0x7f8908ca7780] [2017-05-02 10:29:05,917] - KBEngine::onLoadedSpaceGeometryMapping: spaceID=3, respath=spaces/test_space!
 S_DBG root [0x7f8908ca7780] [2017-05-02 10:29:05,917] - onSpaceGeometryLoaded: spaceID=3, mapping=spaces/test_space.
 S_DBG root [0x7f8908ca7780] [2017-05-02 10:29:05,917] - onAllSpaceGeometryLoaded: spaceID=3, isBootstrap=1, mapping=spaces/test_space.`

**Comment by cshard447** [comment]
What then can be the problem?

**Comment by kbengine** [comment]
https://github.com/kbengine/kbengine_unity3d_warring/blob/master/Assets/scripts/world/GameEntityCtrl.cs#L311

In the entity's isGround = true, the server will not synchronize the Y coordinate.
So the client needs to look for the ground and place it on the ground.

**Comment by kbengine** [comment]
Entity is automatically set to isGround = true each time the server navigates.
When the player moves by the client, it decides how to set it up and automatically synchronizes it to the server

**Comment by kbengine** [comment]
Force the location of the entity on the server, for example: self.position.x = 1, isGround will be automatically set to False

**Comment by kbengine** [comment]
IsGround = false, the server will synchronize Y.

Everything is in order to save bandwidth consumption

**Comment by cshard447** [comment]
My GameEntity.cs
[GameEntity.txt](https://github.com/kbengine/kbengine/files/970160/GameEntity.txt)
https://pastebin.com/j5uBqrSv

`

**Comment by kbengine** [comment]
You can refer directly to:
https://github.com/kbengine/kbengine_unity3d_warring/blob/master/Assets/scripts/world/GameEntityCtrl.cs#L301

**Comment by kbengine** [comment]
Locate the ground in void Update (), and place the entity on the ground

**Comment by kbengine** [comment]
My approach may have some consumption, you can use a better way to find the ground position

**Comment by kbengine** [comment]
Can close?

**Comment by cshard447** [comment]
Yes
Problem solved!
Thanks!
