### ISSUE TITLE
设置新的密码回调 onReqAccountBindEmailCB

### ISSUE THREAD

**Issue by pmsl** [kbengine/kbengine#481]
设置新密码，服务器回调错误 path://src/server/baseapp/Baseapp.cpp

void Baseapp::onReqAccountNewPasswordCB(Network::Channel* pChannel, ENTITY_ID entityID, std::string& accountName,
	SERVER_ERROR_CODE failedcode)
{
	......
	(*pBundle).newMessage(ClientInterface::onReqAccountBindEmailCB);
	.......
}

**Comment by kbengine** [comment]
修正
