### ISSUE TITLE
重置密码，输入不存在的账号依然返回成功。

### ISSUE THREAD

**Issue by pmsl** [kbengine/kbengine#482]
在重置密码时输入不存在的账号，依然返回成功。代码中在重置密码时直接返回的是成功，并没有判断具体的操作结果。但是在onReqAccountResetPasswordCB 中返回的是失败。
void Loginapp::reqAccountResetPassword(Network::Channel* pChannel, std::string& accountName)
{
.......
	{
		Network::Bundle* pBundle = Network::Bundle::createPoolObject();
		(*pBundle).newMessage(ClientInterface::onReqAccountResetPasswordCB);
		SERVER_ERROR_CODE retcode = SERVER_SUCCESS;
		(*pBundle) << retcode;
		pChannel->send(pBundle);
	}
	
}

**Comment by kbengine** [comment]
这是故意而为之， 避免试探KBE的账号系统。

如果输入正确就会收到email

**Comment by pmsl** [comment]
如果忽略KBE试探KBE账号系统，想在这里检测失败的消息，该怎么返回？

**Comment by kbengine** [comment]
这里检测不了。

得去数据库检测， 流程也会比较麻烦。
