### ISSUE TITLE
telnetserver被SIGPIPE终结问题

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#498]
http://bbs.kbengine.org/forum.php?mod=viewthread&tid=4229&extra=page%3D1

**Comment by kbengine** [comment]
SIGPIPE可能在初始化期间被第三方库重设了

**Comment by vvfly** [comment]
所以引擎这边的处理没有问题的，是在进程启动期间被环境中第三库破坏重设导致的？

**Comment by kbengine** [comment]
等下会有一个更新，还没具体知道是哪个库在什么情况下做了其他设置，总之是在初始化过程中。
目前的做法是初始化开始安装信号监听， 初始化结束再重装一次，测试通过。

py脚本在游戏运行中也可以去设置信号监听，目前没找到有效信号监听改变拦截的方法。
