### ISSUE TITLE
希望KBE支持WSS协议

### ISSUE THREAD

**Issue by lxdfigo** [kbengine/kbengine#500]
现在很多H5项目都需要WSS协议，KBE又是个不错的服务端引擎，但是如果不支持wss，H5项目就无法使用。希望KBE可以支持wss协议。

**Comment by basesrv** [comment]
！

**Comment by kbengine** [comment]
有空会加上

**Comment by kbengine** [comment]
你们有时间可以找找c++加wss的资料，我找到时间直接加上

**Comment by kebiao** [comment]
目前可以nginx反向代理支持wss

**Comment by kebiao** [comment]
![003y399azy73a4yhg9i9a 690](https://user-images.githubusercontent.com/2352650/37643852-d7a1eb6e-2c5c-11e8-9150-d7cfba3a1924.jpg)

**Comment by kebiao** [comment]
http://blog.fourthbit.com/2014/12/23/traffic-analysis-of-an-ssl-slash-tls-session

**Comment by kebiao** [comment]
已经支持
在配置文件中填写证书地址即可
		
		<sslCertificate> key/server_cert.pem </sslCertificate>
		<sslPrivateKey> key/server_key.pem </sslPrivateKey>
	</channelCommon> 

注意：微信小程序之类的由于不能在wss连接时给出端口，所以客户端默认统一使用443端口连接服务器， 而服务器分为baseapp和loginapp必然存在多个不同端口， 所以建议小程序之类的还是使用ngix来反向代理使用一个统一的443端口对外通讯。

其他可以支持设置端口只需要 connect("wss://loginappIP : loginappPort")即可wss连接服务器。
