### ISSUE TITLE
实体定义文件(*.def)支持自定义常量

### ISSUE THREAD

**Issue by foryoung365** [kbengine/kbengine#502]
希望实体定义文件能够支持自定义常量。如果能支持全局常量而不是单文件就更方便了。
实际使用中可能有多个属性需要同步到指定范围内的客户端，当需要修改属性同步范围时，可以直接修改常量的值而无需修改每个属性的范围。
比如
```
CLIENT_SYNC_RANGE 10
<volatile>
    <position>CLIENT_SYNC_RANGE </position>
    <yaw>CLIENT_SYNC_RANGE </yaw>
    ...
</volatile>
```

**Comment by kbengine** [comment]
你的意思会经常修改这个def的volatile？

**Comment by kbengine** [comment]
感觉并没有带来特别大的作用

**Comment by foryoung365** [comment]
并不一定是经常修改的问题。比如MMORPG，可能会有非常多的实体（比如100个），这类的广播范围通常都会设置为一样的值，比如10。
这时候因为某种原因需要把广播范围改成15（比如客户端的标准分辨率提高了，显示范围更大了），那么就需要修改100个def文件的所有volatile字段，这就很麻烦了。

**Comment by foryoung365** [comment]
并不一定是经常修改的问题。比如MMORPG，可能会有非常多的实体（比如100个），这类的广播范围通常都会设置为一样的值，比如10。
这时候因为某种原因需要把广播范围改成15（比如客户端的标准分辨率提高了，显示范围更大了），那么就需要修改100个def文件的所有volatile字段，这就很麻烦了。

**Comment by kbengine** [comment]
首先我接受你说的方法能带来一些便利性，
但即使100个文件改动频率也是非常低的，通过编辑器工具文件级别的搜索替换也只需要手动的改动几个值而已，操作难度并没有想象的高。

然后这个方案要去做到你说的便利程度， 基本还需要全局的常量， 在多个def文件可以引用使用， 整个开发下来也比较繁琐， 成本较高而没有看到非常大的好处。
