### ISSUE TITLE
python  make install  时出错

### ISSUE THREAD

**Issue by wvkmind** [kbengine/kbengine#503]
/usr/bin/install -c -m 644 pyconfig.h /usr/local/include/python3.4m/pyconfig.h
/usr/bin/install: cannot create regular file '/usr/local/lib/python3.4/config-3.4m//home/wvkmind/github/kbengine/kbe/src/libs/libpython.a': No such file or directory
ranlib: '/usr/local/lib/python3.4/config-3.4m//home/wvkmind/github/kbengine/kbe/src/libs/libpython.a': No such file
Makefile:1343: recipe for target 'libainstall' failed
make: *** [libainstall] Error 1

**Comment by kbengine** [comment]
删除kbengine文件夹重新解包kbengine后执行
chmod -R 755 kbengine
再make试试

**Comment by wvkmind** [comment]
重新git一遍是么，但是我看是路径有毛病

/usr/local/lib/python3.4/config-3.4m//home/wvkmind/github/kbengine/kbe/src/libs/libpython.a
                                                             ^这里

**Comment by wvkmind** [comment]
‘^这里’没对上。。。在‘g-3.4m//home/’

**Comment by wvkmind** [comment]
Makefile 1353行  改成了这样  就好了
if test "$(SHLIB_SUFFIX)" = .dll; then \
         $(INSTALL_DATA) $(LDLIBRARY) $(DESTDIR)$(LIBPL) ; \
else \
         $(INSTALL_DATA) $(LIBRARY) $(LIBRARY) ; \
           $(RANLIB) $(LIBRARY) ; \
fi; \

**Comment by kbengine** [comment]
ok。
我看看

**Comment by wvkmind** [comment]
是我环境的过么

**Comment by kbengine** [comment]
应该是，大家都没有问题，自动化编译测试也通过
