### ISSUE TITLE
希望有一个Generate CS/Py/C++ code的类似功能

### ISSUE THREAD

**Issue by zhangdage** [kbengine/kbengine#505]
快速迭代开发的时候可能需要这么一种批处理小工具, 生成一些通用的 静态代码,  包括服务端和客户端脚本.   枚举,宏定义,协议定义.Config等..  类似腾讯TDR那种.

**Comment by kbengine** [comment]
这个需要结合未来的IDE计划来做。

**Comment by zhangdage** [comment]
哦, 棒,  听说过这个计划, 大概什么时候启动的?  有这个效率对我这类 不严谨的应该会提升不少,  工具帮助生成或过滤一些错误.

**Comment by kbengine** [comment]
不久后有商业团队来做
