### ISSUE TITLE
kbe/tools/server/install/installer.py line 906，查找mysql.exe应该指定到mysql_home的bin

### ISSUE THREAD

**Issue by ICrazyMouse** [kbengine/kbengine#510]
修改之后：ret, cret = syscommand("\"" + mysql_home + "bin\mysql\" --help", True)

windows10安装KBEngine：
    根据安装提示:Enter mysql.exe path(such as: C:\\MySQL Server 5.1\\bin\\):
会把环境变量MYSQL_HOME设置为mysql.exe path，也就是MYSQL_HOME/bin。
dbmgr找不到my.ini文件又会报错，无法启动。
MYSQL_HOME去掉bin，mysql.exe又找不到。

改成第一行所示之后，我自己测试通过。

版本：KBE 0.9.19；mysql-5.7.19

**Comment by kbengine** [comment]
那此时你的 mysql_home 是什么？“C:\MySQL Server 5.1”？

**Comment by ICrazyMouse** [comment]
现在是 G:/mysql-5.7.19-winx64/，不修改代码，install执行完会变成G:/mysql-5.7.19-winx64/bin。
直接启动server，dbmgr会挂掉,lower_case_table_names 不等于0或2那个错误。
改回G:/mysql-5.7.19-winx64/再启动，可以成功。

**Comment by kbengine** [comment]
我感觉你可能有一些误会，至于你是怎么成功的我不清楚。
dbmgr不是读取mysql_home去找my.ini, dbmgr是直接连mysql通过sql查询的参数。
,lower_case_table_names 需要在my.ini中自己去设置。

 C:\MySQL Server 5.1中的my.ini一些版本中并不是mysql所读取的位置。
例如我的就在C:\ProgramData\MySQL\MySQL Server 5.6中， 而安装在 C:\MySQL Server 5.6

**Comment by ICrazyMouse** [comment]
zip包解压安装的mysql，my.ini是自己建的。
mysql跟kbe在同一台机器上，没有配置remote。
MYSQL_HOME 不对的情况下，dbmgr确实会报lower_case_table_names的错误。

**Comment by kbengine** [comment]
那你可能是别的什么原因， dbmgr不读取mysql的配置文件。

**Comment by kbengine** [comment]
lower_case_table_names是必须要去设置的，mysql在windows默认是不区分大小写的。

**Comment by ICrazyMouse** [comment]
嗯，这个已经设置过了。MYSQL_HOME不对的情况下，dbmgr会报错lower_case_table_names不等于0或2。
我以为是找不到my.ini引起的。
