### ISSUE TITLE
mysql 5.7.19安装失败

### ISSUE THREAD

**Issue by sersoong** [kbengine/kbengine#513]
debian 9 x86_64 mysql 5.7.19
python installer.py install 失败
到这里失败：
create kbe mysql-account:
- username(Do not enter the default is 'kbe')):
- password(Do not enter the default is 'kbe')):
Create kbe-account: name=kbe, password=kbe successfully!

Create game database(Do not enter the default is 'kbe'):
ERROR: database is error! ['mysql: [Warning] Using a password on the command line interface can be insecure.\n', "ERROR 1045 (28000): Access denied for user 'kbe'@'localhost' (using password: YES)\n"]

**Comment by kbengine** [comment]
这个错误自己百度吧，mysql给出的。

一般是匿名账户造成登陆不上

**Comment by sersoong** [comment]
碰上这个错误，只好手动建立。
