### ISSUE TITLE
关于sendto错误处理

### ISSUE THREAD

**Issue by bjut-hz** [kbengine/kbengine#518]
bool BundleBroadcast::broadcast(uint16 port)
	{
		if (!epBroadcast_.good())
			return false;
		
		if(port == 0)
			port = KBE_MACHINE_BROADCAST_SEND_PORT;
	
		epBroadcast_.addr(port, Network::BROADCAST);
	
		if (epBroadcast_.setbroadcast(true) != 0)
		{
			ERROR_MSG(fmt::format("BundleBroadcast::broadcast: Cannot broadcast socket on port {}, {}\n",
				port, kbe_strerror()));
	
			networkInterface_.dispatcher().breakProcessing();
			return false;
		}
	
		this->finiMessage();
		KBE_ASSERT(packets().size() == 1);
	
		epBroadcast_.sendto(packets()[0]->data(), packets()[0]->length(), htons(port), Network::BROADCAST);
	
		// 如果指定了地址池，则向所有地址发送消息
		std::vector< std::string >::iterator addr_iter = machine_addresses_.begin();
		for (; addr_iter != machine_addresses_.end(); ++addr_iter)
		{
			Network::EndPoint ep;
			ep.socket(SOCK_DGRAM);
	
			if (!ep.good())
			{
				ERROR_MSG("BundleBroadcast::broadcast: ep error!\n");
				break;
			}
	
			u_int32_t  uaddress;
			Network::Address::string2ip((*addr_iter).c_str(), uaddress);
			ep.sendto(packets()[0]->data(), packets()[0]->length(), htons(KBE_MACHINE_BROADCAST_SEND_PORT), uaddress);
		}
	
		return true;
	}

在sendto调用中，为什么没有对其返回值进行错误处理呢？

**Comment by kbengine** [comment]
这个地方是用于组网时内部广播用的，  这个广播本来就不需要可靠性， 最终有无问题会体现在组网时有没有收集到所有进程

**Comment by kbengine** [comment]
当然， 加上错误处理会更严谨
