### ISSUE TITLE
apr.h 文件找不到 编译引擎失败

### ISSUE THREAD

**Issue by hzx930415** [kbengine/kbengine#521]
VS2013 编译1.0 版本引擎失败，不会生成Exe 文件

**Comment by kbengine** [comment]
https://ci.appveyor.com/project/kbengine/kbengine/branch/master

自动化编译都是通过的。
我自己编译也没问题， 你检查你自己的环境吧， 杀毒关掉重新解压再编译试试。
有过被360拦截导致一些文件没有产生造成编译失败的情况

**Comment by hzx930415** [comment]
好的

**Comment by hzx930415** [comment]
找到问题了，我换了最新的VS2017编译成功，谢谢！！！
