### ISSUE TITLE
希望没有数据保存的实体不要创建数据库表。

### ISSUE THREAD

**Issue by Firesuiry** [kbengine/kbengine#528]
一些执行功能的实体，没有需要数据库保存的内容，但是也会创建数据库表，不知道能不能如果没有任何数据保存的话就不创建这个实体的表？

**Comment by Firesuiry** [comment]
![tim 20171127095155](https://user-images.githubusercontent.com/30189673/33247376-a90c2f6a-d358-11e7-80b2-264cdb7fc37f.png)
![tim 20171127095206](https://user-images.githubusercontent.com/30189673/33247378-aa9b4c12-d358-11e7-94d5-6e5b11e601fd.png)
就是这样创建了很多空的数据表，但是并没有数据保存。

**Comment by makilyang** [comment]
不是有个参数控制不保存实体到数据库的么

**Comment by Firesuiry** [comment]
目前就是设置的都没有保存到数据库呢。
问题就是没有参数保存的话也会生成表。

**Comment by kbengine** [comment]
这个不行。 只要是实体， 都会启动时提前建表， 无法在你writeToDB时再建表。 所以你这种需求应该从你的设计方面考虑， 不应该有这么多类型的实体， 这些实体你可以变为一个实体， 然后通过读取不同的配置来初始化他们。

**Comment by Firesuiry** [comment]
嗯，，我会更改我的设计。。
另外请问假如这个实体没有任何需要储存的数据（完全不会writeToDB）
那么为什么要提前建表呢？

**Comment by kbengine** [comment]
这个问题就好比， 你完全不需要存储， 那为何这个实体要有“writeToDB”接口呢。
这就是引擎的设计， 用不用是开发者的事情， 接口和机制已存在，不再做过细的区分。

**Comment by Firesuiry** [comment]
好的~感谢解答。
