### ISSUE TITLE
实体位置发生轻微移动（即不触发onNodePassX 的情况）

### ISSUE THREAD

**Issue by codeHardest** [kbengine/kbengine#529]
请问 在标题所示的情况下， 要如何触发 range_trigger，使得其enterAOI  或者leaveAOI

**Comment by kbengine** [comment]
跟移动距离大小没有关系，只要进入范围float精度就可以了。
你是怎么得出的结论呢？

**Comment by codeHardest** [comment]
没事了，之前没有完全理解代码，谢谢
