### ISSUE TITLE
客户端sdk生成器

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#532]

**Comment by kbengine** [comment]
通过一个程序自动的生成不同语言的客户端sdk， 达到各种环境与服务器能够统一语法和高效运行

**Comment by zz861880401** [comment]
激动人心的想法！！！期待

**Comment by kbengine** [comment]
就快完成了， 源码目录kbcmd

**Comment by zz861880401** [comment]
Good！

**Comment by kebiao** [comment]
u3d版本完成

**Comment by wikieden** [comment]
其实还是分开的？

**Comment by kbengine** [comment]
一体的，完成生成u3d部分

**Comment by kebiao** [comment]
使用方法：
在服务器项目资产库中 **assets创建一个bat文件， 例如：createClientSDK.bat





@echo off
set curpath=%~dp0

cd ..
set KBE_ROOT=%cd%
set KBE_RES_PATH=%KBE_ROOT%/kbe/res/;%curpath%/;%curpath%/scripts/;%curpath%/res/
set KBE_BIN_PATH=%KBE_ROOT%/kbe/bin/server/

if defined uid (echo UID = %uid%) else set uid=%random%%%32760+1

echo KBE_ROOT = %KBE_ROOT%
echo KBE_RES_PATH = %KBE_RES_PATH%
echo KBE_BIN_PATH = %KBE_BIN_PATH%

cd %curpath%
start %KBE_BIN_PATH%/kbcmd.exe --clientsdk=unity --outpath=D:\kbe\kbengine_unity3d_demo\Assets\Plugins\kbengine\kbengine_unity3d_plugins

**Comment by HelloMeow** [comment]
期待js/lua版本

**Comment by kebiao** [comment]
u3d客户端使用sdk：
服务器中定义的包含客户端的实体都会自动生成 ***Base.cs的实体模块， def属性和方法都已经自动生成好， 需要用户继承这个模块例如：public class Avatar : AvatarBase
继承后， 可以监听属性的改变和调用mailbox与服务器通讯以及监听服务器调用客户端的方法做适当编程， 例如触发事件告诉UI层

**Comment by kebiao** [comment]
[kbengine_unity3d_demo.zip](https://github.com/kbengine/kbengine/files/1631106/kbengine_unity3d_demo.zip)

**Comment by lanfengnan** [comment]
当types.xml中存在PYTHON格式时，导出报错。部分只有服务器使用到的数据结构会使用PYTHON类型（客户端不需要使用的）。

**Comment by kebiao** [comment]
@lanfengnan 是个bug，近期修正

**Comment by kebiao** [comment]
对于没有客户端的组件模块， 不生成客户端部分

**Comment by lanfengnan** [comment]
是这样的，Avatar实体通过Interfaces扩展的邮件管理模块AvatarEmailMgr，与服务器全局实体GlobalEmail之间的远程调用使用PYTHON格式的接口。但是Avatar的有客户端的组件模块，所以用工具生成时就报错了。
报错信息：tool-1:[ERROR]: ClientSDKUnity::writeTypeItemType_PYTHON(): nonsupport! 
@kbengine @kebiao

**Comment by kbengine** [comment]
@lanfengnan 你更新试试。
kbengine这个号也是我， 以后我用kebiao这个号了

**Comment by lanfengnan** [comment]
@kebiao 之前那个问题好了，现在又另外个问题：在types.xml中存在这样的结构
    <Reward> ARRAY <of> UINT32 </of> </Reward>
    <RewardList> ARRAY <of> Reward</of> </RewardList>

导出到客户端插件时报错：
cannot convert `System.Collections.Generic.List<System.Collections.Generic.List<uint>>' expression to type `KBEngine.RewardList'

CustomDataTypes.cs=============================================
public void addToStreamEx(Bundle stream, RewardList v)
			{
				stream.writeUint32((UInt32)v.Count);
				for(int i=0; i<v.Count; ++i)
				{
					itemType.addToStream(stream, v[i]);
				};
			}
KBETypes.cs=============================================
	public class Reward : List<UInt32>
	{

	}

	public class RewardList : List<List<UInt32>>
	{

	}

**Comment by kebiao** [comment]
public class DATATYPE_Reward : DATATYPE_BASE
	{
		public Reward createFromStreamEx(MemoryStream stream)
		{
			UInt32 size = stream.readUint32();
			Reward datas = new Reward();

			while(size > 0)
			{
				--size;
				datas.Add(stream.readUint32());
			};

			return datas;
		}

		public void addToStreamEx(Bundle stream, Reward v)
		{
			stream.writeUint32((UInt32)v.Count);
			for(int i=0; i<v.Count; ++i)
			{
				stream.writeUint32(v[i]);
			};
		}
	}



	public class DATATYPE_RewardList : DATATYPE_BASE
	{
		private DATATYPE_RewardList_ChildArray itemType = new DATATYPE_RewardList_ChildArray();

		public class DATATYPE_RewardList_ChildArray : DATATYPE_BASE
		{
			private DATATYPE_Reward_ChildArray itemType = new DATATYPE_Reward_ChildArray();

			public class DATATYPE_Reward_ChildArray : DATATYPE_BASE
			{
				public List<UInt32> createFromStreamEx(MemoryStream stream)
				{
					UInt32 size = stream.readUint32();
					List<UInt32> datas = new List<UInt32>();

					while(size > 0)
					{
						--size;
						datas.Add(stream.readUint32());
					};

					return datas;
				}

				public void addToStreamEx(Bundle stream, List<UInt32> v)
				{
					stream.writeUint32((UInt32)v.Count);
					for(int i=0; i<v.Count; ++i)
					{
						stream.writeUint32(v[i]);
					};
				}
			}

			public RewardList createFromStreamEx(MemoryStream stream)
			{
				UInt32 size = stream.readUint32();
				RewardList datas = new RewardList();

				while(size > 0)
				{
					--size;
					datas.Add(itemType.createFromStreamEx(stream));
				};

				return datas;
			}

			public void addToStreamEx(Bundle stream, RewardList v)
			{
				stream.writeUint32((UInt32)v.Count);
				for(int i=0; i<v.Count; ++i)
				{
					itemType.addToStream(stream, v[i]);
				};
			}
		}

		public RewardList createFromStreamEx(MemoryStream stream)
		{
			return itemType.createFromStreamEx(stream);
		}

		public void addToStreamEx(Bundle stream, RewardList v)
		{
			itemType.addToStream(stream, v);
		}
	}

我这里好像没有问题？
@lanfengnan

**Comment by lanfengnan** [comment]
@kebiao 解析数据没有问题，用的时候报的错误
![image](https://user-images.githubusercontent.com/17491132/35900927-5f075260-0c0f-11e8-8d2e-4b97421e6e57.png)

**Comment by kebiao** [comment]
那就是外面引用这个类型解析出错了。

给个稍微完整的例子吧
@lanfengnan

**Comment by lanfengnan** [comment]
[Gameassets.zip](https://github.com/kbengine/kbengine/files/1701947/Gameassets.zip)
@kebiao 
![image](https://user-images.githubusercontent.com/17491132/35901463-a5cfb99c-0c11-11e8-98c5-34e12474ab7f.png)

**Comment by kebiao** [comment]
@lanfengnan 更新一下再试试

**Comment by lanfengnan** [comment]
@kebiao 可以了，其它暂时没有问题

**Comment by lanfengnan** [comment]
![image](https://user-images.githubusercontent.com/17491132/36210606-d18a2fa4-11d9-11e8-9cf6-c31160ca831e.png)
@kebiao 现在有点问题，像这种结构，在客户端生成的是下面这种结构
![image](https://user-images.githubusercontent.com/17491132/36210631-e2710856-11d9-11e8-970e-c49c21f3a2de.png)
不是键值对应的，实际操作的时候每次都需要遍历，比如修改其中某个道具的数量或者其他改变。不能通过key值进行改变，看是否需要切换到其他的类型，例如Dictionary<long, Prop>这种结构，或者是根据服务器的implementedBy进行对应的变化

**Comment by kebiao** [comment]
客户端无法做到键值对应， 必须是强类型， 否则就只能用object代替回到以前了。
你可以在客户端再写一个类似服务器的implmentBy类， 转换这个字典重实现为你想的形式。
工具是不知道你服务器的implmentBy脚本的形式的， 这部分本来就是交给用户自己实现的

**Comment by kebiao** [comment]
UE4生成已经完成
