### ISSUE TITLE
linux下make的时候一些文件会被变更

### ISSUE THREAD

**Issue by sersoong** [kbengine/kbengine#536]
详情请看下面的打包文件。
[git_status.zip](https://github.com/kbengine/kbengine/files/1554087/git_status.zip)

**Comment by kbengine** [comment]
这可能是第三方库要生成文件，执行了chmod之类的命令造成的

**Comment by sersoong** [comment]
diff --git a/kbe/src/lib/dependencies/openssl/crypto/opensslconf.h.bak b/kbe/src/lib/dependencies/openssl/crypto/opensslconf.h.bak
index 4c36fac8a..4abfd1514 100644
--- a/kbe/src/lib/dependencies/openssl/crypto/opensslconf.h.bak
+++ b/kbe/src/lib/dependencies/openssl/crypto/opensslconf.h.bak
@@ -1,259 +1,5 @@
-/* opensslconf.h */
-/* WARNING: Generated automatically from opensslconf.h.in by Configure. */
-
-#ifdef  __cplusplus
-extern "C" {
-#endif
-/* OpenSSL was configured with the following options: */
-#ifndef OPENSSL_SYSNAME_WIN32
-# define OPENSSL_SYSNAME_WIN32
-#endif
-#ifndef OPENSSL_DOING_MAKEDEPEND
-
-
-#ifndef OPENSSL_NO_EC_NISTP_64_GCC_128
-# define OPENSSL_NO_EC_NISTP_64_GCC_128
-#endif
-#ifndef OPENSSL_NO_GMP
-# define OPENSSL_NO_GMP
-#endif
-#ifndef OPENSSL_NO_JPAKE
-# define OPENSSL_NO_JPAKE
-#endif
-#ifndef OPENSSL_NO_KRB5
-# define OPENSSL_NO_KRB5
-#endif
-#ifndef OPENSSL_NO_LIBUNBOUND
-# define OPENSSL_NO_LIBUNBOUND
-#endif
-#ifndef OPENSSL_NO_MD2
-# define OPENSSL_NO_MD2
-#endif
-#ifndef OPENSSL_NO_RC5
-# define OPENSSL_NO_RC5
-#endif
-#ifndef OPENSSL_NO_RFC3779
会修改一些头文件和一些.c文件

**Comment by sersoong** [comment]
这样我们在开发测试的时候岂不是很容易就跟原来的文件不一样了？

**Comment by kbengine** [comment]
第三方库行为不受控制，你开发时可以忽略依赖库的修改。  一般在windows vc下开发，暂时没有这方面的问题

**Comment by sersoong** [comment]
好的。
