### ISSUE TITLE
应该如何在kbe脚本中import第三方库pybullet？

### ISSUE THREAD

**Issue by reatank** [kbengine/kbengine#539]
因要在服务器进行物理引擎的判定，故想在服务器脚本中引入bullet。
执行如下步骤：①pip install pybullet ②将Lib\site-packages中pybullet_data、pybullet_envs和pybullet-1.7.5.dist-info三个文件夹复制到kbe\res\scripts\common\Lib中 ③在脚本中import pybullet
但启动服务器时报错，提示在import时无法找到该module。请问我该怎么做？

**Comment by kebiao** [comment]
如果你这个库中有pyd的话， 参考http://bbs.kbengine.org/forum.php?mod=viewthread&tid=3881&extra=page%3D1%26filter%3Ddigest%26digest%3D1

你需要将pyd编译进去

**Comment by finchcn** [comment]
同求具体的安装方法

**Comment by kebiao** [comment]
只能参考那个帖子了， 我没弄过
