### ISSUE TITLE
插件生成器是否可把onStreamDataAPI相关的消息推送实现加一下呢。

### ISSUE THREAD

**Issue by huangyechuan** [kbengine/kbengine#547]
/*
			服务端通知流数据下载开始
			请参考API手册关于onStreamDataStarted
		*/
		public void Client_onStreamDataStarted(Int16 id, UInt32 datasize, string descr)
		{
		}
		
		public void Client_onStreamDataRecv(MemoryStream stream)
		{
		}
		
		public void Client_onStreamDataCompleted(Int16 id)
		{
		}

**Comment by kebiao** [comment]
可以

**Comment by kebiao** [comment]
已加
