### ISSUE TITLE
cppformat升级

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#561]
先测试当前版本与最新版本的性能。
测试方法， 在一个格式化语句中同时格式化多种数据类型， 如
format("{}{}{}{}{}{}", 1， 0.1f，0.33333333，“fsafas”, ...)

**Comment by jay602** [comment]
fmtlib库的format测试结果(单位:ms)：
int: run time: 13307
float: run time: 32823
double: run time: 32838
string: run time: 13198
fixed: run time: 76815


kbengine的format测试结果(单位:ms):
int: run time: 36785
float: run time: 46223
double: run time: 45303
string: run time: 31325
fixed: run time: 120994
