### ISSUE TITLE
centos下执行update升级到1.1.3后version查看还是1.0.0

### ISSUE THREAD

**Issue by Roytin** [kbengine/kbengine#564]
阿里云的centos上，安装的是1.0.0的kbengine，执行命令
python $KBE_ROOT/kbe/tools/server/install/installer.py update
一切顺利。
之后应该升级到最新的1.1.3了
但是查看python $KBE_ROOT/kbe/tools/server/install/installer.py version
还是1.0.0

**Comment by kebiao** [comment]
你看一下$KBE_ROOT指向哪里， 是不是你期望的

**Comment by Roytin** [comment]
$KBE_ROOT指向/root/kbengine/，一切都是正常结束的，下面是我复制的输出片段: 
Install KBEngine to Linux-account(No input is kbe):root
Already installed KBEngine, KBE_ROOT=[/root/kbengine/].

Want to install to [/root/kbengine/]?[yes|no]yes


Installing KBEngine[/root/kbengine/]...
Found that the existing directory(/root/kbengine//kbe/res/), whether to replace the: [yes|no]?yes
Found that the existing directory(/root/kbengine/kbe/tools), whether to replace the: [yes|no]?yes
Found that the existing directory(/root/kbengine/kbe/src), whether to replace the: [yes|no]?yes
moved: 10366/10366 (100%)
moved: 170/170 (100%)
moved: 2235/2235 (100%)
Cleanup temporary files...

Check the dependences:
- kbe_environment: checking...
- kbe_environment: yes
- mysql: checking...
- MySQL is installed on the remote machine?[yes/no]yes
- Enter mysql ip-address:***
- Enter mysql ip-port:3306
- Enter mysql-account:***
- Enter mysql-password:***
- Enter mysql-databaseName:kbe
- mysql: yes
Modified: /root/kbengine//kbe/res/server/kbengine_defaults.xml
KBEngine has been successfully installed!
[root@izuf6brkj3yuz0ede1qj77z ~]# python $KBE_ROOT/kbe/tools/server/install/installer.py version
version=v1.0.0

View the latest version of GitHub? [yes|no]yes

Check out the latest version...

**Comment by kebiao** [comment]
def findLocalKBEVersion():
	global KBE_ROOT

	KBE_ROOT = getEnvironment('user', 'KBE_ROOT')

	fpath = "../../../../HISTORY.md"
	if len(KBE_ROOT) > 0:
		fpath = KBE_ROOT + "/HISTORY.md"

	try:
		f = open(fpath)
		for line in f.readlines():
			if "#v" in line:
				f.close()
				return line.replace("#", "")

		f.close()
	except:
		pass

	return "unknown"

可以调试一下代码读取的是哪里？github上HISTORY.md是1.1.3
