### ISSUE TITLE
entity组件支持

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#566]
能够在def中定义组件描述， 能够def给entity挂组件， 组件支持存档和远程调用等等的实体相关特性

**Comment by evilrise** [comment]
有组件的文档么？

**Comment by kebiao** [comment]
[demos_assets.zip](https://github.com/kbengine/kbengine/files/1791562/demos_assets.zip)

最终就是类似unity给对象挂组件， 只是目前没有编辑器就变成手写代码的方式挂。
参考Avatar.def:
  <Components>
		<component1>			
			<Type> 			Test		</Type>
			<Persistent>	true		</Persistent>
		</component1>

		<component2>			
			<Type> 			Test		</Type>
			<Persistent>	false		</Persistent>
		</component2>

		<component3>			
			<Type> 			TestNoBase	</Type>
      		<Persistent>	true		</Persistent>
		</component3>
	</Components>

以及类型为TestNoBase和Test的组件def和脚本的写法。

**Comment by cjc1016** [comment]
建议添加自动加载开关，并且提供手动加载接口，灵活控制
