### ISSUE TITLE
assets 2.0异常

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#568]

**Comment by Myskip** [comment]
服务端使用2.0版本，纯净assets。客户端测试代码为：
`    public void onClick()
    {
        KBEngine.Event.fireIn("login", "myskip", "myskip", System.Text.Encoding.UTF8.GetBytes("KBEngine"));
    }
[logger_dbmgr.2018-03-12.log](https://github.com/kbengine/kbengine/files/1801244/logger_dbmgr.2018-03-12.log)
`

服务端报错log见附件。所查询account在数据库中为:
`mysql> select * from kbe_accountinfos;
+-------------+----------------------------------+----------+------------+------------+-------+----------+------------+------------+----------+
| accountName | password                         | bindata  | email      | entityDBID | flags | deadline | regtime    | lasttime   | numlogin |
+-------------+----------------------------------+----------+------------+------------+-------+----------+------------+------------+----------+
| admin       | 21232f297a57a5a743894a0e4a801fc3 | KBEngine | admin@0.0  |          2 |     0 |        0 | 1520758984 | 1520758984 |        1 |
| myskip      | cb6e813422996311b9a71744fe165e2d | KBEngine | myskip@0.0 |          1 |     0 |        0 | 1520758809 | 1520821812 |        3 |
+-------------+----------------------------------+----------+------------+------------+-------+----------+------------+------------+----------+
2 rows in set (0.00 sec)`

但使用kbengine_unity3d_demo的assets时没有问题。

**Comment by Myskip** [comment]
[logger_dbmgr.2018-03-12.log](https://github.com/kbengine/kbengine/files/1801277/logger_dbmgr.2018-03-12.log)
