### ISSUE TITLE
自定义实体不能自动保存属性

### ISSUE THREAD

**Issue by sdkbb2007** [kbengine/kbengine#571]
#创建离线消息处理器
		KBEngine.createEntityAnywhere("OfflineMessage")
		#创建玩家在线实体管理处理器
		KBEngine.createEntityAnywhere("OnLinePlayerManager")
		#创建玩家共享信息管理处理器
		KBEngine.createEntityAnywhere("AllPlayerPublicInfo")

这些自定义实体里面有持久化的属性，但是都不能自动保存，但是Account是可以的

**Comment by kebiao** [comment]
这些实体你调用过writeToDB吗

**Comment by kebiao** [comment]
createEntityAnywhereFromDBID

**Comment by kebiao** [comment]
这个api的前提是你曾经用createEntityAnywhere等api创建过并调过过writeToDB，实体才有dbid， 然后第二次你从数据库加载就需要createEntityAnywhereFromDBID类的api。

你可以试试writeToDB的autoload参数， 服务器启动后就不需要你用createEntityAnywhereFromDBID去加载起来了
