### ISSUE TITLE
关于 gensdk.bat 生成Unity客户端插件的建议

### ISSUE THREAD

**Issue by Hersenberg** [kbengine/kbengine#572]
目前生成的客户端静态挺方便的,  但使用上有个小建议,  
1:在这里 Call entity server method:
entity.baseCall("base_func", 1, "arg2", "argN")
entity.cellCall("cell_func", 1, "arg2", "argN")
这个"base_func"和"cell_func", 在Unity端同时生成一个, ClientMethodDefine.Base_func1 的string 静态代码类型 是不是会更方便一些 , 像这样 批处理同时生成一个这样的类, 
internal class ClientMethodDefine
{
        public const string Base_func1 = "base_func";
}
调用的时候可以这样调用, 
entity.cellCall(ClientMethodDefine.Base_func1 , 1, "arg2", "argN")

2: 类似的 Event.fireIn 和 fireOut 也一样, 
KBEngine.Event.fireIn("login", "stringAccount", "stringPasswd", System.Text.Encoding.UTF8.GetBytes("kbengine_unity3d_demo"));
KBE-Plugin fire-out events(KBE => Unity):
	Entity events:
		onEnterWorld
			Description: 
				Entity enter the client-world.
onEnterWorld 这种定义在一个 internal class 中, 也可以自定义扩展..
这样是不是启到了静态编码的目的,  点一个代码提示就出来了, 更高的客户端编码效率.

**Comment by kebiao** [comment]
1: entity.cellCall(ClientMethodDefine.Base_func1 , 1, "arg2", "argN")
都已经出现几个关键字了， entity、Base_func1，cell 那为何不直接entity.cellEntityCall.Base_func1？

2: 这个是有计划这样做

**Comment by kebiao** [comment]
完成2
