### ISSUE TITLE
onTimer里面调Entity的成员方法，每次id不同

### ISSUE THREAD

**Issue by sekkit** [kbengine/kbengine#579]
def onTimer(self, tid, arg):
     self.update()
     
id(self.update)一直变化，按理说，同一个instance上的bound method，第一次生成后就不会一直new新的出来了。

**Comment by sekkit** [comment]
yes

**Comment by kebiao** [comment]
id没有变化啊

**Comment by sekkit** [comment]
那就是python3.6的锅吧，我回头测一下。
