### ISSUE TITLE
UDP可靠和不可靠通讯模式支持

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#588]
原有TCP模式同时保留，由用户选择网络协议

**Comment by ilvxna** [comment]
请问，kbe能否支持kcp(https://github.com/skywind3000/kcp)协议？

**Comment by kebiao** [comment]
@ilvxna 可以去投票https://bbs.comblockengine.com/forum.php?mod=viewthread&tid=5928&extra=page%3D1

**Comment by kebiao** [comment]
KCP已加入

**Comment by Kiddinglife** [comment]
sctp 也不错的 哈哈
