### ISSUE TITLE
Baseapp01 ERROR

### ISSUE THREAD

**Issue by annak1n** [kbengine/kbengine#591]
Hello, I start the server on Debian 8x
Next, I try to enter the server using kbengine_unity3d_warning.
But the server gives me this error and I can not create a character.
When I try to create a character, I get this message on the server:
**baseapp01: [ERROR]: Account :: onRemoteMethodCall: can not found method. utype = 10002, methodName = unknown, callerID: 2002.**

**Comment by kebiao** [comment]
Hi，
KBE version？
Client version？

**Comment by annak1n** [comment]
I think its last :)
Mb problem its on DataBase ?

**Comment by kebiao** [comment]
Have you changed the version number?

Take a screenshot of the client game window. There is some version information.

Should not be a problem with the database.

**Comment by kebiao** [comment]
Try to use server and demo using 1.x
