### ISSUE TITLE
关于服务器随机地图碰撞数据的加载问题

### ISSUE THREAD

**Issue by chuqiuhan** [kbengine/kbengine#599]
现在我们项目里需要动态生成随机地图，我们现在的做法是服务器提供随机种子，客户端生成地图数据，然后让客户端上传对应的碰撞数据，服务器只做一个抽样校验，客户端上传的数据如何使用引擎里的astar寻路算法？需要让脚本层创建数据文件，使用addSpaceGeometryMapping加载数据吗？

**Comment by kebiao** [comment]
服务器的2d寻路不完善， 你要用astar可能需要做一些扩展。
你可以通过你描述的方式把数据传到是spaces/xxx下， 然后用addSpaceGeometryMapping加载。

你可以看看recastnav的2d寻路功能， 引擎底层默认嵌入的是这个寻路插件
