### ISSUE TITLE
Setting gameUpdateHertz to 100 causes rubberbanding on Unity demo

### ISSUE THREAD

**Issue by krogank9** [kbengine/kbengine#601]
![mov](https://user-images.githubusercontent.com/12469653/39330409-901b9558-496f-11e8-8c5a-05a189836b2c.gif)

I think it is because speed calculation becomes imprecise with a higher update hz.

One possible solution would be to pull back movement only once every 100ms even with a higher update Hz. This would add support for very high real-time games. Thoughts?

**Comment by kebiao** [comment]
1：cell/Avatar.py : 
     self.moveSpeed = 60.0
     self.topSpeed = self.moveSpeed + 5.0

     self.topSpeed is 65.0


2: server errors:
   DEBUG    cellapp01 18116 8001  [2018-04-27 10:44:16 337] - Avatar::onUpdateDataFromClient: 176 position[(-66.566,1.05,-141.653) -> (-66.2818,1.05,-142.315), (xzDist=0.72002)>(topSpeed=0.65) || (yDist=2.38419e-07)>(topSpeedY=-0.1)] invalid. reset client!
   DEBUG    cellapp01 18116 8001  [2018-04-27 10:44:16 437] - Avatar::onUpdateDataFromClient: 176 position[(-66.566,1.05,-141.653) -> (-66.0449,1.05,-142.866), (xzDist=1.32004)>(topSpeed=0.65) || (yDist=2.38419e-07)>(topSpeedY=-0.1)] invalid. reset client!
   DEBUG    cellapp01 18116 8001  [2018-04-27 10:44:16 537] - Avatar::onUpdateDataFromClient: 176 position[(-66.566,1.05,-141.653) -> (-65.8081,1.05,-143.418), (xzDist=1.92007)>(topSpeed=0.65) || (yDist=0)>(topSpeedY=-0.1)] invalid. reset client!
   DEBUG    cellapp01 18116 8001  [2018-04-27 10:44:16 637] - Avatar::onUpdateDataFromClient: 176 position[(-66.566,1.05,-141.653) -> (-65.5713,1.05,-143.969), (xzDist=2.52009)>(topSpeed=0.65) || (yDist=0)>(topSpeedY=-0.1)] invalid. reset client!


The position submitted by the client to the server is not strictly 100HZ. The difference between the position of the last synchronization and the current synchronization is greater than the difference allowed by topSpeed.

**Comment by kebiao** [comment]
No support, there may be systematic collaboration between multiple cellapps, and the frequency should be consistent.

**Comment by krogank9** [comment]
What if KBEngine.APP_FLAGS_NOT_PARTCIPATING_LOAD_BALANCING is set?

**Comment by kebiao** [comment]
Hi，
Setting to KBEngine.APP_FLAGS_NOT_PARTCIPATING_LOAD_BALANCING can allow different updateHZs between multiple processes, but this may encounter other troubles, such as: Where the creation of the entity is allocated, manual processing is required, and the entity is created into the specified process.

At present, this is not a function that most people need. To keep the engine simple, you can add this feature to your own branch and wait until more people need it before adding it to the master.
