### ISSUE TITLE
mysql表名支持忽略大小写

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#605]

**Comment by ahffffffff** [comment]
改动不小哟

**Comment by kebiao** [comment]
不会很大改动

**Comment by kebiao** [comment]
不再需要设置lower_case_table_names

**Comment by ahffffffff** [comment]
恩，新项目还好

可预见的就是所有的entiti都要小写了吧？或许可以在底层存储的时候强制小写。

老项目要兼容升级就是个麻烦事儿，当然这不属于引擎范围。 各家自己项目内部功能 兼容 和其它系统的交互处理等

不过总的来说这个确实是要改的。

**Comment by kebiao** [comment]
新老项目不受影响， 引擎内部处理即可。
