### ISSUE TITLE
 MemoryStream Error

### ISSUE THREAD

**Issue by annak1n** [kbengine/kbengine#627]
This error on the server I have when I try to create an avatar.
`baseapp01: [ERROR]: Attempted to get in MemoryStream (pos:10  size: 0).`
Server version: **2.x** _(and i tried and with earlier versions)_
Client Version: https://github.com/kbengine/kbengine_unity3d_warring/releases/tag/v1.1.6

What could be the problem ?

**Comment by kebiao** [comment]
Please match the version.
Download the 2.x client https://github.com/kbengine/kbengine_unity3d_warring/releases/tag/v2.0.0

**Comment by annak1n** [comment]
The development environment has changed? or is she also Unity3d 4.x?

**Comment by annak1n** [comment]
Now i get error on the server:
` baseapp01: [ERROR]: Account::onRemoteMethodCall: can't found method. utype=10002, methodName=unknown, callerID:3`
