### ISSUE TITLE
Account::onRemoteMethodCall: can't found method

### ISSUE THREAD

**Issue by annak1n** [kbengine/kbengine#628]
After upgrade Server and Client to version 2.0.0 i get error on the server:
Server Version 2.0.1
Client Version https://github.com/kbengine/kbengine_unity3d_warring/releases/tag/v2.0.0
baseapp01: [ERROR]: Account::onRemoteMethodCall: can't found method. utype=10002, methodName=unknown, callerID:3

**Comment by annak1n** [comment]
I found on the forum that i need to generate plugins, but I can not understand out where to make them and where to put them later?

**Comment by kebiao** [comment]
1:warring source code already contains the generated plugin
2: Is it a server started from https://github.com/kbengine/kbengine_demos_assets?

**Comment by kebiao** [comment]
generate plugins：https://github.com/kbengine/kbengine_demos_assets/blob/master/gensdk.bat

**Comment by annak1n** [comment]
1) We need to compile the server then download this Demo Assets and run the generation of plugins?
2) What should I do with the generated files?
3) Or after generating the files, you just need to start the server?
