### ISSUE TITLE
Compiling StreaminAssets problem on kbengine_unity3d_warring

### ISSUE THREAD

**Issue by annak1n** [kbengine/kbengine#642]
Hello, why can not I compile a new file for StreamingAssets?
Only xinshoucun_x_x.unity3d is compiled..
But i need and other files like:
gameui.unity3d
avatar1.unity3d
loadingbar.unity3d
And etc...
mb its becuz i use Uity3d Personal not Pro ?
Or do something wrong ?

I want to translate the client into English, but whatever I change in the interface of the game does not change anything, because the game loads already compiled files from the folder: **StreamingAssets**

**Comment by kebiao** [comment]
You have to choose to open start.scene.
Then click on the menu (publish->build publish assetbundles)

**Comment by kebiao** [comment]
You want to add an export object. You need to follow some rules.
I have forgotten, you can read the source code (ExprotAssetBundles.cs)

**Comment by kebiao** [comment]
My version is unity4.7.2f1 pro.

**Comment by kebiao** [comment]
You try to make your added object a Prefabs/*
