### ISSUE TITLE
真不明白作者为什么选用python做为脚本语言

### ISSUE THREAD

**Issue by daiwy** [kbengine/kbengine#645]
学了几个星期，最后被Python几个tab和空格打败。去作者论坛发帖，也被拒绝。。感觉作者真的不能太技术控，学学Unity拥抱开发者。

**Comment by kebiao** [comment]
你被空格打败是你的习惯问题， 不要找理由。
python在全世界也是排名比较前的语言， AI等都拥抱了python,  也即将纳入国内高考（https://www.sohu.com/a/209724968_100050964）。

你这样的问题我并不想回， 太新手太不负责任的提问。

**Comment by daiwy** [comment]
抱歉

**Comment by myth326** [comment]
python挺好
