### ISSUE TITLE
再问一个问题

### ISSUE THREAD

**Issue by daiwy** [kbengine/kbengine#646]
我也是刚学不是太懂。能不能把asset这个，做成一个python项目，然后把kbengine那些可以做为链接库，可以导入进去，有智能提示。然后整个项目可以调试跟踪。。我不是太懂，作者觉得太弱智，可以不用回答，谢谢。

**Comment by kebiao** [comment]
这个后面会做支持https://github.com/kbengine/kbengine/issues/639
