### ISSUE TITLE
引擎telnet服务 linux下支持上下键翻阅历史命令

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#656]

**Comment by thao6626** [comment]
看了一下Telnetserver的终端，是支持的VT100啊， 希望支持python自己的console操作，现在用起来太别扭了

**Comment by thao6626** [comment]
感觉用Telnet实现console太绕了，python 有一个console可以用用`code.InteractiveConsole`

**Comment by thao6626** [comment]
这个功能还是有点问题

`[baseapp@python ~] >>>
[baseapp@python ~] >>>
[baseapp@python ~] >>>
[baseapp@python ~] >>>                        [baseapp@python ~] >>>                        tm.task_center.daily_tasks[baseapp@python ~] >>>  tm.task_center.daily_tasks[baseapp@python ~] >>>                        tm.task_center.daily_tasks[baseapp@python ~] >>>                       tm[baseapp@python ~] >>>                        tm = r.TaskMgr[baseapp@python ~] >>>                        tm[baseapp@python ~] >>>           tm.task_center.daily_tasks[baseapp@python ~] >>>                        tm.task_center.daily_tasks[baseapp@python ~] >>>                       tm.task_center.daily_tasks`

按上下键的时候都成这样了

**Comment by thao6626** [comment]
按一个上键或下键，就多出提示符

**Comment by thao6626** [comment]
2.3.0版本的，不过是前不久从master合过来的，对应最近的版本是2.3.0  

重现的操作就是按上下键，是把历史命令打出来了，但是是会出现上面的情况

另外还有个问题是，在没有字符输入的时候按delete键，光标会一直往后面跑

**Comment by jay602** [comment]
自己测下，没有复现。你从https://github.com/kbengine/kbengine重新克隆下来，再跑一遍看看

**Comment by thao6626** [comment]
是从2.0低版本升级上来的。

我的虚拟机是Ubuntu，终端是iterm2

不清楚是什么情况

**Comment by jay602** [comment]
iterm2？你用的是mac os?

**Comment by jay602** [comment]
https://www.cnblogs.com/xishuai/p/mac-iterm2.html  

> 是从2.0低版本升级上来的。
> 
> 我的虚拟机是Ubuntu，终端是iterm2
> 
> 不清楚是什么情况

item2? 
是mac os上的软件吧。没在mac上用这个软件测过

**Comment by thao6626** [comment]
@jay602    是的，是mac os的一个终端，但是引擎跑在虚拟机Ubuntu上面

**Comment by thao6626** [comment]
@jay602  不知道有没有影响，可以看看上下键的实现以及回显文字这一块是不是又什么小的问题没被发现

**Comment by thao6626** [comment]
@jay602   
![image](https://user-images.githubusercontent.com/6292860/48691460-9b5b9300-ec0d-11e8-8c82-538e17b99736.png)

是上面的 terminal emulation 吗，截图所示

**Comment by jay602** [comment]
> @jay602
> ![image](https://user-images.githubusercontent.com/6292860/48691460-9b5b9300-ec0d-11e8-8c82-538e17b99736.png)
> 
> 是上面的 terminal emulation 吗，截图所示

原来是xterm-256color协议，好的，我测下

**Comment by thao6626** [comment]
@jay602  设置里面还有好几个可以选

xterm,  xterm-new, xterm-256color, vt100, ansi, rxvt, linux

这也不能所有都支持吧，不是很懂这种协议

**Comment by jay602** [comment]
> @jay602 设置里面还有好几个可以选
> 
> xterm, xterm-new, xterm-256color, vt100, ansi, rxvt, linux
> 
> 这也不能所有都支持吧，不是很懂这种协议

你改为vt100，试试看

**Comment by thao6626** [comment]
@jay602   改成了vt100 还是不行，还是一样的问题

**Comment by jay602** [comment]
> @jay602 改成了vt100 还是不行，还是一样的问题

看看其他协议是不是也一样，都测下

**Comment by thao6626** [comment]
@jay602   都是一样的，没变化
