### ISSUE TITLE
English documentation/tutorials?

### ISSUE THREAD

**Issue by Narcotic904** [kbengine/kbengine#673]
They used to exist. But not anymore.

**Comment by kebiao** [comment]
https://github.com/kbengine/kbengine/issues/550
Look here.

**Comment by Narcotic904** [comment]
Thats nice but its not really telling us what we need to do to spawn entities etc.

**Comment by kebiao** [comment]
References:

https://github.com/kbengine/kbengine_unity3d_demo

https://www.comblockengine.com/docs/1.0/
https://bbs.comblockengine.com/forum.php?mod=viewthread&tid=166&extra=page%3D1

**Comment by Narcotic904** [comment]
Thank you very much.

**Comment by Narcotic904** [comment]
Where on the server is this code from the client handled?

KBEngine.Event.fireIn("updatePlayer", spaceID, gameObject.transform.position.x, 
			gameObject.transform.position.y, gameObject.transform.position.z, gameObject.transform.rotation.eulerAngles.y);

I have searched the entire scripts folder and cannot fild that event on the server side.

**Comment by kebiao** [comment]
Search updatePlayer on the client.
