### ISSUE TITLE
增加logout接口，让客户端可以主动退出服务器

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#676]

**Comment by xiaoaq** [comment]
客户端调用了logout后，除了等待退出，还需要做其它动作吗，比如反注册所有事件或reset getsingle...

**Comment by kebiao** [comment]
能清理是好习惯，不过app退出了清不清都是一个结果

**Comment by kebiao** [comment]
能清理是好习惯，不过app退出了清不清都是一个结果

**Comment by xiaoaq** [comment]
嗯。但如果游戏进程还在，只在进程内登出的话只调用logout能使客户端和服务端彻底脱离联系吗？知道再次login。

**Comment by kebiao** [comment]
可以， 要重新登录你最好reset一下插件。

**Comment by xiaoaq** [comment]
嗯，好的，我看login里已经还有做reset了
