### ISSUE TITLE
FIXED_DICT不支持for key in xxxDict？

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#706]

**Comment by kebiao** [comment]
>>>KBEngine.entities[175].xxx
{'k2': 0, 'k1': 0}

>>>type(_)
<class 'FixedDict'>

>>>for x in KBEngine.entities[175].xxx:
   print(x)
Traceback (most recent call last):
  File 	<string>	, line 1, in <module>
TypeError: 'FixedDict' object is not iterable

>>>s={'k2': 0, 'k1': 0}



>>>type(s)
<class 'dict'>

>>>for x in s:
   print(x)
k2
k1

**Comment by thao6626** [comment]
globaldata 也不支持这样，只能items()去遍历了

**Comment by jp3411952** [comment]
python语法还像是这样直接取字典是遍历的key
