### ISSUE TITLE
引擎中assets目录放到模板中，使用工具创建一个新脚本项目提供给开发者

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#781]

**Comment by xiaoaq** [comment]
"kbcmd --newassets=d:/xserver_assets"这句是什么作用？
模板中的python_assets跟new_assets.sh生成的server_assets有什么区别吗

**Comment by kebiao** [comment]
目前没有区别，就是一个copy，规范了创建新项目的行为，以后需要区别时再说。
