### ISSUE TITLE
Disable standart Account system

### ISSUE THREAD

**Issue by VTaredi** [kbengine/kbengine#783]
How i can disable standart Account system?
I don't understend your account system, can i make own users profile system?

**Comment by kebiao** [comment]
You can send login and registration requests to the third-party account system through the script of the interfaces() process.

**Comment by kebiao** [comment]
https://github.com/kbengine/kbengine/blob/master/assets/scripts/interface/kbemain.py

**Comment by VTaredi** [comment]
No, i need it in this. Same as account i create Profile entity on login app, init it as proxy at base app?

**Comment by VTaredi** [comment]
`	<Properties>

	    <email>
	        <Type>UNICODE</Type>
	        <Flags>BASE</Flags>
	    </email>
	    <username>
	        <Type>UNICODE</Type>
	        <Flags>BASE</Flags>
	    </username>
	    <password>
	        <Type>UNICODE</Type>
	        <Flags>BASE</Flags>
	    </password>

	</Properties>

	<ClientMethods>
	    <TryRegister>
	        <Arg>UNICODE</Arg>
	        <Arg>UNICODE</Arg>
	        <Arg>UNICODE</Arg>
	    </TryRegister>
	    <TryLogin>
	        <Arg>UNICODE</Arg>
	        <Arg>UNICODE</Arg>
	    </TryLogin>
	</ClientMethods>`

**Comment by kebiao** [comment]
Write the script "Interfaces.exe" and forward it to your own account system to fulfill your needs.
