### ISSUE TITLE
js插件粘包和拼包处理

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#784]
非浏览器环境可能有不完整包和粘包情况

**Comment by cchorseless** [comment]
期待

**Comment by kebiao** [comment]
https://bbs.comblockengine.com/forum.php?mod=viewthread&tid=6864&extra=page%3D1

**Comment by Wandar** [comment]
https://github.com/Wandar/kbengine_ts_plugin我做了个ts插件,支持2.0和分包处理

**Comment by cchorseless** [comment]
js 插件有问题。
1、case FragmentDataTypes.NETWORK_MESSAGE_LENGTH_SIZE:
					app.currMsgLen = fragmentStream.readUint16();
					app.fragmentStream = null;
					break;

2、 KBEngine.NETWORK_MESSAGE_LENGTH_SIZE);
