### ISSUE TITLE
wss通讯测试

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#805]
配置好证书，在公网测试loginapp能否正常接收js插件wss登录

		
		<sslCertificate> key/server_cert.pem </sslCertificate>
		<sslPrivateKey> key/server_key.pem </sslPrivateKey>
	</channelCommon>

**Comment by maomaoispan** [comment]
请问已经支持WSS了吗，是JS插件支持了吗？谢谢

**Comment by kebiao** [comment]
正在支持， 等测试

**Comment by kebiao** [comment]
已经支持
