### ISSUE TITLE
log4cxx改变了log级别， 日志仍然可以发往logger，应该根据级别屏蔽日志。

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#829]

**Comment by LogicCoder** [comment]
这个啥时候能好啊，挺重要的，现在要么一堆日志塞满硬盘，要么就没日志

**Comment by kbengine** [comment]
你可以用log4cxx配置限制日志文件大小。
关闭logger进程， 程序本地日志是支持调级别的

**Comment by LogicCoder** [comment]
期待正式版，限制大小不解决根本问题，毕竟核心矛盾是想打印的内容少，而不想打印的内容占满了打印空间

**Comment by kebiao** [comment]
已经实现

**Comment by kebiao** [comment]
修改logger.properties其中不同进程的输出级别即可过滤

**Comment by kebiao** [comment]
级别：
                    FATAL_INT = 50000,
                    ERROR_INT = 40000,
                    WARN_INT = 30000,
                    INFO_INT = 20000,
                    DEBUG_INT = 10000,
                    TRACE_INT = 5000,

如果设置为WARN， 则id小于30000的都将不再输出。
