### ISSUE TITLE
非源码版本UE4编译插件报cryptlib.lib link错误

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#839]
https://bbs.comblockengine.com/forum.php?mod=viewthread&tid=6885&extra=page%3D1&page=2

 可能是非源码版本不带这个第三方库， 尝试修改插件， 判断是否有cryptlib这个库， 没有的话， 插件不编译加密通讯模块。

**Comment by xiaoaq** [comment]
非源码版ue4缺失cryptlib.lib问题可通过如下解决。
去cryptopp官网下载对应版本源码编译生成库(源码很小,所以编译过程很快的)，然后拷贝到ue4安装目录的相关文件夹下即可。
详见：
官网：https://www.cryptopp.com/
编译使用方法：http://gad.qq.com/article/detail/38929

**Comment by kebiao** [comment]
是个办法， 不过不是特别友好，尽量做到简单化安装无需再去下载什么

**Comment by kebiao** [comment]
是

**Comment by xiaoaq** [comment]
换了ue4的21版本，我之前的方法没用。。
柯大第一种方法是哪个工程的文件。
第二中代码里添加宏条件，是哪个代码里？

**Comment by kebiao** [comment]
只是一种想法，还没验证和实施
