### ISSUE TITLE
相关插件pause之后 和 resume之前 进行deregister 的话是没有效果的，不会真正注销事件的，resume之后还会触发

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#859]
如果是UE4， 也许会crash。

检查一下

**Comment by maomaoispan** [comment]
我的改发，望参考：

while(this._fireEvents.length > 0)
                {
                        var eobj = this._fireEvents.shift();
                        // var info = eobj.evtInfo;
                        // var ars = eobj.ars;

                        // if(ars.length < 1)
                        // {
                        //         info.callbackfn.apply(info.classinst);
                        // }
                        // else
                        // {
                        //         info.callbackfn.apply(info.classinst, ars);
                        // }

                        this.fire.apply(this,eobj)
                }


resume函数里面注销的部分和新加的一行代码：
        this.resume = function()
        {
                this._isPause = false;


                while(this._fireEvents.length > 0)
                {
                        var eobj = this._fireEvents.shift();
                        // var info = eobj.evtInfo;
                        // var ars = eobj.ars;

                        // if(ars.length < 1)
                        // {
                        //         info.callbackfn.apply(info.classinst);
                        // }
                        // else
                        // {
                        //         info.callbackfn.apply(info.classinst, ars);
                        // }

                        this.fire.apply(this,eobj)
                }
        }
