### ISSUE TITLE
KBEngine.urlopen Get 宕机

### ISSUE THREAD

**Issue by TraditoreZ** [kbengine/kbengine#917]
![tim 20181203200101](https://user-images.githubusercontent.com/18109168/49372642-499b2880-f736-11e8-8521-c280f72548e7.png)
![tim 20181203200104](https://user-images.githubusercontent.com/18109168/49372649-4dc74600-f736-11e8-8374-4c041943a6c7.jpg)
用最新版本 想测试一下Http的异步Get 结果一直宕机 百分之百必现

**Comment by kebiao** [comment]
更新到最新提交
