### ISSUE TITLE
服务器dbmgr配置提供一个选项， 是否允许该组服的数据库共享给其他服

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#938]
由于当前默认是共享的， 开发期间很容易更换uid导致认为在其他服登录无法再次登录上游戏。
默认设置为不共享， 需要共享自己打开。

不共享的情况下， 每次起服自动删除entitylog表重建。

**Comment by jay602** [comment]
1： serverlog加个字段  是否允许共享数据库
2：配置加个选项， 默认不共享数据
3：服务器起来后dbmgr先检查serverlog
    1：当自己是共享数据库状态时，检查是否有服务器是不共享数据库的， 如果有那么报错， 启动失败， 因为不能删除entitylog。
    2： 如果自己是不共享数据库状态时， 检查serverlog发现有其他服是共享数据库状态时启动出错， 因为不能删除entitylog。
