### ISSUE TITLE
实体属性 新增标签  是否自动存档

### ISSUE THREAD

**Issue by cchorseless** [kbengine/kbengine#973]
现在 修改 自动存档的策略 只能在 entity 层面上。
能否 在entity 属性 层面上，增加一个标签 标识 是否自动存档 用来 标识一些大数据属性

**Comment by kebiao** [comment]
意义不是很大， 大数据你应该摘出去自己维护存档。  entity层面的大数据存档以后会考虑优化， 优化就问题不大。
