### ISSUE TITLE
当实体处于ghost pending状态时，一些base发往cell的实体系统请求可能丢给了ghost实体而后丢失

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#978]
需要中转给real

**Comment by kebiao** [comment]
https://github.com/kbengine/kbengine/issues/905

**Comment by jay602** [comment]
由于baseapp上发送给cellapp实体的消息途中（Entity::onLoseWitness）， 实体由于从cellapp1 teleport到cellapp2的过程中在cellapp1上临时设置为ghost状态了， cellapp2上才是real实体， 而baseapp发给cellapp1上的ghost实体没有将消息继续中转给real， 就造成了一些意外情况

参考这个做转发
				if(!entity->isReal())
				{
					GhostManager* gm = Cellapp::getSingleton().pGhostManager();
					if(gm)
					{
						Network::Bundle* pBundle = gm->createSendBundle(entity->realCell());
						pBundle->newMessage(CellappInterface::onEntityCall);
						(*pBundle) << eid << calltype;
						pBundle->append(s);
						gm->pushMessage(entity->realCell(), pBundle);
					}
				}
				else
				{
					entity->onRemoteMethodCall(pChannel, s);
				}

**Comment by jay602** [comment]
测试 1个baseapp，2个cellapp
1: demo avatar进入场景， 日志看在哪个cellapp上， 然后看另外一个cellapp上创建了哪个space
2：在avatar base加个方法， 方法内调用teleport到另外一个space上， 可通过遍历spaces中的space获得space的cell， 看看哪个cell跟自己不是一个进程， 就传送到哪个space上。
teleport之后的下一行， 立即将自己giveClientTo到Account实体。

3：看cellapp日志是否出现预期的情况

**Comment by jay602** [comment]
CellappInterface::onRemoteCallMethodFromClient
CellappInterface::onUpdateDataFromClientForControlledEntity
CellappInterface::onUpdateDataFromClient
CellappInterface::forwardEntityMessageToCellappFromClient
CellappInterface::onDestroyCellEntityFromBaseapp
CellappInterface::reqBackupEntityCellData
CellappInterface::onLoseWitness
ClientInterface::onEntityDestroyed
CellappInterface::onGetWitnessFromBase
CellappInterface::teleportFromBaseapp
CellappInterface::reqTeleportToCellAppOver
CellappInterface::reqWriteToDBFromBaseapp
